package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.math.BigDecimal;
import java.util.Date;

public class Accident implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.description
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.modified_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.created_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.owner_node_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.since
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Date since;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.until
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Date until;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.construction_site_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long constructionSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.person_employment_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private Long personEmploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.duration
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private BigDecimal duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accident.note
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.id
     *
     * @return the value of accident.id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.id
     *
     * @param id the value for accident.id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.description
     *
     * @return the value of accident.description
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.description
     *
     * @param description the value for accident.description
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.modified_stamp
     *
     * @return the value of accident.modified_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.modified_stamp
     *
     * @param modifiedStamp the value for accident.modified_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.created_stamp
     *
     * @return the value of accident.created_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.created_stamp
     *
     * @param createdStamp the value for accident.created_stamp
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.created_by_user_id
     *
     * @return the value of accident.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.created_by_user_id
     *
     * @param createdByUserId the value for accident.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.modified_by_user_id
     *
     * @return the value of accident.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.modified_by_user_id
     *
     * @param modifiedByUserId the value for accident.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.owner_node_id
     *
     * @return the value of accident.owner_node_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.owner_node_id
     *
     * @param ownerNodeId the value for accident.owner_node_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.since
     *
     * @return the value of accident.since
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Date getSince() {
        return since;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.since
     *
     * @param since the value for accident.since
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setSince(Date since) {
        this.since = since;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.until
     *
     * @return the value of accident.until
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Date getUntil() {
        return until;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.until
     *
     * @param until the value for accident.until
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setUntil(Date until) {
        this.until = until;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.construction_site_id
     *
     * @return the value of accident.construction_site_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getConstructionSiteId() {
        return constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.construction_site_id
     *
     * @param constructionSiteId the value for accident.construction_site_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setConstructionSiteId(Long constructionSiteId) {
        this.constructionSiteId = constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.person_employment_id
     *
     * @return the value of accident.person_employment_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public Long getPersonEmploymentId() {
        return personEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.person_employment_id
     *
     * @param personEmploymentId the value for accident.person_employment_id
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setPersonEmploymentId(Long personEmploymentId) {
        this.personEmploymentId = personEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.duration
     *
     * @return the value of accident.duration
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public BigDecimal getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.duration
     *
     * @param duration the value for accident.duration
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accident.note
     *
     * @return the value of accident.note
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accident.note
     *
     * @param note the value for accident.note
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}