package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.enumeration.JobStatus;
import it.memelabs.smartnebula.lmm.persistence.enumeration.JobType;
import it.memelabs.smartnebula.lmm.persistence.enumeration.ReferenceObject;
import java.util.Date;

public class ActivityJob implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.description
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.created_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.created_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.modified_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.modified_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.scheduled_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Date scheduledStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.consumed_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Date consumedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.status
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private JobStatus status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.type
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private JobType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.commit_required
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Boolean commitRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.reference_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Long referenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.fail_message
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private String failMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.reference_object
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private ReferenceObject referenceObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job.owner_node_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.id
     *
     * @return the value of activity_job.id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.id
     *
     * @param id the value for activity_job.id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.description
     *
     * @return the value of activity_job.description
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.description
     *
     * @param description the value for activity_job.description
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.created_stamp
     *
     * @return the value of activity_job.created_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.created_stamp
     *
     * @param createdStamp the value for activity_job.created_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.created_by_user_id
     *
     * @return the value of activity_job.created_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.created_by_user_id
     *
     * @param createdByUserId the value for activity_job.created_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.modified_stamp
     *
     * @return the value of activity_job.modified_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.modified_stamp
     *
     * @param modifiedStamp the value for activity_job.modified_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.modified_by_user_id
     *
     * @return the value of activity_job.modified_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.modified_by_user_id
     *
     * @param modifiedByUserId the value for activity_job.modified_by_user_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.scheduled_stamp
     *
     * @return the value of activity_job.scheduled_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Date getScheduledStamp() {
        return scheduledStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.scheduled_stamp
     *
     * @param scheduledStamp the value for activity_job.scheduled_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setScheduledStamp(Date scheduledStamp) {
        this.scheduledStamp = scheduledStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.consumed_stamp
     *
     * @return the value of activity_job.consumed_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Date getConsumedStamp() {
        return consumedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.consumed_stamp
     *
     * @param consumedStamp the value for activity_job.consumed_stamp
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setConsumedStamp(Date consumedStamp) {
        this.consumedStamp = consumedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.status
     *
     * @return the value of activity_job.status
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public JobStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.status
     *
     * @param status the value for activity_job.status
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setStatus(JobStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.type
     *
     * @return the value of activity_job.type
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public JobType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.type
     *
     * @param type the value for activity_job.type
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setType(JobType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.commit_required
     *
     * @return the value of activity_job.commit_required
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Boolean getCommitRequired() {
        return commitRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.commit_required
     *
     * @param commitRequired the value for activity_job.commit_required
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setCommitRequired(Boolean commitRequired) {
        this.commitRequired = commitRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.reference_id
     *
     * @return the value of activity_job.reference_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Long getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.reference_id
     *
     * @param referenceId the value for activity_job.reference_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setReferenceId(Long referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.fail_message
     *
     * @return the value of activity_job.fail_message
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public String getFailMessage() {
        return failMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.fail_message
     *
     * @param failMessage the value for activity_job.fail_message
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setFailMessage(String failMessage) {
        this.failMessage = failMessage == null ? null : failMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.reference_object
     *
     * @return the value of activity_job.reference_object
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public ReferenceObject getReferenceObject() {
        return referenceObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.reference_object
     *
     * @param referenceObject the value for activity_job.reference_object
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setReferenceObject(ReferenceObject referenceObject) {
        this.referenceObject = referenceObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job.owner_node_id
     *
     * @return the value of activity_job.owner_node_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job.owner_node_id
     *
     * @param ownerNodeId the value for activity_job.owner_node_id
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }
}