package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.enumeration.JobStatus;
import it.memelabs.smartnebula.lmm.persistence.enumeration.JobType;
import it.memelabs.smartnebula.lmm.persistence.enumeration.ReferenceObject;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityJobExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public ActivityJobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> statusCriteria;

        protected List<Criterion> typeCriteria;

        protected List<Criterion> referenceObjectCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            statusCriteria = new ArrayList<Criterion>();
            typeCriteria = new ArrayList<Criterion>();
            referenceObjectCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStatusCriteria() {
            return statusCriteria;
        }

        protected void addStatusCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStatusCriterion(String condition, JobStatus value1, JobStatus value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getTypeCriteria() {
            return typeCriteria;
        }

        protected void addTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            typeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addTypeCriterion(String condition, JobType value1, JobType value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            typeCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getReferenceObjectCriteria() {
            return referenceObjectCriteria;
        }

        protected void addReferenceObjectCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            referenceObjectCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addReferenceObjectCriterion(String condition, ReferenceObject value1, ReferenceObject value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            referenceObjectCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || statusCriteria.size() > 0
                || typeCriteria.size() > 0
                || referenceObjectCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(statusCriteria);
                allCriteria.addAll(typeCriteria);
                allCriteria.addAll(referenceObjectCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andScheduledStampIsNull() {
            addCriterion("scheduled_stamp is null");
            return (Criteria) this;
        }

        public Criteria andScheduledStampIsNotNull() {
            addCriterion("scheduled_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledStampEqualTo(Date value) {
            addCriterion("scheduled_stamp =", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampNotEqualTo(Date value) {
            addCriterion("scheduled_stamp <>", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampGreaterThan(Date value) {
            addCriterion("scheduled_stamp >", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampGreaterThanOrEqualTo(Date value) {
            addCriterion("scheduled_stamp >=", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampLessThan(Date value) {
            addCriterion("scheduled_stamp <", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampLessThanOrEqualTo(Date value) {
            addCriterion("scheduled_stamp <=", value, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampIn(List<Date> values) {
            addCriterion("scheduled_stamp in", values, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampNotIn(List<Date> values) {
            addCriterion("scheduled_stamp not in", values, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampBetween(Date value1, Date value2) {
            addCriterion("scheduled_stamp between", value1, value2, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andScheduledStampNotBetween(Date value1, Date value2) {
            addCriterion("scheduled_stamp not between", value1, value2, "scheduledStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampIsNull() {
            addCriterion("consumed_stamp is null");
            return (Criteria) this;
        }

        public Criteria andConsumedStampIsNotNull() {
            addCriterion("consumed_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andConsumedStampEqualTo(Date value) {
            addCriterion("consumed_stamp =", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampNotEqualTo(Date value) {
            addCriterion("consumed_stamp <>", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampGreaterThan(Date value) {
            addCriterion("consumed_stamp >", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("consumed_stamp >=", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampLessThan(Date value) {
            addCriterion("consumed_stamp <", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampLessThanOrEqualTo(Date value) {
            addCriterion("consumed_stamp <=", value, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampIn(List<Date> values) {
            addCriterion("consumed_stamp in", values, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampNotIn(List<Date> values) {
            addCriterion("consumed_stamp not in", values, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampBetween(Date value1, Date value2) {
            addCriterion("consumed_stamp between", value1, value2, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andConsumedStampNotBetween(Date value1, Date value2) {
            addCriterion("consumed_stamp not between", value1, value2, "consumedStamp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(JobStatus value) {
            addStatusCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(JobStatus value) {
            addStatusCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(JobStatus value) {
            addStatusCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(JobStatus value) {
            addStatusCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(JobStatus value) {
            addStatusCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(JobStatus value) {
            addStatusCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(JobStatus value) {
            addStatusCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(JobStatus value) {
            addStatusCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<JobStatus> values) {
            addStatusCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<JobStatus> values) {
            addStatusCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(JobStatus value1, JobStatus value2) {
            addStatusCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(JobStatus value1, JobStatus value2) {
            addStatusCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(JobType value) {
            addTypeCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(JobType value) {
            addTypeCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(JobType value) {
            addTypeCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(JobType value) {
            addTypeCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(JobType value) {
            addTypeCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(JobType value) {
            addTypeCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(JobType value) {
            addTypeCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(JobType value) {
            addTypeCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<JobType> values) {
            addTypeCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<JobType> values) {
            addTypeCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(JobType value1, JobType value2) {
            addTypeCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(JobType value1, JobType value2) {
            addTypeCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredIsNull() {
            addCriterion("commit_required is null");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredIsNotNull() {
            addCriterion("commit_required is not null");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredEqualTo(Boolean value) {
            addCriterion("commit_required =", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredNotEqualTo(Boolean value) {
            addCriterion("commit_required <>", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredGreaterThan(Boolean value) {
            addCriterion("commit_required >", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredGreaterThanOrEqualTo(Boolean value) {
            addCriterion("commit_required >=", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredLessThan(Boolean value) {
            addCriterion("commit_required <", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredLessThanOrEqualTo(Boolean value) {
            addCriterion("commit_required <=", value, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredIn(List<Boolean> values) {
            addCriterion("commit_required in", values, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredNotIn(List<Boolean> values) {
            addCriterion("commit_required not in", values, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredBetween(Boolean value1, Boolean value2) {
            addCriterion("commit_required between", value1, value2, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andCommitRequiredNotBetween(Boolean value1, Boolean value2) {
            addCriterion("commit_required not between", value1, value2, "commitRequired");
            return (Criteria) this;
        }

        public Criteria andReferenceIdIsNull() {
            addCriterion("reference_id is null");
            return (Criteria) this;
        }

        public Criteria andReferenceIdIsNotNull() {
            addCriterion("reference_id is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceIdEqualTo(Long value) {
            addCriterion("reference_id =", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdNotEqualTo(Long value) {
            addCriterion("reference_id <>", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdGreaterThan(Long value) {
            addCriterion("reference_id >", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("reference_id >=", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdLessThan(Long value) {
            addCriterion("reference_id <", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdLessThanOrEqualTo(Long value) {
            addCriterion("reference_id <=", value, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdIn(List<Long> values) {
            addCriterion("reference_id in", values, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdNotIn(List<Long> values) {
            addCriterion("reference_id not in", values, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdBetween(Long value1, Long value2) {
            addCriterion("reference_id between", value1, value2, "referenceId");
            return (Criteria) this;
        }

        public Criteria andReferenceIdNotBetween(Long value1, Long value2) {
            addCriterion("reference_id not between", value1, value2, "referenceId");
            return (Criteria) this;
        }

        public Criteria andFailMessageIsNull() {
            addCriterion("fail_message is null");
            return (Criteria) this;
        }

        public Criteria andFailMessageIsNotNull() {
            addCriterion("fail_message is not null");
            return (Criteria) this;
        }

        public Criteria andFailMessageEqualTo(String value) {
            addCriterion("fail_message =", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageNotEqualTo(String value) {
            addCriterion("fail_message <>", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageGreaterThan(String value) {
            addCriterion("fail_message >", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageGreaterThanOrEqualTo(String value) {
            addCriterion("fail_message >=", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageLessThan(String value) {
            addCriterion("fail_message <", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageLessThanOrEqualTo(String value) {
            addCriterion("fail_message <=", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageLike(String value) {
            addCriterion("fail_message like", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageNotLike(String value) {
            addCriterion("fail_message not like", value, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageIn(List<String> values) {
            addCriterion("fail_message in", values, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageNotIn(List<String> values) {
            addCriterion("fail_message not in", values, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageBetween(String value1, String value2) {
            addCriterion("fail_message between", value1, value2, "failMessage");
            return (Criteria) this;
        }

        public Criteria andFailMessageNotBetween(String value1, String value2) {
            addCriterion("fail_message not between", value1, value2, "failMessage");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectIsNull() {
            addCriterion("reference_object is null");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectIsNotNull() {
            addCriterion("reference_object is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectEqualTo(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object =", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectNotEqualTo(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object <>", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectGreaterThan(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object >", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectGreaterThanOrEqualTo(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object >=", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectLessThan(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object <", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectLessThanOrEqualTo(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object <=", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectLike(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object like", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectNotLike(ReferenceObject value) {
            addReferenceObjectCriterion("reference_object not like", value, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectIn(List<ReferenceObject> values) {
            addReferenceObjectCriterion("reference_object in", values, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectNotIn(List<ReferenceObject> values) {
            addReferenceObjectCriterion("reference_object not in", values, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectBetween(ReferenceObject value1, ReferenceObject value2) {
            addReferenceObjectCriterion("reference_object between", value1, value2, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andReferenceObjectNotBetween(ReferenceObject value1, ReferenceObject value2) {
            addReferenceObjectCriterion("reference_object not between", value1, value2, "referenceObject");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andFailMessageLikeInsensitive(String value) {
            addCriterion("lower(fail_message) like", (value != null) ? value.toLowerCase() : value , "failMessage");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andFailMessageEqualToInsensitive(String value) {
            addCriterion("lower(fail_message) =", (value != null) ? value.toLowerCase() : value , "failMessage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 08 11:32:05 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}