package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.enumeration.AttributeType;
import java.util.ArrayList;
import java.util.List;

public class ActivityJobAttributeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public ActivityJobAttributeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> attrTypeIdCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            attrTypeIdCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getAttrTypeIdCriteria() {
            return attrTypeIdCriteria;
        }

        protected void addAttrTypeIdCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            attrTypeIdCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addAttrTypeIdCriterion(String condition, AttributeType value1, AttributeType value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            attrTypeIdCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || attrTypeIdCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(attrTypeIdCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Long value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Long value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Long value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Long value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Long value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Long> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Long> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Long value1, Long value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Long value1, Long value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andAttrNameIsNull() {
            addCriterion("attr_name is null");
            return (Criteria) this;
        }

        public Criteria andAttrNameIsNotNull() {
            addCriterion("attr_name is not null");
            return (Criteria) this;
        }

        public Criteria andAttrNameEqualTo(String value) {
            addCriterion("attr_name =", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotEqualTo(String value) {
            addCriterion("attr_name <>", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameGreaterThan(String value) {
            addCriterion("attr_name >", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameGreaterThanOrEqualTo(String value) {
            addCriterion("attr_name >=", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLessThan(String value) {
            addCriterion("attr_name <", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLessThanOrEqualTo(String value) {
            addCriterion("attr_name <=", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameLike(String value) {
            addCriterion("attr_name like", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotLike(String value) {
            addCriterion("attr_name not like", value, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameIn(List<String> values) {
            addCriterion("attr_name in", values, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotIn(List<String> values) {
            addCriterion("attr_name not in", values, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameBetween(String value1, String value2) {
            addCriterion("attr_name between", value1, value2, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrNameNotBetween(String value1, String value2) {
            addCriterion("attr_name not between", value1, value2, "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrValueIsNull() {
            addCriterion("attr_value is null");
            return (Criteria) this;
        }

        public Criteria andAttrValueIsNotNull() {
            addCriterion("attr_value is not null");
            return (Criteria) this;
        }

        public Criteria andAttrValueEqualTo(String value) {
            addCriterion("attr_value =", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueNotEqualTo(String value) {
            addCriterion("attr_value <>", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueGreaterThan(String value) {
            addCriterion("attr_value >", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueGreaterThanOrEqualTo(String value) {
            addCriterion("attr_value >=", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueLessThan(String value) {
            addCriterion("attr_value <", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueLessThanOrEqualTo(String value) {
            addCriterion("attr_value <=", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueLike(String value) {
            addCriterion("attr_value like", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueNotLike(String value) {
            addCriterion("attr_value not like", value, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueIn(List<String> values) {
            addCriterion("attr_value in", values, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueNotIn(List<String> values) {
            addCriterion("attr_value not in", values, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueBetween(String value1, String value2) {
            addCriterion("attr_value between", value1, value2, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrValueNotBetween(String value1, String value2) {
            addCriterion("attr_value not between", value1, value2, "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdIsNull() {
            addCriterion("attr_type_id is null");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdIsNotNull() {
            addCriterion("attr_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdEqualTo(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id =", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdNotEqualTo(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id <>", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdGreaterThan(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id >", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdGreaterThanOrEqualTo(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id >=", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdLessThan(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id <", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdLessThanOrEqualTo(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id <=", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdLike(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id like", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdNotLike(AttributeType value) {
            addAttrTypeIdCriterion("attr_type_id not like", value, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdIn(List<AttributeType> values) {
            addAttrTypeIdCriterion("attr_type_id in", values, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdNotIn(List<AttributeType> values) {
            addAttrTypeIdCriterion("attr_type_id not in", values, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdBetween(AttributeType value1, AttributeType value2) {
            addAttrTypeIdCriterion("attr_type_id between", value1, value2, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrTypeIdNotBetween(AttributeType value1, AttributeType value2) {
            addAttrTypeIdCriterion("attr_type_id not between", value1, value2, "attrTypeId");
            return (Criteria) this;
        }

        public Criteria andAttrNameLikeInsensitive(String value) {
            addCriterion("lower(attr_name) like", (value != null) ? value.toLowerCase() : value , "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrValueLikeInsensitive(String value) {
            addCriterion("lower(attr_value) like", (value != null) ? value.toLowerCase() : value , "attrValue");
            return (Criteria) this;
        }

        public Criteria andAttrNameEqualToInsensitive(String value) {
            addCriterion("lower(attr_name) =", (value != null) ? value.toLowerCase() : value , "attrName");
            return (Criteria) this;
        }

        public Criteria andAttrValueEqualToInsensitive(String value) {
            addCriterion("lower(attr_value) =", (value != null) ? value.toLowerCase() : value , "attrValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job_attribute
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 08 11:50:41 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_job_attribute
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}