package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.enumeration.AttributeType;

public class ActivityJobAttribute extends ActivityJobAttributeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job_attribute.attr_value
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_job_attribute.attr_type_id
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    private AttributeType attrTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job_attribute.attr_value
     *
     * @return the value of activity_job_attribute.attr_value
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job_attribute.attr_value
     *
     * @param attrValue the value for activity_job_attribute.attr_value
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_job_attribute.attr_type_id
     *
     * @return the value of activity_job_attribute.attr_type_id
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public AttributeType getAttrTypeId() {
        return attrTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_job_attribute.attr_type_id
     *
     * @param attrTypeId the value for activity_job_attribute.attr_type_id
     *
     * @mbggenerated Mon Aug 08 11:50:41 CEST 2016
     */
    public void setAttrTypeId(AttributeType attrTypeId) {
        this.attrTypeId = attrTypeId;
    }
}