package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import java.util.Date;

public class AntimafiaProcess implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.description
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.created_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.modified_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.created_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.modified_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.owner_node_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.company_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.prefecture_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long prefectureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.state_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.lot_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long lotId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.causal_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Long causalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.expiry_date
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.note
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antimafia_process.state_tag
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    private EntityStateTag stateTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.id
     *
     * @return the value of antimafia_process.id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.id
     *
     * @param id the value for antimafia_process.id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.description
     *
     * @return the value of antimafia_process.description
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.description
     *
     * @param description the value for antimafia_process.description
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.created_stamp
     *
     * @return the value of antimafia_process.created_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.created_stamp
     *
     * @param createdStamp the value for antimafia_process.created_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.modified_stamp
     *
     * @return the value of antimafia_process.modified_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.modified_stamp
     *
     * @param modifiedStamp the value for antimafia_process.modified_stamp
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.created_by_user_id
     *
     * @return the value of antimafia_process.created_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.created_by_user_id
     *
     * @param createdByUserId the value for antimafia_process.created_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.modified_by_user_id
     *
     * @return the value of antimafia_process.modified_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.modified_by_user_id
     *
     * @param modifiedByUserId the value for antimafia_process.modified_by_user_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.owner_node_id
     *
     * @return the value of antimafia_process.owner_node_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.owner_node_id
     *
     * @param ownerNodeId the value for antimafia_process.owner_node_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.company_id
     *
     * @return the value of antimafia_process.company_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.company_id
     *
     * @param companyId the value for antimafia_process.company_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.prefecture_id
     *
     * @return the value of antimafia_process.prefecture_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getPrefectureId() {
        return prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.prefecture_id
     *
     * @param prefectureId the value for antimafia_process.prefecture_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setPrefectureId(Long prefectureId) {
        this.prefectureId = prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.state_id
     *
     * @return the value of antimafia_process.state_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.state_id
     *
     * @param stateId the value for antimafia_process.state_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.lot_id
     *
     * @return the value of antimafia_process.lot_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getLotId() {
        return lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.lot_id
     *
     * @param lotId the value for antimafia_process.lot_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setLotId(Long lotId) {
        this.lotId = lotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.causal_id
     *
     * @return the value of antimafia_process.causal_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Long getCausalId() {
        return causalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.causal_id
     *
     * @param causalId the value for antimafia_process.causal_id
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setCausalId(Long causalId) {
        this.causalId = causalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.expiry_date
     *
     * @return the value of antimafia_process.expiry_date
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.expiry_date
     *
     * @param expiryDate the value for antimafia_process.expiry_date
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.note
     *
     * @return the value of antimafia_process.note
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.note
     *
     * @param note the value for antimafia_process.note
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antimafia_process.state_tag
     *
     * @return the value of antimafia_process.state_tag
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public EntityStateTag getStateTag() {
        return stateTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antimafia_process.state_tag
     *
     * @param stateTag the value for antimafia_process.state_tag
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setStateTag(EntityStateTag stateTag) {
        this.stateTag = stateTag;
    }
}