package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AntimafiaProcessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public AntimafiaProcessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> stateTagCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            stateTagCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStateTagCriteria() {
            return stateTagCriteria;
        }

        protected void addStateTagCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStateTagCriterion(String condition, EntityStateTag value1, EntityStateTag value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || stateTagCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(stateTagCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdIsNull() {
            addCriterion("prefecture_id is null");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdIsNotNull() {
            addCriterion("prefecture_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdEqualTo(Long value) {
            addCriterion("prefecture_id =", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdNotEqualTo(Long value) {
            addCriterion("prefecture_id <>", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdGreaterThan(Long value) {
            addCriterion("prefecture_id >", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prefecture_id >=", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdLessThan(Long value) {
            addCriterion("prefecture_id <", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdLessThanOrEqualTo(Long value) {
            addCriterion("prefecture_id <=", value, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdIn(List<Long> values) {
            addCriterion("prefecture_id in", values, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdNotIn(List<Long> values) {
            addCriterion("prefecture_id not in", values, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdBetween(Long value1, Long value2) {
            addCriterion("prefecture_id between", value1, value2, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andPrefectureIdNotBetween(Long value1, Long value2) {
            addCriterion("prefecture_id not between", value1, value2, "prefectureId");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("state_id is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("state_id is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(Long value) {
            addCriterion("state_id =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(Long value) {
            addCriterion("state_id <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(Long value) {
            addCriterion("state_id >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("state_id >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(Long value) {
            addCriterion("state_id <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(Long value) {
            addCriterion("state_id <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<Long> values) {
            addCriterion("state_id in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<Long> values) {
            addCriterion("state_id not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(Long value1, Long value2) {
            addCriterion("state_id between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(Long value1, Long value2) {
            addCriterion("state_id not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andLotIdIsNull() {
            addCriterion("lot_id is null");
            return (Criteria) this;
        }

        public Criteria andLotIdIsNotNull() {
            addCriterion("lot_id is not null");
            return (Criteria) this;
        }

        public Criteria andLotIdEqualTo(Long value) {
            addCriterion("lot_id =", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotEqualTo(Long value) {
            addCriterion("lot_id <>", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdGreaterThan(Long value) {
            addCriterion("lot_id >", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdGreaterThanOrEqualTo(Long value) {
            addCriterion("lot_id >=", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdLessThan(Long value) {
            addCriterion("lot_id <", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdLessThanOrEqualTo(Long value) {
            addCriterion("lot_id <=", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdIn(List<Long> values) {
            addCriterion("lot_id in", values, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotIn(List<Long> values) {
            addCriterion("lot_id not in", values, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdBetween(Long value1, Long value2) {
            addCriterion("lot_id between", value1, value2, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotBetween(Long value1, Long value2) {
            addCriterion("lot_id not between", value1, value2, "lotId");
            return (Criteria) this;
        }

        public Criteria andCausalIdIsNull() {
            addCriterion("causal_id is null");
            return (Criteria) this;
        }

        public Criteria andCausalIdIsNotNull() {
            addCriterion("causal_id is not null");
            return (Criteria) this;
        }

        public Criteria andCausalIdEqualTo(Long value) {
            addCriterion("causal_id =", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdNotEqualTo(Long value) {
            addCriterion("causal_id <>", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdGreaterThan(Long value) {
            addCriterion("causal_id >", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdGreaterThanOrEqualTo(Long value) {
            addCriterion("causal_id >=", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdLessThan(Long value) {
            addCriterion("causal_id <", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdLessThanOrEqualTo(Long value) {
            addCriterion("causal_id <=", value, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdIn(List<Long> values) {
            addCriterion("causal_id in", values, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdNotIn(List<Long> values) {
            addCriterion("causal_id not in", values, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdBetween(Long value1, Long value2) {
            addCriterion("causal_id between", value1, value2, "causalId");
            return (Criteria) this;
        }

        public Criteria andCausalIdNotBetween(Long value1, Long value2) {
            addCriterion("causal_id not between", value1, value2, "causalId");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIsNull() {
            addCriterion("expiry_date is null");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIsNotNull() {
            addCriterion("expiry_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpiryDateEqualTo(Date value) {
            addCriterionForJDBCDate("expiry_date =", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("expiry_date <>", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateGreaterThan(Date value) {
            addCriterionForJDBCDate("expiry_date >", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expiry_date >=", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateLessThan(Date value) {
            addCriterionForJDBCDate("expiry_date <", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expiry_date <=", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIn(List<Date> values) {
            addCriterionForJDBCDate("expiry_date in", values, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("expiry_date not in", values, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expiry_date between", value1, value2, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expiry_date not between", value1, value2, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNull() {
            addCriterion("state_tag is null");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNotNull() {
            addCriterion("state_tag is not null");
            return (Criteria) this;
        }

        public Criteria andStateTagEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag =", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <>", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThan(EntityStateTag value) {
            addStateTagCriterion("state_tag >", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag >=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThan(EntityStateTag value) {
            addStateTagCriterion("state_tag <", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLike(EntityStateTag value) {
            addStateTagCriterion("state_tag like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotLike(EntityStateTag value) {
            addStateTagCriterion("state_tag not like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag not in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag not between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andNoteLikeInsensitive(String value) {
            addCriterion("lower(note) like", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andNoteEqualToInsensitive(String value) {
            addCriterion("lower(note) =", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table antimafia_process
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 23 11:44:05 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}