package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentEntity;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStatus;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStorage;
import java.util.Date;

public class Attachment implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.description
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.modified_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.created_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.uploaded_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Date uploadedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.uploaded_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long uploadedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.type_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.filename
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.mime_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String mimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.bucket_name
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String bucketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.storage_path
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String storagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.storage_file
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String storageFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.sha1
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String sha1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.size
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.valid_since
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Date validSince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.valid_until
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Date validUntil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.status
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private AttachmentStatus status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.storage_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private AttachmentStorage storageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.owner_node_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.entity
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private AttachmentEntity entity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.company_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.equipment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long equipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.equipment_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long equipmentEmploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.person_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.person_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long personEmploymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.antimafia_process_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long antimafiaProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.antimafia_process_phase_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long antimafiaProcessPhaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.contract_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.reference_year
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String referenceYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.reference_month
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private String referenceMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.accident_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    private Long accidentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.id
     *
     * @return the value of attachment.id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.id
     *
     * @param id the value for attachment.id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.description
     *
     * @return the value of attachment.description
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.description
     *
     * @param description the value for attachment.description
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.modified_stamp
     *
     * @return the value of attachment.modified_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.modified_stamp
     *
     * @param modifiedStamp the value for attachment.modified_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.created_stamp
     *
     * @return the value of attachment.created_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.created_stamp
     *
     * @param createdStamp the value for attachment.created_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.uploaded_stamp
     *
     * @return the value of attachment.uploaded_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Date getUploadedStamp() {
        return uploadedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.uploaded_stamp
     *
     * @param uploadedStamp the value for attachment.uploaded_stamp
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setUploadedStamp(Date uploadedStamp) {
        this.uploadedStamp = uploadedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.created_by_user_id
     *
     * @return the value of attachment.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.created_by_user_id
     *
     * @param createdByUserId the value for attachment.created_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.modified_by_user_id
     *
     * @return the value of attachment.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.modified_by_user_id
     *
     * @param modifiedByUserId the value for attachment.modified_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.uploaded_by_user_id
     *
     * @return the value of attachment.uploaded_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getUploadedByUserId() {
        return uploadedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.uploaded_by_user_id
     *
     * @param uploadedByUserId the value for attachment.uploaded_by_user_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setUploadedByUserId(Long uploadedByUserId) {
        this.uploadedByUserId = uploadedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.type_id
     *
     * @return the value of attachment.type_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.type_id
     *
     * @param typeId the value for attachment.type_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.filename
     *
     * @return the value of attachment.filename
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.filename
     *
     * @param filename the value for attachment.filename
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.mime_type
     *
     * @return the value of attachment.mime_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.mime_type
     *
     * @param mimeType the value for attachment.mime_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType == null ? null : mimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.bucket_name
     *
     * @return the value of attachment.bucket_name
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.bucket_name
     *
     * @param bucketName the value for attachment.bucket_name
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.storage_path
     *
     * @return the value of attachment.storage_path
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getStoragePath() {
        return storagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.storage_path
     *
     * @param storagePath the value for attachment.storage_path
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setStoragePath(String storagePath) {
        this.storagePath = storagePath == null ? null : storagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.storage_file
     *
     * @return the value of attachment.storage_file
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getStorageFile() {
        return storageFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.storage_file
     *
     * @param storageFile the value for attachment.storage_file
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setStorageFile(String storageFile) {
        this.storageFile = storageFile == null ? null : storageFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.sha1
     *
     * @return the value of attachment.sha1
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getSha1() {
        return sha1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.sha1
     *
     * @param sha1 the value for attachment.sha1
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setSha1(String sha1) {
        this.sha1 = sha1 == null ? null : sha1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.size
     *
     * @return the value of attachment.size
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.size
     *
     * @param size the value for attachment.size
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.valid_since
     *
     * @return the value of attachment.valid_since
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Date getValidSince() {
        return validSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.valid_since
     *
     * @param validSince the value for attachment.valid_since
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setValidSince(Date validSince) {
        this.validSince = validSince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.valid_until
     *
     * @return the value of attachment.valid_until
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Date getValidUntil() {
        return validUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.valid_until
     *
     * @param validUntil the value for attachment.valid_until
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setValidUntil(Date validUntil) {
        this.validUntil = validUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.status
     *
     * @return the value of attachment.status
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public AttachmentStatus getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.status
     *
     * @param status the value for attachment.status
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setStatus(AttachmentStatus status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.storage_type
     *
     * @return the value of attachment.storage_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public AttachmentStorage getStorageType() {
        return storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.storage_type
     *
     * @param storageType the value for attachment.storage_type
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setStorageType(AttachmentStorage storageType) {
        this.storageType = storageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.owner_node_id
     *
     * @return the value of attachment.owner_node_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.owner_node_id
     *
     * @param ownerNodeId the value for attachment.owner_node_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.entity
     *
     * @return the value of attachment.entity
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public AttachmentEntity getEntity() {
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.entity
     *
     * @param entity the value for attachment.entity
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setEntity(AttachmentEntity entity) {
        this.entity = entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.company_id
     *
     * @return the value of attachment.company_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.company_id
     *
     * @param companyId the value for attachment.company_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.equipment_id
     *
     * @return the value of attachment.equipment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.equipment_id
     *
     * @param equipmentId the value for attachment.equipment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setEquipmentId(Long equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.equipment_employment_id
     *
     * @return the value of attachment.equipment_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getEquipmentEmploymentId() {
        return equipmentEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.equipment_employment_id
     *
     * @param equipmentEmploymentId the value for attachment.equipment_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setEquipmentEmploymentId(Long equipmentEmploymentId) {
        this.equipmentEmploymentId = equipmentEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.person_id
     *
     * @return the value of attachment.person_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.person_id
     *
     * @param personId the value for attachment.person_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.person_employment_id
     *
     * @return the value of attachment.person_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getPersonEmploymentId() {
        return personEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.person_employment_id
     *
     * @param personEmploymentId the value for attachment.person_employment_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setPersonEmploymentId(Long personEmploymentId) {
        this.personEmploymentId = personEmploymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.antimafia_process_id
     *
     * @return the value of attachment.antimafia_process_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getAntimafiaProcessId() {
        return antimafiaProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.antimafia_process_id
     *
     * @param antimafiaProcessId the value for attachment.antimafia_process_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setAntimafiaProcessId(Long antimafiaProcessId) {
        this.antimafiaProcessId = antimafiaProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.antimafia_process_phase_id
     *
     * @return the value of attachment.antimafia_process_phase_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getAntimafiaProcessPhaseId() {
        return antimafiaProcessPhaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.antimafia_process_phase_id
     *
     * @param antimafiaProcessPhaseId the value for attachment.antimafia_process_phase_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setAntimafiaProcessPhaseId(Long antimafiaProcessPhaseId) {
        this.antimafiaProcessPhaseId = antimafiaProcessPhaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.contract_id
     *
     * @return the value of attachment.contract_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.contract_id
     *
     * @param contractId the value for attachment.contract_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.reference_year
     *
     * @return the value of attachment.reference_year
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getReferenceYear() {
        return referenceYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.reference_year
     *
     * @param referenceYear the value for attachment.reference_year
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setReferenceYear(String referenceYear) {
        this.referenceYear = referenceYear == null ? null : referenceYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.reference_month
     *
     * @return the value of attachment.reference_month
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getReferenceMonth() {
        return referenceMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.reference_month
     *
     * @param referenceMonth the value for attachment.reference_month
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setReferenceMonth(String referenceMonth) {
        this.referenceMonth = referenceMonth == null ? null : referenceMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.accident_id
     *
     * @return the value of attachment.accident_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Long getAccidentId() {
        return accidentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.accident_id
     *
     * @param accidentId the value for attachment.accident_id
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setAccidentId(Long accidentId) {
        this.accidentId = accidentId;
    }
}