package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentEntity;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStatus;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStorage;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttachmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public AttachmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> statusCriteria;

        protected List<Criterion> storageTypeCriteria;

        protected List<Criterion> entityCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            statusCriteria = new ArrayList<Criterion>();
            storageTypeCriteria = new ArrayList<Criterion>();
            entityCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStatusCriteria() {
            return statusCriteria;
        }

        protected void addStatusCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStatusCriterion(String condition, AttachmentStatus value1, AttachmentStatus value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getStorageTypeCriteria() {
            return storageTypeCriteria;
        }

        protected void addStorageTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            storageTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStorageTypeCriterion(String condition, AttachmentStorage value1, AttachmentStorage value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            storageTypeCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getEntityCriteria() {
            return entityCriteria;
        }

        protected void addEntityCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            entityCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addEntityCriterion(String condition, AttachmentEntity value1, AttachmentEntity value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            entityCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || statusCriteria.size() > 0
                || storageTypeCriteria.size() > 0
                || entityCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(statusCriteria);
                allCriteria.addAll(storageTypeCriteria);
                allCriteria.addAll(entityCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIsNull() {
            addCriterion("uploaded_stamp is null");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIsNotNull() {
            addCriterion("uploaded_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andUploadedStampEqualTo(Date value) {
            addCriterion("uploaded_stamp =", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotEqualTo(Date value) {
            addCriterion("uploaded_stamp <>", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampGreaterThan(Date value) {
            addCriterion("uploaded_stamp >", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("uploaded_stamp >=", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampLessThan(Date value) {
            addCriterion("uploaded_stamp <", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampLessThanOrEqualTo(Date value) {
            addCriterion("uploaded_stamp <=", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIn(List<Date> values) {
            addCriterion("uploaded_stamp in", values, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotIn(List<Date> values) {
            addCriterion("uploaded_stamp not in", values, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampBetween(Date value1, Date value2) {
            addCriterion("uploaded_stamp between", value1, value2, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotBetween(Date value1, Date value2) {
            addCriterion("uploaded_stamp not between", value1, value2, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIsNull() {
            addCriterion("uploaded_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIsNotNull() {
            addCriterion("uploaded_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdEqualTo(Long value) {
            addCriterion("uploaded_by_user_id =", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotEqualTo(Long value) {
            addCriterion("uploaded_by_user_id <>", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdGreaterThan(Long value) {
            addCriterion("uploaded_by_user_id >", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("uploaded_by_user_id >=", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdLessThan(Long value) {
            addCriterion("uploaded_by_user_id <", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("uploaded_by_user_id <=", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIn(List<Long> values) {
            addCriterion("uploaded_by_user_id in", values, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotIn(List<Long> values) {
            addCriterion("uploaded_by_user_id not in", values, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdBetween(Long value1, Long value2) {
            addCriterion("uploaded_by_user_id between", value1, value2, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("uploaded_by_user_id not between", value1, value2, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Long value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Long value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Long value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Long value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Long> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Long> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Long value1, Long value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNull() {
            addCriterion("mime_type is null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNotNull() {
            addCriterion("mime_type is not null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeEqualTo(String value) {
            addCriterion("mime_type =", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotEqualTo(String value) {
            addCriterion("mime_type <>", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThan(String value) {
            addCriterion("mime_type >", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("mime_type >=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThan(String value) {
            addCriterion("mime_type <", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThanOrEqualTo(String value) {
            addCriterion("mime_type <=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLike(String value) {
            addCriterion("mime_type like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotLike(String value) {
            addCriterion("mime_type not like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIn(List<String> values) {
            addCriterion("mime_type in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotIn(List<String> values) {
            addCriterion("mime_type not in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeBetween(String value1, String value2) {
            addCriterion("mime_type between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotBetween(String value1, String value2) {
            addCriterion("mime_type not between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNull() {
            addCriterion("bucket_name is null");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNotNull() {
            addCriterion("bucket_name is not null");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualTo(String value) {
            addCriterion("bucket_name =", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotEqualTo(String value) {
            addCriterion("bucket_name <>", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThan(String value) {
            addCriterion("bucket_name >", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThanOrEqualTo(String value) {
            addCriterion("bucket_name >=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThan(String value) {
            addCriterion("bucket_name <", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThanOrEqualTo(String value) {
            addCriterion("bucket_name <=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLike(String value) {
            addCriterion("bucket_name like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotLike(String value) {
            addCriterion("bucket_name not like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameIn(List<String> values) {
            addCriterion("bucket_name in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotIn(List<String> values) {
            addCriterion("bucket_name not in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameBetween(String value1, String value2) {
            addCriterion("bucket_name between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotBetween(String value1, String value2) {
            addCriterion("bucket_name not between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andStoragePathIsNull() {
            addCriterion("storage_path is null");
            return (Criteria) this;
        }

        public Criteria andStoragePathIsNotNull() {
            addCriterion("storage_path is not null");
            return (Criteria) this;
        }

        public Criteria andStoragePathEqualTo(String value) {
            addCriterion("storage_path =", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotEqualTo(String value) {
            addCriterion("storage_path <>", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathGreaterThan(String value) {
            addCriterion("storage_path >", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathGreaterThanOrEqualTo(String value) {
            addCriterion("storage_path >=", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLessThan(String value) {
            addCriterion("storage_path <", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLessThanOrEqualTo(String value) {
            addCriterion("storage_path <=", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLike(String value) {
            addCriterion("storage_path like", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotLike(String value) {
            addCriterion("storage_path not like", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathIn(List<String> values) {
            addCriterion("storage_path in", values, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotIn(List<String> values) {
            addCriterion("storage_path not in", values, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathBetween(String value1, String value2) {
            addCriterion("storage_path between", value1, value2, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotBetween(String value1, String value2) {
            addCriterion("storage_path not between", value1, value2, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileIsNull() {
            addCriterion("storage_file is null");
            return (Criteria) this;
        }

        public Criteria andStorageFileIsNotNull() {
            addCriterion("storage_file is not null");
            return (Criteria) this;
        }

        public Criteria andStorageFileEqualTo(String value) {
            addCriterion("storage_file =", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotEqualTo(String value) {
            addCriterion("storage_file <>", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileGreaterThan(String value) {
            addCriterion("storage_file >", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileGreaterThanOrEqualTo(String value) {
            addCriterion("storage_file >=", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLessThan(String value) {
            addCriterion("storage_file <", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLessThanOrEqualTo(String value) {
            addCriterion("storage_file <=", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLike(String value) {
            addCriterion("storage_file like", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotLike(String value) {
            addCriterion("storage_file not like", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileIn(List<String> values) {
            addCriterion("storage_file in", values, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotIn(List<String> values) {
            addCriterion("storage_file not in", values, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileBetween(String value1, String value2) {
            addCriterion("storage_file between", value1, value2, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotBetween(String value1, String value2) {
            addCriterion("storage_file not between", value1, value2, "storageFile");
            return (Criteria) this;
        }

        public Criteria andSha1IsNull() {
            addCriterion("sha1 is null");
            return (Criteria) this;
        }

        public Criteria andSha1IsNotNull() {
            addCriterion("sha1 is not null");
            return (Criteria) this;
        }

        public Criteria andSha1EqualTo(String value) {
            addCriterion("sha1 =", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotEqualTo(String value) {
            addCriterion("sha1 <>", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1GreaterThan(String value) {
            addCriterion("sha1 >", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1GreaterThanOrEqualTo(String value) {
            addCriterion("sha1 >=", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1LessThan(String value) {
            addCriterion("sha1 <", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1LessThanOrEqualTo(String value) {
            addCriterion("sha1 <=", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1Like(String value) {
            addCriterion("sha1 like", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotLike(String value) {
            addCriterion("sha1 not like", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1In(List<String> values) {
            addCriterion("sha1 in", values, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotIn(List<String> values) {
            addCriterion("sha1 not in", values, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1Between(String value1, String value2) {
            addCriterion("sha1 between", value1, value2, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotBetween(String value1, String value2) {
            addCriterion("sha1 not between", value1, value2, "sha1");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Long value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Long value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Long value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Long value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Long value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Long> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Long> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Long value1, Long value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Long value1, Long value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andValidSinceIsNull() {
            addCriterion("valid_since is null");
            return (Criteria) this;
        }

        public Criteria andValidSinceIsNotNull() {
            addCriterion("valid_since is not null");
            return (Criteria) this;
        }

        public Criteria andValidSinceEqualTo(Date value) {
            addCriterion("valid_since =", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotEqualTo(Date value) {
            addCriterion("valid_since <>", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceGreaterThan(Date value) {
            addCriterion("valid_since >", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceGreaterThanOrEqualTo(Date value) {
            addCriterion("valid_since >=", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceLessThan(Date value) {
            addCriterion("valid_since <", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceLessThanOrEqualTo(Date value) {
            addCriterion("valid_since <=", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceIn(List<Date> values) {
            addCriterion("valid_since in", values, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotIn(List<Date> values) {
            addCriterion("valid_since not in", values, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceBetween(Date value1, Date value2) {
            addCriterion("valid_since between", value1, value2, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotBetween(Date value1, Date value2) {
            addCriterion("valid_since not between", value1, value2, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidUntilIsNull() {
            addCriterion("valid_until is null");
            return (Criteria) this;
        }

        public Criteria andValidUntilIsNotNull() {
            addCriterion("valid_until is not null");
            return (Criteria) this;
        }

        public Criteria andValidUntilEqualTo(Date value) {
            addCriterion("valid_until =", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotEqualTo(Date value) {
            addCriterion("valid_until <>", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilGreaterThan(Date value) {
            addCriterion("valid_until >", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilGreaterThanOrEqualTo(Date value) {
            addCriterion("valid_until >=", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilLessThan(Date value) {
            addCriterion("valid_until <", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilLessThanOrEqualTo(Date value) {
            addCriterion("valid_until <=", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilIn(List<Date> values) {
            addCriterion("valid_until in", values, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotIn(List<Date> values) {
            addCriterion("valid_until not in", values, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilBetween(Date value1, Date value2) {
            addCriterion("valid_until between", value1, value2, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotBetween(Date value1, Date value2) {
            addCriterion("valid_until not between", value1, value2, "validUntil");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(AttachmentStatus value) {
            addStatusCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(AttachmentStatus value) {
            addStatusCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(AttachmentStatus value) {
            addStatusCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(AttachmentStatus value) {
            addStatusCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(AttachmentStatus value) {
            addStatusCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(AttachmentStatus value) {
            addStatusCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(AttachmentStatus value) {
            addStatusCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(AttachmentStatus value) {
            addStatusCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<AttachmentStatus> values) {
            addStatusCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<AttachmentStatus> values) {
            addStatusCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(AttachmentStatus value1, AttachmentStatus value2) {
            addStatusCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(AttachmentStatus value1, AttachmentStatus value2) {
            addStatusCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIsNull() {
            addCriterion("storage_type is null");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIsNotNull() {
            addCriterion("storage_type is not null");
            return (Criteria) this;
        }

        public Criteria andStorageTypeEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type =", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <>", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeGreaterThan(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type >", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeGreaterThanOrEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type >=", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLessThan(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLessThanOrEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <=", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLike(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type like", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotLike(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type not like", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIn(List<AttachmentStorage> values) {
            addStorageTypeCriterion("storage_type in", values, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotIn(List<AttachmentStorage> values) {
            addStorageTypeCriterion("storage_type not in", values, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addStorageTypeCriterion("storage_type between", value1, value2, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addStorageTypeCriterion("storage_type not between", value1, value2, "storageType");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andEntityIsNull() {
            addCriterion("entity is null");
            return (Criteria) this;
        }

        public Criteria andEntityIsNotNull() {
            addCriterion("entity is not null");
            return (Criteria) this;
        }

        public Criteria andEntityEqualTo(AttachmentEntity value) {
            addEntityCriterion("entity =", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotEqualTo(AttachmentEntity value) {
            addEntityCriterion("entity <>", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityGreaterThan(AttachmentEntity value) {
            addEntityCriterion("entity >", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityGreaterThanOrEqualTo(AttachmentEntity value) {
            addEntityCriterion("entity >=", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLessThan(AttachmentEntity value) {
            addEntityCriterion("entity <", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLessThanOrEqualTo(AttachmentEntity value) {
            addEntityCriterion("entity <=", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLike(AttachmentEntity value) {
            addEntityCriterion("entity like", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotLike(AttachmentEntity value) {
            addEntityCriterion("entity not like", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityIn(List<AttachmentEntity> values) {
            addEntityCriterion("entity in", values, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotIn(List<AttachmentEntity> values) {
            addEntityCriterion("entity not in", values, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityBetween(AttachmentEntity value1, AttachmentEntity value2) {
            addEntityCriterion("entity between", value1, value2, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotBetween(AttachmentEntity value1, AttachmentEntity value2) {
            addEntityCriterion("entity not between", value1, value2, "entity");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("equipment_id is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("equipment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(Long value) {
            addCriterion("equipment_id =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(Long value) {
            addCriterion("equipment_id <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(Long value) {
            addCriterion("equipment_id >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("equipment_id >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(Long value) {
            addCriterion("equipment_id <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(Long value) {
            addCriterion("equipment_id <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<Long> values) {
            addCriterion("equipment_id in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<Long> values) {
            addCriterion("equipment_id not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(Long value1, Long value2) {
            addCriterion("equipment_id between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(Long value1, Long value2) {
            addCriterion("equipment_id not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdIsNull() {
            addCriterion("equipment_employment_id is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdIsNotNull() {
            addCriterion("equipment_employment_id is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdEqualTo(Long value) {
            addCriterion("equipment_employment_id =", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdNotEqualTo(Long value) {
            addCriterion("equipment_employment_id <>", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdGreaterThan(Long value) {
            addCriterion("equipment_employment_id >", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("equipment_employment_id >=", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdLessThan(Long value) {
            addCriterion("equipment_employment_id <", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdLessThanOrEqualTo(Long value) {
            addCriterion("equipment_employment_id <=", value, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdIn(List<Long> values) {
            addCriterion("equipment_employment_id in", values, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdNotIn(List<Long> values) {
            addCriterion("equipment_employment_id not in", values, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdBetween(Long value1, Long value2) {
            addCriterion("equipment_employment_id between", value1, value2, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentEmploymentIdNotBetween(Long value1, Long value2) {
            addCriterion("equipment_employment_id not between", value1, value2, "equipmentEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNull() {
            addCriterion("person_id is null");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNotNull() {
            addCriterion("person_id is not null");
            return (Criteria) this;
        }

        public Criteria andPersonIdEqualTo(Long value) {
            addCriterion("person_id =", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotEqualTo(Long value) {
            addCriterion("person_id <>", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThan(Long value) {
            addCriterion("person_id >", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("person_id >=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThan(Long value) {
            addCriterion("person_id <", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThanOrEqualTo(Long value) {
            addCriterion("person_id <=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIn(List<Long> values) {
            addCriterion("person_id in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotIn(List<Long> values) {
            addCriterion("person_id not in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdBetween(Long value1, Long value2) {
            addCriterion("person_id between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotBetween(Long value1, Long value2) {
            addCriterion("person_id not between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdIsNull() {
            addCriterion("person_employment_id is null");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdIsNotNull() {
            addCriterion("person_employment_id is not null");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdEqualTo(Long value) {
            addCriterion("person_employment_id =", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdNotEqualTo(Long value) {
            addCriterion("person_employment_id <>", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdGreaterThan(Long value) {
            addCriterion("person_employment_id >", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("person_employment_id >=", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdLessThan(Long value) {
            addCriterion("person_employment_id <", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdLessThanOrEqualTo(Long value) {
            addCriterion("person_employment_id <=", value, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdIn(List<Long> values) {
            addCriterion("person_employment_id in", values, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdNotIn(List<Long> values) {
            addCriterion("person_employment_id not in", values, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdBetween(Long value1, Long value2) {
            addCriterion("person_employment_id between", value1, value2, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andPersonEmploymentIdNotBetween(Long value1, Long value2) {
            addCriterion("person_employment_id not between", value1, value2, "personEmploymentId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdIsNull() {
            addCriterion("antimafia_process_id is null");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdIsNotNull() {
            addCriterion("antimafia_process_id is not null");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdEqualTo(Long value) {
            addCriterion("antimafia_process_id =", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdNotEqualTo(Long value) {
            addCriterion("antimafia_process_id <>", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdGreaterThan(Long value) {
            addCriterion("antimafia_process_id >", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdGreaterThanOrEqualTo(Long value) {
            addCriterion("antimafia_process_id >=", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdLessThan(Long value) {
            addCriterion("antimafia_process_id <", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdLessThanOrEqualTo(Long value) {
            addCriterion("antimafia_process_id <=", value, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdIn(List<Long> values) {
            addCriterion("antimafia_process_id in", values, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdNotIn(List<Long> values) {
            addCriterion("antimafia_process_id not in", values, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdBetween(Long value1, Long value2) {
            addCriterion("antimafia_process_id between", value1, value2, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessIdNotBetween(Long value1, Long value2) {
            addCriterion("antimafia_process_id not between", value1, value2, "antimafiaProcessId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdIsNull() {
            addCriterion("antimafia_process_phase_id is null");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdIsNotNull() {
            addCriterion("antimafia_process_phase_id is not null");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdEqualTo(Long value) {
            addCriterion("antimafia_process_phase_id =", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdNotEqualTo(Long value) {
            addCriterion("antimafia_process_phase_id <>", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdGreaterThan(Long value) {
            addCriterion("antimafia_process_phase_id >", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("antimafia_process_phase_id >=", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdLessThan(Long value) {
            addCriterion("antimafia_process_phase_id <", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdLessThanOrEqualTo(Long value) {
            addCriterion("antimafia_process_phase_id <=", value, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdIn(List<Long> values) {
            addCriterion("antimafia_process_phase_id in", values, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdNotIn(List<Long> values) {
            addCriterion("antimafia_process_phase_id not in", values, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdBetween(Long value1, Long value2) {
            addCriterion("antimafia_process_phase_id between", value1, value2, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andAntimafiaProcessPhaseIdNotBetween(Long value1, Long value2) {
            addCriterion("antimafia_process_phase_id not between", value1, value2, "antimafiaProcessPhaseId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(Long value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(Long value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(Long value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(Long value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(Long value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(Long value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<Long> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<Long> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(Long value1, Long value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(Long value1, Long value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andReferenceYearIsNull() {
            addCriterion("reference_year is null");
            return (Criteria) this;
        }

        public Criteria andReferenceYearIsNotNull() {
            addCriterion("reference_year is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceYearEqualTo(String value) {
            addCriterion("reference_year =", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearNotEqualTo(String value) {
            addCriterion("reference_year <>", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearGreaterThan(String value) {
            addCriterion("reference_year >", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearGreaterThanOrEqualTo(String value) {
            addCriterion("reference_year >=", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearLessThan(String value) {
            addCriterion("reference_year <", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearLessThanOrEqualTo(String value) {
            addCriterion("reference_year <=", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearLike(String value) {
            addCriterion("reference_year like", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearNotLike(String value) {
            addCriterion("reference_year not like", value, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearIn(List<String> values) {
            addCriterion("reference_year in", values, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearNotIn(List<String> values) {
            addCriterion("reference_year not in", values, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearBetween(String value1, String value2) {
            addCriterion("reference_year between", value1, value2, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceYearNotBetween(String value1, String value2) {
            addCriterion("reference_year not between", value1, value2, "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthIsNull() {
            addCriterion("reference_month is null");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthIsNotNull() {
            addCriterion("reference_month is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthEqualTo(String value) {
            addCriterion("reference_month =", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthNotEqualTo(String value) {
            addCriterion("reference_month <>", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthGreaterThan(String value) {
            addCriterion("reference_month >", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthGreaterThanOrEqualTo(String value) {
            addCriterion("reference_month >=", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthLessThan(String value) {
            addCriterion("reference_month <", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthLessThanOrEqualTo(String value) {
            addCriterion("reference_month <=", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthLike(String value) {
            addCriterion("reference_month like", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthNotLike(String value) {
            addCriterion("reference_month not like", value, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthIn(List<String> values) {
            addCriterion("reference_month in", values, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthNotIn(List<String> values) {
            addCriterion("reference_month not in", values, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthBetween(String value1, String value2) {
            addCriterion("reference_month between", value1, value2, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthNotBetween(String value1, String value2) {
            addCriterion("reference_month not between", value1, value2, "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andAccidentIdIsNull() {
            addCriterion("accident_id is null");
            return (Criteria) this;
        }

        public Criteria andAccidentIdIsNotNull() {
            addCriterion("accident_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccidentIdEqualTo(Long value) {
            addCriterion("accident_id =", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdNotEqualTo(Long value) {
            addCriterion("accident_id <>", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdGreaterThan(Long value) {
            addCriterion("accident_id >", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("accident_id >=", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdLessThan(Long value) {
            addCriterion("accident_id <", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdLessThanOrEqualTo(Long value) {
            addCriterion("accident_id <=", value, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdIn(List<Long> values) {
            addCriterion("accident_id in", values, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdNotIn(List<Long> values) {
            addCriterion("accident_id not in", values, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdBetween(Long value1, Long value2) {
            addCriterion("accident_id between", value1, value2, "accidentId");
            return (Criteria) this;
        }

        public Criteria andAccidentIdNotBetween(Long value1, Long value2) {
            addCriterion("accident_id not between", value1, value2, "accidentId");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andFilenameLikeInsensitive(String value) {
            addCriterion("lower(filename) like", (value != null) ? value.toLowerCase() : value , "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLikeInsensitive(String value) {
            addCriterion("lower(mime_type) like", (value != null) ? value.toLowerCase() : value , "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameLikeInsensitive(String value) {
            addCriterion("lower(bucket_name) like", (value != null) ? value.toLowerCase() : value , "bucketName");
            return (Criteria) this;
        }

        public Criteria andStoragePathLikeInsensitive(String value) {
            addCriterion("lower(storage_path) like", (value != null) ? value.toLowerCase() : value , "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileLikeInsensitive(String value) {
            addCriterion("lower(storage_file) like", (value != null) ? value.toLowerCase() : value , "storageFile");
            return (Criteria) this;
        }

        public Criteria andSha1LikeInsensitive(String value) {
            addCriterion("lower(sha1) like", (value != null) ? value.toLowerCase() : value , "sha1");
            return (Criteria) this;
        }

        public Criteria andReferenceYearLikeInsensitive(String value) {
            addCriterion("lower(reference_year) like", (value != null) ? value.toLowerCase() : value , "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthLikeInsensitive(String value) {
            addCriterion("lower(reference_month) like", (value != null) ? value.toLowerCase() : value , "referenceMonth");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualToInsensitive(String value) {
            addCriterion("lower(filename) =", (value != null) ? value.toLowerCase() : value , "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeEqualToInsensitive(String value) {
            addCriterion("lower(mime_type) =", (value != null) ? value.toLowerCase() : value , "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualToInsensitive(String value) {
            addCriterion("lower(bucket_name) =", (value != null) ? value.toLowerCase() : value , "bucketName");
            return (Criteria) this;
        }

        public Criteria andStoragePathEqualToInsensitive(String value) {
            addCriterion("lower(storage_path) =", (value != null) ? value.toLowerCase() : value , "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileEqualToInsensitive(String value) {
            addCriterion("lower(storage_file) =", (value != null) ? value.toLowerCase() : value , "storageFile");
            return (Criteria) this;
        }

        public Criteria andSha1EqualToInsensitive(String value) {
            addCriterion("lower(sha1) =", (value != null) ? value.toLowerCase() : value , "sha1");
            return (Criteria) this;
        }

        public Criteria andReferenceYearEqualToInsensitive(String value) {
            addCriterion("lower(reference_year) =", (value != null) ? value.toLowerCase() : value , "referenceYear");
            return (Criteria) this;
        }

        public Criteria andReferenceMonthEqualToInsensitive(String value) {
            addCriterion("lower(reference_month) =", (value != null) ? value.toLowerCase() : value , "referenceMonth");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attachment
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 31 18:16:23 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attachment
     *
     * @mbggenerated Mon Oct 31 18:16:23 CET 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}