package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class CompanyClassification implements AbstractIdentifiable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.description
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.modified_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.created_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.created_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.modified_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_classification.owner_node_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.id
     *
     * @return the value of company_classification.id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.id
     *
     * @param id the value for company_classification.id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.description
     *
     * @return the value of company_classification.description
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.description
     *
     * @param description the value for company_classification.description
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.modified_stamp
     *
     * @return the value of company_classification.modified_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.modified_stamp
     *
     * @param modifiedStamp the value for company_classification.modified_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.created_stamp
     *
     * @return the value of company_classification.created_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.created_stamp
     *
     * @param createdStamp the value for company_classification.created_stamp
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.created_by_user_id
     *
     * @return the value of company_classification.created_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.created_by_user_id
     *
     * @param createdByUserId the value for company_classification.created_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.modified_by_user_id
     *
     * @return the value of company_classification.modified_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.modified_by_user_id
     *
     * @param modifiedByUserId the value for company_classification.modified_by_user_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_classification.owner_node_id
     *
     * @return the value of company_classification.owner_node_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_classification.owner_node_id
     *
     * @param ownerNodeId the value for company_classification.owner_node_id
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }
}