package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> stateTagCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            stateTagCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStateTagCriteria() {
            return stateTagCriteria;
        }

        protected void addStateTagCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStateTagCriterion(String condition, EntityStateTag value1, EntityStateTag value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || stateTagCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(stateTagCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNull() {
            addCriterion("business_name is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIsNotNull() {
            addCriterion("business_name is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualTo(String value) {
            addCriterion("business_name =", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotEqualTo(String value) {
            addCriterion("business_name <>", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThan(String value) {
            addCriterion("business_name >", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameGreaterThanOrEqualTo(String value) {
            addCriterion("business_name >=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThan(String value) {
            addCriterion("business_name <", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLessThanOrEqualTo(String value) {
            addCriterion("business_name <=", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLike(String value) {
            addCriterion("business_name like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotLike(String value) {
            addCriterion("business_name not like", value, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameIn(List<String> values) {
            addCriterion("business_name in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotIn(List<String> values) {
            addCriterion("business_name not in", values, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameBetween(String value1, String value2) {
            addCriterion("business_name between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andBusinessNameNotBetween(String value1, String value2) {
            addCriterion("business_name not between", value1, value2, "businessName");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberIsNull() {
            addCriterion("tax_identification_number is null");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberIsNotNull() {
            addCriterion("tax_identification_number is not null");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberEqualTo(String value) {
            addCriterion("tax_identification_number =", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberNotEqualTo(String value) {
            addCriterion("tax_identification_number <>", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberGreaterThan(String value) {
            addCriterion("tax_identification_number >", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberGreaterThanOrEqualTo(String value) {
            addCriterion("tax_identification_number >=", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberLessThan(String value) {
            addCriterion("tax_identification_number <", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberLessThanOrEqualTo(String value) {
            addCriterion("tax_identification_number <=", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberLike(String value) {
            addCriterion("tax_identification_number like", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberNotLike(String value) {
            addCriterion("tax_identification_number not like", value, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberIn(List<String> values) {
            addCriterion("tax_identification_number in", values, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberNotIn(List<String> values) {
            addCriterion("tax_identification_number not in", values, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberBetween(String value1, String value2) {
            addCriterion("tax_identification_number between", value1, value2, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberNotBetween(String value1, String value2) {
            addCriterion("tax_identification_number not between", value1, value2, "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberIsNull() {
            addCriterion("vat_number is null");
            return (Criteria) this;
        }

        public Criteria andVatNumberIsNotNull() {
            addCriterion("vat_number is not null");
            return (Criteria) this;
        }

        public Criteria andVatNumberEqualTo(String value) {
            addCriterion("vat_number =", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberNotEqualTo(String value) {
            addCriterion("vat_number <>", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberGreaterThan(String value) {
            addCriterion("vat_number >", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberGreaterThanOrEqualTo(String value) {
            addCriterion("vat_number >=", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberLessThan(String value) {
            addCriterion("vat_number <", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberLessThanOrEqualTo(String value) {
            addCriterion("vat_number <=", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberLike(String value) {
            addCriterion("vat_number like", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberNotLike(String value) {
            addCriterion("vat_number not like", value, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberIn(List<String> values) {
            addCriterion("vat_number in", values, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberNotIn(List<String> values) {
            addCriterion("vat_number not in", values, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberBetween(String value1, String value2) {
            addCriterion("vat_number between", value1, value2, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberNotBetween(String value1, String value2) {
            addCriterion("vat_number not between", value1, value2, "vatNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeIsNull() {
            addCriterion("company_purpose is null");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeIsNotNull() {
            addCriterion("company_purpose is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeEqualTo(String value) {
            addCriterion("company_purpose =", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeNotEqualTo(String value) {
            addCriterion("company_purpose <>", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeGreaterThan(String value) {
            addCriterion("company_purpose >", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeGreaterThanOrEqualTo(String value) {
            addCriterion("company_purpose >=", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeLessThan(String value) {
            addCriterion("company_purpose <", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeLessThanOrEqualTo(String value) {
            addCriterion("company_purpose <=", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeLike(String value) {
            addCriterion("company_purpose like", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeNotLike(String value) {
            addCriterion("company_purpose not like", value, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeIn(List<String> values) {
            addCriterion("company_purpose in", values, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeNotIn(List<String> values) {
            addCriterion("company_purpose not in", values, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeBetween(String value1, String value2) {
            addCriterion("company_purpose between", value1, value2, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeNotBetween(String value1, String value2) {
            addCriterion("company_purpose not between", value1, value2, "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalIsNull() {
            addCriterion("string_stock_capital is null");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalIsNotNull() {
            addCriterion("string_stock_capital is not null");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalEqualTo(String value) {
            addCriterion("string_stock_capital =", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalNotEqualTo(String value) {
            addCriterion("string_stock_capital <>", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalGreaterThan(String value) {
            addCriterion("string_stock_capital >", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalGreaterThanOrEqualTo(String value) {
            addCriterion("string_stock_capital >=", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalLessThan(String value) {
            addCriterion("string_stock_capital <", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalLessThanOrEqualTo(String value) {
            addCriterion("string_stock_capital <=", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalLike(String value) {
            addCriterion("string_stock_capital like", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalNotLike(String value) {
            addCriterion("string_stock_capital not like", value, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalIn(List<String> values) {
            addCriterion("string_stock_capital in", values, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalNotIn(List<String> values) {
            addCriterion("string_stock_capital not in", values, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalBetween(String value1, String value2) {
            addCriterion("string_stock_capital between", value1, value2, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalNotBetween(String value1, String value2) {
            addCriterion("string_stock_capital not between", value1, value2, "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andClassificationIdIsNull() {
            addCriterion("classification_id is null");
            return (Criteria) this;
        }

        public Criteria andClassificationIdIsNotNull() {
            addCriterion("classification_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassificationIdEqualTo(Long value) {
            addCriterion("classification_id =", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdNotEqualTo(Long value) {
            addCriterion("classification_id <>", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdGreaterThan(Long value) {
            addCriterion("classification_id >", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("classification_id >=", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdLessThan(Long value) {
            addCriterion("classification_id <", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdLessThanOrEqualTo(Long value) {
            addCriterion("classification_id <=", value, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdIn(List<Long> values) {
            addCriterion("classification_id in", values, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdNotIn(List<Long> values) {
            addCriterion("classification_id not in", values, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdBetween(Long value1, Long value2) {
            addCriterion("classification_id between", value1, value2, "classificationId");
            return (Criteria) this;
        }

        public Criteria andClassificationIdNotBetween(Long value1, Long value2) {
            addCriterion("classification_id not between", value1, value2, "classificationId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateIsNull() {
            addCriterion("legal_delegate is null");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateIsNotNull() {
            addCriterion("legal_delegate is not null");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateEqualTo(String value) {
            addCriterion("legal_delegate =", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateNotEqualTo(String value) {
            addCriterion("legal_delegate <>", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateGreaterThan(String value) {
            addCriterion("legal_delegate >", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateGreaterThanOrEqualTo(String value) {
            addCriterion("legal_delegate >=", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateLessThan(String value) {
            addCriterion("legal_delegate <", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateLessThanOrEqualTo(String value) {
            addCriterion("legal_delegate <=", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateLike(String value) {
            addCriterion("legal_delegate like", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateNotLike(String value) {
            addCriterion("legal_delegate not like", value, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateIn(List<String> values) {
            addCriterion("legal_delegate in", values, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateNotIn(List<String> values) {
            addCriterion("legal_delegate not in", values, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateBetween(String value1, String value2) {
            addCriterion("legal_delegate between", value1, value2, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateNotBetween(String value1, String value2) {
            addCriterion("legal_delegate not between", value1, value2, "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberIsNull() {
            addCriterion("fax_number is null");
            return (Criteria) this;
        }

        public Criteria andFaxNumberIsNotNull() {
            addCriterion("fax_number is not null");
            return (Criteria) this;
        }

        public Criteria andFaxNumberEqualTo(String value) {
            addCriterion("fax_number =", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberNotEqualTo(String value) {
            addCriterion("fax_number <>", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberGreaterThan(String value) {
            addCriterion("fax_number >", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberGreaterThanOrEqualTo(String value) {
            addCriterion("fax_number >=", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberLessThan(String value) {
            addCriterion("fax_number <", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberLessThanOrEqualTo(String value) {
            addCriterion("fax_number <=", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberLike(String value) {
            addCriterion("fax_number like", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberNotLike(String value) {
            addCriterion("fax_number not like", value, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberIn(List<String> values) {
            addCriterion("fax_number in", values, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberNotIn(List<String> values) {
            addCriterion("fax_number not in", values, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberBetween(String value1, String value2) {
            addCriterion("fax_number between", value1, value2, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberNotBetween(String value1, String value2) {
            addCriterion("fax_number not between", value1, value2, "faxNumber");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRdlControlIsNull() {
            addCriterion("rdl_control is null");
            return (Criteria) this;
        }

        public Criteria andRdlControlIsNotNull() {
            addCriterion("rdl_control is not null");
            return (Criteria) this;
        }

        public Criteria andRdlControlEqualTo(Boolean value) {
            addCriterion("rdl_control =", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlNotEqualTo(Boolean value) {
            addCriterion("rdl_control <>", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlGreaterThan(Boolean value) {
            addCriterion("rdl_control >", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlGreaterThanOrEqualTo(Boolean value) {
            addCriterion("rdl_control >=", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlLessThan(Boolean value) {
            addCriterion("rdl_control <", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlLessThanOrEqualTo(Boolean value) {
            addCriterion("rdl_control <=", value, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlIn(List<Boolean> values) {
            addCriterion("rdl_control in", values, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlNotIn(List<Boolean> values) {
            addCriterion("rdl_control not in", values, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlBetween(Boolean value1, Boolean value2) {
            addCriterion("rdl_control between", value1, value2, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andRdlControlNotBetween(Boolean value1, Boolean value2) {
            addCriterion("rdl_control not between", value1, value2, "rdlControl");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNull() {
            addCriterion("company_type is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIsNotNull() {
            addCriterion("company_type is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualTo(String value) {
            addCriterion("company_type =", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotEqualTo(String value) {
            addCriterion("company_type <>", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThan(String value) {
            addCriterion("company_type >", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeGreaterThanOrEqualTo(String value) {
            addCriterion("company_type >=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThan(String value) {
            addCriterion("company_type <", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLessThanOrEqualTo(String value) {
            addCriterion("company_type <=", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLike(String value) {
            addCriterion("company_type like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotLike(String value) {
            addCriterion("company_type not like", value, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeIn(List<String> values) {
            addCriterion("company_type in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotIn(List<String> values) {
            addCriterion("company_type not in", values, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeBetween(String value1, String value2) {
            addCriterion("company_type between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeNotBetween(String value1, String value2) {
            addCriterion("company_type not between", value1, value2, "companyType");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Long value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Long value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Long value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Long value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Long value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Long> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Long> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Long value1, Long value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Long value1, Long value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andCciaaDateIsNull() {
            addCriterion("cciaa_date is null");
            return (Criteria) this;
        }

        public Criteria andCciaaDateIsNotNull() {
            addCriterion("cciaa_date is not null");
            return (Criteria) this;
        }

        public Criteria andCciaaDateEqualTo(Date value) {
            addCriterionForJDBCDate("cciaa_date =", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("cciaa_date <>", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateGreaterThan(Date value) {
            addCriterionForJDBCDate("cciaa_date >", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cciaa_date >=", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateLessThan(Date value) {
            addCriterionForJDBCDate("cciaa_date <", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("cciaa_date <=", value, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateIn(List<Date> values) {
            addCriterionForJDBCDate("cciaa_date in", values, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("cciaa_date not in", values, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cciaa_date between", value1, value2, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andCciaaDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("cciaa_date not between", value1, value2, "cciaaDate");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("state_id is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("state_id is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(Long value) {
            addCriterion("state_id =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(Long value) {
            addCriterion("state_id <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(Long value) {
            addCriterion("state_id >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("state_id >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(Long value) {
            addCriterion("state_id <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(Long value) {
            addCriterion("state_id <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<Long> values) {
            addCriterion("state_id in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<Long> values) {
            addCriterion("state_id not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(Long value1, Long value2) {
            addCriterion("state_id between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(Long value1, Long value2) {
            addCriterion("state_id not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andConsortiumIsNull() {
            addCriterion("consortium is null");
            return (Criteria) this;
        }

        public Criteria andConsortiumIsNotNull() {
            addCriterion("consortium is not null");
            return (Criteria) this;
        }

        public Criteria andConsortiumEqualTo(Boolean value) {
            addCriterion("consortium =", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumNotEqualTo(Boolean value) {
            addCriterion("consortium <>", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumGreaterThan(Boolean value) {
            addCriterion("consortium >", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumGreaterThanOrEqualTo(Boolean value) {
            addCriterion("consortium >=", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumLessThan(Boolean value) {
            addCriterion("consortium <", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumLessThanOrEqualTo(Boolean value) {
            addCriterion("consortium <=", value, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumIn(List<Boolean> values) {
            addCriterion("consortium in", values, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumNotIn(List<Boolean> values) {
            addCriterion("consortium not in", values, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumBetween(Boolean value1, Boolean value2) {
            addCriterion("consortium between", value1, value2, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumNotBetween(Boolean value1, Boolean value2) {
            addCriterion("consortium not between", value1, value2, "consortium");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdIsNull() {
            addCriterion("consortium_membership_id is null");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdIsNotNull() {
            addCriterion("consortium_membership_id is not null");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdEqualTo(Long value) {
            addCriterion("consortium_membership_id =", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdNotEqualTo(Long value) {
            addCriterion("consortium_membership_id <>", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdGreaterThan(Long value) {
            addCriterion("consortium_membership_id >", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdGreaterThanOrEqualTo(Long value) {
            addCriterion("consortium_membership_id >=", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdLessThan(Long value) {
            addCriterion("consortium_membership_id <", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdLessThanOrEqualTo(Long value) {
            addCriterion("consortium_membership_id <=", value, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdIn(List<Long> values) {
            addCriterion("consortium_membership_id in", values, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdNotIn(List<Long> values) {
            addCriterion("consortium_membership_id not in", values, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdBetween(Long value1, Long value2) {
            addCriterion("consortium_membership_id between", value1, value2, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andConsortiumMembershipIdNotBetween(Long value1, Long value2) {
            addCriterion("consortium_membership_id not between", value1, value2, "consortiumMembershipId");
            return (Criteria) this;
        }

        public Criteria andStockCapitalIsNull() {
            addCriterion("stock_capital is null");
            return (Criteria) this;
        }

        public Criteria andStockCapitalIsNotNull() {
            addCriterion("stock_capital is not null");
            return (Criteria) this;
        }

        public Criteria andStockCapitalEqualTo(BigDecimal value) {
            addCriterion("stock_capital =", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalNotEqualTo(BigDecimal value) {
            addCriterion("stock_capital <>", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalGreaterThan(BigDecimal value) {
            addCriterion("stock_capital >", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stock_capital >=", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalLessThan(BigDecimal value) {
            addCriterion("stock_capital <", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stock_capital <=", value, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalIn(List<BigDecimal> values) {
            addCriterion("stock_capital in", values, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalNotIn(List<BigDecimal> values) {
            addCriterion("stock_capital not in", values, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stock_capital between", value1, value2, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStockCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stock_capital not between", value1, value2, "stockCapital");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNull() {
            addCriterion("state_tag is null");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNotNull() {
            addCriterion("state_tag is not null");
            return (Criteria) this;
        }

        public Criteria andStateTagEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag =", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <>", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThan(EntityStateTag value) {
            addStateTagCriterion("state_tag >", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag >=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThan(EntityStateTag value) {
            addStateTagCriterion("state_tag <", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLike(EntityStateTag value) {
            addStateTagCriterion("state_tag like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotLike(EntityStateTag value) {
            addStateTagCriterion("state_tag not like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag not in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag not between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberIsNull() {
            addCriterion("white_list_member is null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberIsNotNull() {
            addCriterion("white_list_member is not null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberEqualTo(Boolean value) {
            addCriterion("white_list_member =", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberNotEqualTo(Boolean value) {
            addCriterion("white_list_member <>", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberGreaterThan(Boolean value) {
            addCriterion("white_list_member >", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberGreaterThanOrEqualTo(Boolean value) {
            addCriterion("white_list_member >=", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberLessThan(Boolean value) {
            addCriterion("white_list_member <", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberLessThanOrEqualTo(Boolean value) {
            addCriterion("white_list_member <=", value, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberIn(List<Boolean> values) {
            addCriterion("white_list_member in", values, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberNotIn(List<Boolean> values) {
            addCriterion("white_list_member not in", values, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberBetween(Boolean value1, Boolean value2) {
            addCriterion("white_list_member between", value1, value2, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMemberNotBetween(Boolean value1, Boolean value2) {
            addCriterion("white_list_member not between", value1, value2, "whiteListMember");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateIsNull() {
            addCriterion("white_list_membership_start_date is null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateIsNotNull() {
            addCriterion("white_list_membership_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date =", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date <>", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date >", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date >=", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateLessThan(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date <", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_start_date <=", value, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("white_list_membership_start_date in", values, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("white_list_membership_start_date not in", values, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("white_list_membership_start_date between", value1, value2, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("white_list_membership_start_date not between", value1, value2, "whiteListMembershipStartDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateIsNull() {
            addCriterion("white_list_membership_end_date is null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateIsNotNull() {
            addCriterion("white_list_membership_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date =", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date <>", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date >", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date >=", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateLessThan(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date <", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("white_list_membership_end_date <=", value, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("white_list_membership_end_date in", values, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("white_list_membership_end_date not in", values, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("white_list_membership_end_date between", value1, value2, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andWhiteListMembershipEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("white_list_membership_end_date not between", value1, value2, "whiteListMembershipEndDate");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andBusinessNameLikeInsensitive(String value) {
            addCriterion("lower(business_name) like", (value != null) ? value.toLowerCase() : value , "businessName");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberLikeInsensitive(String value) {
            addCriterion("lower(tax_identification_number) like", (value != null) ? value.toLowerCase() : value , "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberLikeInsensitive(String value) {
            addCriterion("lower(vat_number) like", (value != null) ? value.toLowerCase() : value , "vatNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeLikeInsensitive(String value) {
            addCriterion("lower(company_purpose) like", (value != null) ? value.toLowerCase() : value , "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalLikeInsensitive(String value) {
            addCriterion("lower(string_stock_capital) like", (value != null) ? value.toLowerCase() : value , "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateLikeInsensitive(String value) {
            addCriterion("lower(legal_delegate) like", (value != null) ? value.toLowerCase() : value , "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLikeInsensitive(String value) {
            addCriterion("lower(phone_number) like", (value != null) ? value.toLowerCase() : value , "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberLikeInsensitive(String value) {
            addCriterion("lower(fax_number) like", (value != null) ? value.toLowerCase() : value , "faxNumber");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("lower(email) like", (value != null) ? value.toLowerCase() : value , "email");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeLikeInsensitive(String value) {
            addCriterion("lower(company_type) like", (value != null) ? value.toLowerCase() : value , "companyType");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andBusinessNameEqualToInsensitive(String value) {
            addCriterion("lower(business_name) =", (value != null) ? value.toLowerCase() : value , "businessName");
            return (Criteria) this;
        }

        public Criteria andTaxIdentificationNumberEqualToInsensitive(String value) {
            addCriterion("lower(tax_identification_number) =", (value != null) ? value.toLowerCase() : value , "taxIdentificationNumber");
            return (Criteria) this;
        }

        public Criteria andVatNumberEqualToInsensitive(String value) {
            addCriterion("lower(vat_number) =", (value != null) ? value.toLowerCase() : value , "vatNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyPurposeEqualToInsensitive(String value) {
            addCriterion("lower(company_purpose) =", (value != null) ? value.toLowerCase() : value , "companyPurpose");
            return (Criteria) this;
        }

        public Criteria andStringStockCapitalEqualToInsensitive(String value) {
            addCriterion("lower(string_stock_capital) =", (value != null) ? value.toLowerCase() : value , "stringStockCapital");
            return (Criteria) this;
        }

        public Criteria andLegalDelegateEqualToInsensitive(String value) {
            addCriterion("lower(legal_delegate) =", (value != null) ? value.toLowerCase() : value , "legalDelegate");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualToInsensitive(String value) {
            addCriterion("lower(phone_number) =", (value != null) ? value.toLowerCase() : value , "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andFaxNumberEqualToInsensitive(String value) {
            addCriterion("lower(fax_number) =", (value != null) ? value.toLowerCase() : value , "faxNumber");
            return (Criteria) this;
        }

        public Criteria andEmailEqualToInsensitive(String value) {
            addCriterion("lower(email) =", (value != null) ? value.toLowerCase() : value , "email");
            return (Criteria) this;
        }

        public Criteria andCompanyTypeEqualToInsensitive(String value) {
            addCriterion("lower(company_type) =", (value != null) ? value.toLowerCase() : value , "companyType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 07 11:03:50 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company
     *
     * @mbggenerated Fri Oct 07 11:03:50 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}