package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class ConstructionSiteLog implements AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.log_date
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.state_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.created_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.modified_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.created_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.modified_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.construction_site_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long constructionSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.owner_node_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_log.note
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.id
     *
     * @return the value of construction_site_log.id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.id
     *
     * @param id the value for construction_site_log.id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.log_date
     *
     * @return the value of construction_site_log.log_date
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.log_date
     *
     * @param logDate the value for construction_site_log.log_date
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.state_id
     *
     * @return the value of construction_site_log.state_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.state_id
     *
     * @param stateId the value for construction_site_log.state_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.created_stamp
     *
     * @return the value of construction_site_log.created_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.created_stamp
     *
     * @param createdStamp the value for construction_site_log.created_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.modified_stamp
     *
     * @return the value of construction_site_log.modified_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.modified_stamp
     *
     * @param modifiedStamp the value for construction_site_log.modified_stamp
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.created_by_user_id
     *
     * @return the value of construction_site_log.created_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.created_by_user_id
     *
     * @param createdByUserId the value for construction_site_log.created_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.modified_by_user_id
     *
     * @return the value of construction_site_log.modified_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.modified_by_user_id
     *
     * @param modifiedByUserId the value for construction_site_log.modified_by_user_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.construction_site_id
     *
     * @return the value of construction_site_log.construction_site_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getConstructionSiteId() {
        return constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.construction_site_id
     *
     * @param constructionSiteId the value for construction_site_log.construction_site_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setConstructionSiteId(Long constructionSiteId) {
        this.constructionSiteId = constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.owner_node_id
     *
     * @return the value of construction_site_log.owner_node_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.owner_node_id
     *
     * @param ownerNodeId the value for construction_site_log.owner_node_id
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_log.note
     *
     * @return the value of construction_site_log.note
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_log.note
     *
     * @param note the value for construction_site_log.note
     *
     * @mbggenerated Mon Oct 03 15:29:18 CEST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}