package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConstructionSiteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public ConstructionSiteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIsNull() {
            addCriterion("job_order_id is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIsNotNull() {
            addCriterion("job_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdEqualTo(Long value) {
            addCriterion("job_order_id =", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotEqualTo(Long value) {
            addCriterion("job_order_id <>", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdGreaterThan(Long value) {
            addCriterion("job_order_id >", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_order_id >=", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdLessThan(Long value) {
            addCriterion("job_order_id <", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("job_order_id <=", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIn(List<Long> values) {
            addCriterion("job_order_id in", values, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotIn(List<Long> values) {
            addCriterion("job_order_id not in", values, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdBetween(Long value1, Long value2) {
            addCriterion("job_order_id between", value1, value2, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("job_order_id not between", value1, value2, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andLotIdIsNull() {
            addCriterion("lot_id is null");
            return (Criteria) this;
        }

        public Criteria andLotIdIsNotNull() {
            addCriterion("lot_id is not null");
            return (Criteria) this;
        }

        public Criteria andLotIdEqualTo(Long value) {
            addCriterion("lot_id =", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotEqualTo(Long value) {
            addCriterion("lot_id <>", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdGreaterThan(Long value) {
            addCriterion("lot_id >", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdGreaterThanOrEqualTo(Long value) {
            addCriterion("lot_id >=", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdLessThan(Long value) {
            addCriterion("lot_id <", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdLessThanOrEqualTo(Long value) {
            addCriterion("lot_id <=", value, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdIn(List<Long> values) {
            addCriterion("lot_id in", values, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotIn(List<Long> values) {
            addCriterion("lot_id not in", values, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdBetween(Long value1, Long value2) {
            addCriterion("lot_id between", value1, value2, "lotId");
            return (Criteria) this;
        }

        public Criteria andLotIdNotBetween(Long value1, Long value2) {
            addCriterion("lot_id not between", value1, value2, "lotId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdIsNull() {
            addCriterion("weekly_referent_id is null");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdIsNotNull() {
            addCriterion("weekly_referent_id is not null");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdEqualTo(Long value) {
            addCriterion("weekly_referent_id =", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdNotEqualTo(Long value) {
            addCriterion("weekly_referent_id <>", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdGreaterThan(Long value) {
            addCriterion("weekly_referent_id >", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("weekly_referent_id >=", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdLessThan(Long value) {
            addCriterion("weekly_referent_id <", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdLessThanOrEqualTo(Long value) {
            addCriterion("weekly_referent_id <=", value, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdIn(List<Long> values) {
            addCriterion("weekly_referent_id in", values, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdNotIn(List<Long> values) {
            addCriterion("weekly_referent_id not in", values, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdBetween(Long value1, Long value2) {
            addCriterion("weekly_referent_id between", value1, value2, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andWeeklyReferentIdNotBetween(Long value1, Long value2) {
            addCriterion("weekly_referent_id not between", value1, value2, "weeklyReferentId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdIsNull() {
            addCriterion("company_manager_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdIsNotNull() {
            addCriterion("company_manager_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdEqualTo(Long value) {
            addCriterion("company_manager_id =", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdNotEqualTo(Long value) {
            addCriterion("company_manager_id <>", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdGreaterThan(Long value) {
            addCriterion("company_manager_id >", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_manager_id >=", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdLessThan(Long value) {
            addCriterion("company_manager_id <", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdLessThanOrEqualTo(Long value) {
            addCriterion("company_manager_id <=", value, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdIn(List<Long> values) {
            addCriterion("company_manager_id in", values, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdNotIn(List<Long> values) {
            addCriterion("company_manager_id not in", values, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdBetween(Long value1, Long value2) {
            addCriterion("company_manager_id between", value1, value2, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCompanyManagerIdNotBetween(Long value1, Long value2) {
            addCriterion("company_manager_id not between", value1, value2, "companyManagerId");
            return (Criteria) this;
        }

        public Criteria andCseIdIsNull() {
            addCriterion("cse_id is null");
            return (Criteria) this;
        }

        public Criteria andCseIdIsNotNull() {
            addCriterion("cse_id is not null");
            return (Criteria) this;
        }

        public Criteria andCseIdEqualTo(Long value) {
            addCriterion("cse_id =", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdNotEqualTo(Long value) {
            addCriterion("cse_id <>", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdGreaterThan(Long value) {
            addCriterion("cse_id >", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("cse_id >=", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdLessThan(Long value) {
            addCriterion("cse_id <", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdLessThanOrEqualTo(Long value) {
            addCriterion("cse_id <=", value, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdIn(List<Long> values) {
            addCriterion("cse_id in", values, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdNotIn(List<Long> values) {
            addCriterion("cse_id not in", values, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdBetween(Long value1, Long value2) {
            addCriterion("cse_id between", value1, value2, "cseId");
            return (Criteria) this;
        }

        public Criteria andCseIdNotBetween(Long value1, Long value2) {
            addCriterion("cse_id not between", value1, value2, "cseId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdIsNull() {
            addCriterion("assigned_company_id is null");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdIsNotNull() {
            addCriterion("assigned_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdEqualTo(Long value) {
            addCriterion("assigned_company_id =", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdNotEqualTo(Long value) {
            addCriterion("assigned_company_id <>", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdGreaterThan(Long value) {
            addCriterion("assigned_company_id >", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("assigned_company_id >=", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdLessThan(Long value) {
            addCriterion("assigned_company_id <", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("assigned_company_id <=", value, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdIn(List<Long> values) {
            addCriterion("assigned_company_id in", values, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdNotIn(List<Long> values) {
            addCriterion("assigned_company_id not in", values, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdBetween(Long value1, Long value2) {
            addCriterion("assigned_company_id between", value1, value2, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAssignedCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("assigned_company_id not between", value1, value2, "assignedCompanyId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNull() {
            addCriterion("address_id is null");
            return (Criteria) this;
        }

        public Criteria andAddressIdIsNotNull() {
            addCriterion("address_id is not null");
            return (Criteria) this;
        }

        public Criteria andAddressIdEqualTo(Long value) {
            addCriterion("address_id =", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotEqualTo(Long value) {
            addCriterion("address_id <>", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThan(Long value) {
            addCriterion("address_id >", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdGreaterThanOrEqualTo(Long value) {
            addCriterion("address_id >=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThan(Long value) {
            addCriterion("address_id <", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdLessThanOrEqualTo(Long value) {
            addCriterion("address_id <=", value, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdIn(List<Long> values) {
            addCriterion("address_id in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotIn(List<Long> values) {
            addCriterion("address_id not in", values, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdBetween(Long value1, Long value2) {
            addCriterion("address_id between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andAddressIdNotBetween(Long value1, Long value2) {
            addCriterion("address_id not between", value1, value2, "addressId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andCupIsNull() {
            addCriterion("cup is null");
            return (Criteria) this;
        }

        public Criteria andCupIsNotNull() {
            addCriterion("cup is not null");
            return (Criteria) this;
        }

        public Criteria andCupEqualTo(String value) {
            addCriterion("cup =", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotEqualTo(String value) {
            addCriterion("cup <>", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupGreaterThan(String value) {
            addCriterion("cup >", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupGreaterThanOrEqualTo(String value) {
            addCriterion("cup >=", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLessThan(String value) {
            addCriterion("cup <", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLessThanOrEqualTo(String value) {
            addCriterion("cup <=", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupLike(String value) {
            addCriterion("cup like", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotLike(String value) {
            addCriterion("cup not like", value, "cup");
            return (Criteria) this;
        }

        public Criteria andCupIn(List<String> values) {
            addCriterion("cup in", values, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotIn(List<String> values) {
            addCriterion("cup not in", values, "cup");
            return (Criteria) this;
        }

        public Criteria andCupBetween(String value1, String value2) {
            addCriterion("cup between", value1, value2, "cup");
            return (Criteria) this;
        }

        public Criteria andCupNotBetween(String value1, String value2) {
            addCriterion("cup not between", value1, value2, "cup");
            return (Criteria) this;
        }

        public Criteria andCigIsNull() {
            addCriterion("cig is null");
            return (Criteria) this;
        }

        public Criteria andCigIsNotNull() {
            addCriterion("cig is not null");
            return (Criteria) this;
        }

        public Criteria andCigEqualTo(String value) {
            addCriterion("cig =", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotEqualTo(String value) {
            addCriterion("cig <>", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigGreaterThan(String value) {
            addCriterion("cig >", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigGreaterThanOrEqualTo(String value) {
            addCriterion("cig >=", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLessThan(String value) {
            addCriterion("cig <", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLessThanOrEqualTo(String value) {
            addCriterion("cig <=", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLike(String value) {
            addCriterion("cig like", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotLike(String value) {
            addCriterion("cig not like", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigIn(List<String> values) {
            addCriterion("cig in", values, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotIn(List<String> values) {
            addCriterion("cig not in", values, "cig");
            return (Criteria) this;
        }

        public Criteria andCigBetween(String value1, String value2) {
            addCriterion("cig between", value1, value2, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotBetween(String value1, String value2) {
            addCriterion("cig not between", value1, value2, "cig");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdIsNull() {
            addCriterion("works_company_id is null");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdIsNotNull() {
            addCriterion("works_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdEqualTo(Long value) {
            addCriterion("works_company_id =", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdNotEqualTo(Long value) {
            addCriterion("works_company_id <>", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdGreaterThan(Long value) {
            addCriterion("works_company_id >", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("works_company_id >=", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdLessThan(Long value) {
            addCriterion("works_company_id <", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("works_company_id <=", value, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdIn(List<Long> values) {
            addCriterion("works_company_id in", values, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdNotIn(List<Long> values) {
            addCriterion("works_company_id not in", values, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdBetween(Long value1, Long value2) {
            addCriterion("works_company_id between", value1, value2, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andWorksCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("works_company_id not between", value1, value2, "worksCompanyId");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("lower(code) like", (value != null) ? value.toLowerCase() : value , "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andNoteLikeInsensitive(String value) {
            addCriterion("lower(note) like", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }

        public Criteria andCupLikeInsensitive(String value) {
            addCriterion("lower(cup) like", (value != null) ? value.toLowerCase() : value , "cup");
            return (Criteria) this;
        }

        public Criteria andCigLikeInsensitive(String value) {
            addCriterion("lower(cig) like", (value != null) ? value.toLowerCase() : value , "cig");
            return (Criteria) this;
        }

        public Criteria andCodeEqualToInsensitive(String value) {
            addCriterion("lower(code) =", (value != null) ? value.toLowerCase() : value , "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andNoteEqualToInsensitive(String value) {
            addCriterion("lower(note) =", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }

        public Criteria andCupEqualToInsensitive(String value) {
            addCriterion("lower(cup) =", (value != null) ? value.toLowerCase() : value , "cup");
            return (Criteria) this;
        }

        public Criteria andCigEqualToInsensitive(String value) {
            addCriterion("lower(cig) =", (value != null) ? value.toLowerCase() : value , "cig");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table construction_site
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 01 14:44:44 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}