package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class ConstructionSiteLocation extends ConstructionSiteLocationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_location.created_stamp
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_site_location.created_by_user_id
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_location.created_stamp
     *
     * @return the value of construction_site_location.created_stamp
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_location.created_stamp
     *
     * @param createdStamp the value for construction_site_location.created_stamp
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_site_location.created_by_user_id
     *
     * @return the value of construction_site_location.created_by_user_id
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_site_location.created_by_user_id
     *
     * @param createdByUserId the value for construction_site_location.created_by_user_id
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }
}