package it.memelabs.smartnebula.lmm.persistence.main.dto;

public class EmploymentToExportKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_to_export.employment_external_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    private String employmentExternalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employment_to_export.session_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    private Long sessionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_to_export.employment_external_id
     *
     * @return the value of employment_to_export.employment_external_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public String getEmploymentExternalId() {
        return employmentExternalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_to_export.employment_external_id
     *
     * @param employmentExternalId the value for employment_to_export.employment_external_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void setEmploymentExternalId(String employmentExternalId) {
        this.employmentExternalId = employmentExternalId == null ? null : employmentExternalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employment_to_export.session_id
     *
     * @return the value of employment_to_export.session_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public Long getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employment_to_export.session_id
     *
     * @param sessionId the value for employment_to_export.session_id
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void setSessionId(Long sessionId) {
        this.sessionId = sessionId;
    }
}