package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import java.util.Date;

public class EntityState implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.description
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.modified_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.created_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.created_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.modified_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.owner_node_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.parent_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.ordinal
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Integer ordinal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.name
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.entity
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private String entity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.tag
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private EntityStateTag tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entity_state.valid_until
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    private Date validUntil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.id
     *
     * @return the value of entity_state.id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.id
     *
     * @param id the value for entity_state.id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.description
     *
     * @return the value of entity_state.description
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.description
     *
     * @param description the value for entity_state.description
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.modified_stamp
     *
     * @return the value of entity_state.modified_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.modified_stamp
     *
     * @param modifiedStamp the value for entity_state.modified_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.created_stamp
     *
     * @return the value of entity_state.created_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.created_stamp
     *
     * @param createdStamp the value for entity_state.created_stamp
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.created_by_user_id
     *
     * @return the value of entity_state.created_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.created_by_user_id
     *
     * @param createdByUserId the value for entity_state.created_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.modified_by_user_id
     *
     * @return the value of entity_state.modified_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.modified_by_user_id
     *
     * @param modifiedByUserId the value for entity_state.modified_by_user_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.owner_node_id
     *
     * @return the value of entity_state.owner_node_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.owner_node_id
     *
     * @param ownerNodeId the value for entity_state.owner_node_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.parent_id
     *
     * @return the value of entity_state.parent_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.parent_id
     *
     * @param parentId the value for entity_state.parent_id
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.ordinal
     *
     * @return the value of entity_state.ordinal
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Integer getOrdinal() {
        return ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.ordinal
     *
     * @param ordinal the value for entity_state.ordinal
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.name
     *
     * @return the value of entity_state.name
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.name
     *
     * @param name the value for entity_state.name
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.entity
     *
     * @return the value of entity_state.entity
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public String getEntity() {
        return entity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.entity
     *
     * @param entity the value for entity_state.entity
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setEntity(String entity) {
        this.entity = entity == null ? null : entity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.tag
     *
     * @return the value of entity_state.tag
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public EntityStateTag getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.tag
     *
     * @param tag the value for entity_state.tag
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setTag(EntityStateTag tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entity_state.valid_until
     *
     * @return the value of entity_state.valid_until
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public Date getValidUntil() {
        return validUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entity_state.valid_until
     *
     * @param validUntil the value for entity_state.valid_until
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    public void setValidUntil(Date validUntil) {
        this.validUntil = validUntil;
    }
}