package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStatus;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.AttachmentStorage;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GalleryImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public GalleryImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> storageTypeCriteria;

        protected List<Criterion> thumbnailStorageTypeCriteria;

        protected List<Criterion> webStorageTypeCriteria;

        protected List<Criterion> statusCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            storageTypeCriteria = new ArrayList<Criterion>();
            thumbnailStorageTypeCriteria = new ArrayList<Criterion>();
            webStorageTypeCriteria = new ArrayList<Criterion>();
            statusCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStorageTypeCriteria() {
            return storageTypeCriteria;
        }

        protected void addStorageTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            storageTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStorageTypeCriterion(String condition, AttachmentStorage value1, AttachmentStorage value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            storageTypeCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getThumbnailStorageTypeCriteria() {
            return thumbnailStorageTypeCriteria;
        }

        protected void addThumbnailStorageTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            thumbnailStorageTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addThumbnailStorageTypeCriterion(String condition, AttachmentStorage value1, AttachmentStorage value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            thumbnailStorageTypeCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getWebStorageTypeCriteria() {
            return webStorageTypeCriteria;
        }

        protected void addWebStorageTypeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            webStorageTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addWebStorageTypeCriterion(String condition, AttachmentStorage value1, AttachmentStorage value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            webStorageTypeCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getStatusCriteria() {
            return statusCriteria;
        }

        protected void addStatusCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStatusCriterion(String condition, AttachmentStatus value1, AttachmentStatus value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            statusCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || storageTypeCriteria.size() > 0
                || thumbnailStorageTypeCriteria.size() > 0
                || webStorageTypeCriteria.size() > 0
                || statusCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(storageTypeCriteria);
                allCriteria.addAll(thumbnailStorageTypeCriteria);
                allCriteria.addAll(webStorageTypeCriteria);
                allCriteria.addAll(statusCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIsNull() {
            addCriterion("uploaded_stamp is null");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIsNotNull() {
            addCriterion("uploaded_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andUploadedStampEqualTo(Date value) {
            addCriterion("uploaded_stamp =", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotEqualTo(Date value) {
            addCriterion("uploaded_stamp <>", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampGreaterThan(Date value) {
            addCriterion("uploaded_stamp >", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("uploaded_stamp >=", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampLessThan(Date value) {
            addCriterion("uploaded_stamp <", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampLessThanOrEqualTo(Date value) {
            addCriterion("uploaded_stamp <=", value, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampIn(List<Date> values) {
            addCriterion("uploaded_stamp in", values, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotIn(List<Date> values) {
            addCriterion("uploaded_stamp not in", values, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampBetween(Date value1, Date value2) {
            addCriterion("uploaded_stamp between", value1, value2, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andUploadedStampNotBetween(Date value1, Date value2) {
            addCriterion("uploaded_stamp not between", value1, value2, "uploadedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIsNull() {
            addCriterion("uploaded_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIsNotNull() {
            addCriterion("uploaded_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdEqualTo(Long value) {
            addCriterion("uploaded_by_user_id =", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotEqualTo(Long value) {
            addCriterion("uploaded_by_user_id <>", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdGreaterThan(Long value) {
            addCriterion("uploaded_by_user_id >", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("uploaded_by_user_id >=", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdLessThan(Long value) {
            addCriterion("uploaded_by_user_id <", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("uploaded_by_user_id <=", value, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdIn(List<Long> values) {
            addCriterion("uploaded_by_user_id in", values, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotIn(List<Long> values) {
            addCriterion("uploaded_by_user_id not in", values, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdBetween(Long value1, Long value2) {
            addCriterion("uploaded_by_user_id between", value1, value2, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andUploadedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("uploaded_by_user_id not between", value1, value2, "uploadedByUserId");
            return (Criteria) this;
        }

        public Criteria andEntityIsNull() {
            addCriterion("entity is null");
            return (Criteria) this;
        }

        public Criteria andEntityIsNotNull() {
            addCriterion("entity is not null");
            return (Criteria) this;
        }

        public Criteria andEntityEqualTo(String value) {
            addCriterion("entity =", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotEqualTo(String value) {
            addCriterion("entity <>", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityGreaterThan(String value) {
            addCriterion("entity >", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityGreaterThanOrEqualTo(String value) {
            addCriterion("entity >=", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLessThan(String value) {
            addCriterion("entity <", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLessThanOrEqualTo(String value) {
            addCriterion("entity <=", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityLike(String value) {
            addCriterion("entity like", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotLike(String value) {
            addCriterion("entity not like", value, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityIn(List<String> values) {
            addCriterion("entity in", values, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotIn(List<String> values) {
            addCriterion("entity not in", values, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityBetween(String value1, String value2) {
            addCriterion("entity between", value1, value2, "entity");
            return (Criteria) this;
        }

        public Criteria andEntityNotBetween(String value1, String value2) {
            addCriterion("entity not between", value1, value2, "entity");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNull() {
            addCriterion("mime_type is null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIsNotNull() {
            addCriterion("mime_type is not null");
            return (Criteria) this;
        }

        public Criteria andMimeTypeEqualTo(String value) {
            addCriterion("mime_type =", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotEqualTo(String value) {
            addCriterion("mime_type <>", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThan(String value) {
            addCriterion("mime_type >", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("mime_type >=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThan(String value) {
            addCriterion("mime_type <", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLessThanOrEqualTo(String value) {
            addCriterion("mime_type <=", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLike(String value) {
            addCriterion("mime_type like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotLike(String value) {
            addCriterion("mime_type not like", value, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeIn(List<String> values) {
            addCriterion("mime_type in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotIn(List<String> values) {
            addCriterion("mime_type not in", values, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeBetween(String value1, String value2) {
            addCriterion("mime_type between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andMimeTypeNotBetween(String value1, String value2) {
            addCriterion("mime_type not between", value1, value2, "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNull() {
            addCriterion("bucket_name is null");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNotNull() {
            addCriterion("bucket_name is not null");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualTo(String value) {
            addCriterion("bucket_name =", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotEqualTo(String value) {
            addCriterion("bucket_name <>", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThan(String value) {
            addCriterion("bucket_name >", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThanOrEqualTo(String value) {
            addCriterion("bucket_name >=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThan(String value) {
            addCriterion("bucket_name <", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThanOrEqualTo(String value) {
            addCriterion("bucket_name <=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLike(String value) {
            addCriterion("bucket_name like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotLike(String value) {
            addCriterion("bucket_name not like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameIn(List<String> values) {
            addCriterion("bucket_name in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotIn(List<String> values) {
            addCriterion("bucket_name not in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameBetween(String value1, String value2) {
            addCriterion("bucket_name between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotBetween(String value1, String value2) {
            addCriterion("bucket_name not between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIsNull() {
            addCriterion("storage_type is null");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIsNotNull() {
            addCriterion("storage_type is not null");
            return (Criteria) this;
        }

        public Criteria andStorageTypeEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type =", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <>", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeGreaterThan(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type >", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeGreaterThanOrEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type >=", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLessThan(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLessThanOrEqualTo(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type <=", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeLike(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type like", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotLike(AttachmentStorage value) {
            addStorageTypeCriterion("storage_type not like", value, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeIn(List<AttachmentStorage> values) {
            addStorageTypeCriterion("storage_type in", values, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotIn(List<AttachmentStorage> values) {
            addStorageTypeCriterion("storage_type not in", values, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addStorageTypeCriterion("storage_type between", value1, value2, "storageType");
            return (Criteria) this;
        }

        public Criteria andStorageTypeNotBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addStorageTypeCriterion("storage_type not between", value1, value2, "storageType");
            return (Criteria) this;
        }

        public Criteria andStoragePathIsNull() {
            addCriterion("storage_path is null");
            return (Criteria) this;
        }

        public Criteria andStoragePathIsNotNull() {
            addCriterion("storage_path is not null");
            return (Criteria) this;
        }

        public Criteria andStoragePathEqualTo(String value) {
            addCriterion("storage_path =", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotEqualTo(String value) {
            addCriterion("storage_path <>", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathGreaterThan(String value) {
            addCriterion("storage_path >", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathGreaterThanOrEqualTo(String value) {
            addCriterion("storage_path >=", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLessThan(String value) {
            addCriterion("storage_path <", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLessThanOrEqualTo(String value) {
            addCriterion("storage_path <=", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathLike(String value) {
            addCriterion("storage_path like", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotLike(String value) {
            addCriterion("storage_path not like", value, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathIn(List<String> values) {
            addCriterion("storage_path in", values, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotIn(List<String> values) {
            addCriterion("storage_path not in", values, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathBetween(String value1, String value2) {
            addCriterion("storage_path between", value1, value2, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStoragePathNotBetween(String value1, String value2) {
            addCriterion("storage_path not between", value1, value2, "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileIsNull() {
            addCriterion("storage_file is null");
            return (Criteria) this;
        }

        public Criteria andStorageFileIsNotNull() {
            addCriterion("storage_file is not null");
            return (Criteria) this;
        }

        public Criteria andStorageFileEqualTo(String value) {
            addCriterion("storage_file =", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotEqualTo(String value) {
            addCriterion("storage_file <>", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileGreaterThan(String value) {
            addCriterion("storage_file >", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileGreaterThanOrEqualTo(String value) {
            addCriterion("storage_file >=", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLessThan(String value) {
            addCriterion("storage_file <", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLessThanOrEqualTo(String value) {
            addCriterion("storage_file <=", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileLike(String value) {
            addCriterion("storage_file like", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotLike(String value) {
            addCriterion("storage_file not like", value, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileIn(List<String> values) {
            addCriterion("storage_file in", values, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotIn(List<String> values) {
            addCriterion("storage_file not in", values, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileBetween(String value1, String value2) {
            addCriterion("storage_file between", value1, value2, "storageFile");
            return (Criteria) this;
        }

        public Criteria andStorageFileNotBetween(String value1, String value2) {
            addCriterion("storage_file not between", value1, value2, "storageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeIsNull() {
            addCriterion("thumbnail_storage_type is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeIsNotNull() {
            addCriterion("thumbnail_storage_type is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeEqualTo(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type =", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeNotEqualTo(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type <>", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeGreaterThan(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type >", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeGreaterThanOrEqualTo(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type >=", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeLessThan(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type <", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeLessThanOrEqualTo(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type <=", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeLike(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type like", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeNotLike(AttachmentStorage value) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type not like", value, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeIn(List<AttachmentStorage> values) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type in", values, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeNotIn(List<AttachmentStorage> values) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type not in", values, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type between", value1, value2, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageTypeNotBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addThumbnailStorageTypeCriterion("thumbnail_storage_type not between", value1, value2, "thumbnailStorageType");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileIsNull() {
            addCriterion("thumbnail_storage_file is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileIsNotNull() {
            addCriterion("thumbnail_storage_file is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileEqualTo(String value) {
            addCriterion("thumbnail_storage_file =", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileNotEqualTo(String value) {
            addCriterion("thumbnail_storage_file <>", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileGreaterThan(String value) {
            addCriterion("thumbnail_storage_file >", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail_storage_file >=", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileLessThan(String value) {
            addCriterion("thumbnail_storage_file <", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileLessThanOrEqualTo(String value) {
            addCriterion("thumbnail_storage_file <=", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileLike(String value) {
            addCriterion("thumbnail_storage_file like", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileNotLike(String value) {
            addCriterion("thumbnail_storage_file not like", value, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileIn(List<String> values) {
            addCriterion("thumbnail_storage_file in", values, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileNotIn(List<String> values) {
            addCriterion("thumbnail_storage_file not in", values, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileBetween(String value1, String value2) {
            addCriterion("thumbnail_storage_file between", value1, value2, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileNotBetween(String value1, String value2) {
            addCriterion("thumbnail_storage_file not between", value1, value2, "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathIsNull() {
            addCriterion("thumbnail_storage_path is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathIsNotNull() {
            addCriterion("thumbnail_storage_path is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathEqualTo(String value) {
            addCriterion("thumbnail_storage_path =", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathNotEqualTo(String value) {
            addCriterion("thumbnail_storage_path <>", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathGreaterThan(String value) {
            addCriterion("thumbnail_storage_path >", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathGreaterThanOrEqualTo(String value) {
            addCriterion("thumbnail_storage_path >=", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathLessThan(String value) {
            addCriterion("thumbnail_storage_path <", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathLessThanOrEqualTo(String value) {
            addCriterion("thumbnail_storage_path <=", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathLike(String value) {
            addCriterion("thumbnail_storage_path like", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathNotLike(String value) {
            addCriterion("thumbnail_storage_path not like", value, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathIn(List<String> values) {
            addCriterion("thumbnail_storage_path in", values, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathNotIn(List<String> values) {
            addCriterion("thumbnail_storage_path not in", values, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathBetween(String value1, String value2) {
            addCriterion("thumbnail_storage_path between", value1, value2, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathNotBetween(String value1, String value2) {
            addCriterion("thumbnail_storage_path not between", value1, value2, "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeIsNull() {
            addCriterion("web_storage_type is null");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeIsNotNull() {
            addCriterion("web_storage_type is not null");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeEqualTo(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type =", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeNotEqualTo(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type <>", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeGreaterThan(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type >", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeGreaterThanOrEqualTo(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type >=", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeLessThan(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type <", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeLessThanOrEqualTo(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type <=", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeLike(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type like", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeNotLike(AttachmentStorage value) {
            addWebStorageTypeCriterion("web_storage_type not like", value, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeIn(List<AttachmentStorage> values) {
            addWebStorageTypeCriterion("web_storage_type in", values, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeNotIn(List<AttachmentStorage> values) {
            addWebStorageTypeCriterion("web_storage_type not in", values, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addWebStorageTypeCriterion("web_storage_type between", value1, value2, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageTypeNotBetween(AttachmentStorage value1, AttachmentStorage value2) {
            addWebStorageTypeCriterion("web_storage_type not between", value1, value2, "webStorageType");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileIsNull() {
            addCriterion("web_storage_file is null");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileIsNotNull() {
            addCriterion("web_storage_file is not null");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileEqualTo(String value) {
            addCriterion("web_storage_file =", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileNotEqualTo(String value) {
            addCriterion("web_storage_file <>", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileGreaterThan(String value) {
            addCriterion("web_storage_file >", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileGreaterThanOrEqualTo(String value) {
            addCriterion("web_storage_file >=", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileLessThan(String value) {
            addCriterion("web_storage_file <", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileLessThanOrEqualTo(String value) {
            addCriterion("web_storage_file <=", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileLike(String value) {
            addCriterion("web_storage_file like", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileNotLike(String value) {
            addCriterion("web_storage_file not like", value, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileIn(List<String> values) {
            addCriterion("web_storage_file in", values, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileNotIn(List<String> values) {
            addCriterion("web_storage_file not in", values, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileBetween(String value1, String value2) {
            addCriterion("web_storage_file between", value1, value2, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileNotBetween(String value1, String value2) {
            addCriterion("web_storage_file not between", value1, value2, "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathIsNull() {
            addCriterion("web_storage_path is null");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathIsNotNull() {
            addCriterion("web_storage_path is not null");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathEqualTo(String value) {
            addCriterion("web_storage_path =", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathNotEqualTo(String value) {
            addCriterion("web_storage_path <>", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathGreaterThan(String value) {
            addCriterion("web_storage_path >", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathGreaterThanOrEqualTo(String value) {
            addCriterion("web_storage_path >=", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathLessThan(String value) {
            addCriterion("web_storage_path <", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathLessThanOrEqualTo(String value) {
            addCriterion("web_storage_path <=", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathLike(String value) {
            addCriterion("web_storage_path like", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathNotLike(String value) {
            addCriterion("web_storage_path not like", value, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathIn(List<String> values) {
            addCriterion("web_storage_path in", values, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathNotIn(List<String> values) {
            addCriterion("web_storage_path not in", values, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathBetween(String value1, String value2) {
            addCriterion("web_storage_path between", value1, value2, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathNotBetween(String value1, String value2) {
            addCriterion("web_storage_path not between", value1, value2, "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andSha1IsNull() {
            addCriterion("sha1 is null");
            return (Criteria) this;
        }

        public Criteria andSha1IsNotNull() {
            addCriterion("sha1 is not null");
            return (Criteria) this;
        }

        public Criteria andSha1EqualTo(String value) {
            addCriterion("sha1 =", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotEqualTo(String value) {
            addCriterion("sha1 <>", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1GreaterThan(String value) {
            addCriterion("sha1 >", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1GreaterThanOrEqualTo(String value) {
            addCriterion("sha1 >=", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1LessThan(String value) {
            addCriterion("sha1 <", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1LessThanOrEqualTo(String value) {
            addCriterion("sha1 <=", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1Like(String value) {
            addCriterion("sha1 like", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotLike(String value) {
            addCriterion("sha1 not like", value, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1In(List<String> values) {
            addCriterion("sha1 in", values, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotIn(List<String> values) {
            addCriterion("sha1 not in", values, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1Between(String value1, String value2) {
            addCriterion("sha1 between", value1, value2, "sha1");
            return (Criteria) this;
        }

        public Criteria andSha1NotBetween(String value1, String value2) {
            addCriterion("sha1 not between", value1, value2, "sha1");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("size is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("size is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Long value) {
            addCriterion("size =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Long value) {
            addCriterion("size <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Long value) {
            addCriterion("size >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("size >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Long value) {
            addCriterion("size <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Long value) {
            addCriterion("size <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Long> values) {
            addCriterion("size in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Long> values) {
            addCriterion("size not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Long value1, Long value2) {
            addCriterion("size between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Long value1, Long value2) {
            addCriterion("size not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andValidSinceIsNull() {
            addCriterion("valid_since is null");
            return (Criteria) this;
        }

        public Criteria andValidSinceIsNotNull() {
            addCriterion("valid_since is not null");
            return (Criteria) this;
        }

        public Criteria andValidSinceEqualTo(Date value) {
            addCriterion("valid_since =", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotEqualTo(Date value) {
            addCriterion("valid_since <>", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceGreaterThan(Date value) {
            addCriterion("valid_since >", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceGreaterThanOrEqualTo(Date value) {
            addCriterion("valid_since >=", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceLessThan(Date value) {
            addCriterion("valid_since <", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceLessThanOrEqualTo(Date value) {
            addCriterion("valid_since <=", value, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceIn(List<Date> values) {
            addCriterion("valid_since in", values, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotIn(List<Date> values) {
            addCriterion("valid_since not in", values, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceBetween(Date value1, Date value2) {
            addCriterion("valid_since between", value1, value2, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidSinceNotBetween(Date value1, Date value2) {
            addCriterion("valid_since not between", value1, value2, "validSince");
            return (Criteria) this;
        }

        public Criteria andValidUntilIsNull() {
            addCriterion("valid_until is null");
            return (Criteria) this;
        }

        public Criteria andValidUntilIsNotNull() {
            addCriterion("valid_until is not null");
            return (Criteria) this;
        }

        public Criteria andValidUntilEqualTo(Date value) {
            addCriterion("valid_until =", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotEqualTo(Date value) {
            addCriterion("valid_until <>", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilGreaterThan(Date value) {
            addCriterion("valid_until >", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilGreaterThanOrEqualTo(Date value) {
            addCriterion("valid_until >=", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilLessThan(Date value) {
            addCriterion("valid_until <", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilLessThanOrEqualTo(Date value) {
            addCriterion("valid_until <=", value, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilIn(List<Date> values) {
            addCriterion("valid_until in", values, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotIn(List<Date> values) {
            addCriterion("valid_until not in", values, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilBetween(Date value1, Date value2) {
            addCriterion("valid_until between", value1, value2, "validUntil");
            return (Criteria) this;
        }

        public Criteria andValidUntilNotBetween(Date value1, Date value2) {
            addCriterion("valid_until not between", value1, value2, "validUntil");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(AttachmentStatus value) {
            addStatusCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(AttachmentStatus value) {
            addStatusCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(AttachmentStatus value) {
            addStatusCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(AttachmentStatus value) {
            addStatusCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(AttachmentStatus value) {
            addStatusCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(AttachmentStatus value) {
            addStatusCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(AttachmentStatus value) {
            addStatusCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(AttachmentStatus value) {
            addStatusCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<AttachmentStatus> values) {
            addStatusCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<AttachmentStatus> values) {
            addStatusCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(AttachmentStatus value1, AttachmentStatus value2) {
            addStatusCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(AttachmentStatus value1, AttachmentStatus value2) {
            addStatusCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdIsNull() {
            addCriterion("construction_site_id is null");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdIsNotNull() {
            addCriterion("construction_site_id is not null");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdEqualTo(Long value) {
            addCriterion("construction_site_id =", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdNotEqualTo(Long value) {
            addCriterion("construction_site_id <>", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdGreaterThan(Long value) {
            addCriterion("construction_site_id >", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdGreaterThanOrEqualTo(Long value) {
            addCriterion("construction_site_id >=", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdLessThan(Long value) {
            addCriterion("construction_site_id <", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdLessThanOrEqualTo(Long value) {
            addCriterion("construction_site_id <=", value, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdIn(List<Long> values) {
            addCriterion("construction_site_id in", values, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdNotIn(List<Long> values) {
            addCriterion("construction_site_id not in", values, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdBetween(Long value1, Long value2) {
            addCriterion("construction_site_id between", value1, value2, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andConstructionSiteIdNotBetween(Long value1, Long value2) {
            addCriterion("construction_site_id not between", value1, value2, "constructionSiteId");
            return (Criteria) this;
        }

        public Criteria andWbsIdIsNull() {
            addCriterion("wbs_id is null");
            return (Criteria) this;
        }

        public Criteria andWbsIdIsNotNull() {
            addCriterion("wbs_id is not null");
            return (Criteria) this;
        }

        public Criteria andWbsIdEqualTo(Long value) {
            addCriterion("wbs_id =", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotEqualTo(Long value) {
            addCriterion("wbs_id <>", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdGreaterThan(Long value) {
            addCriterion("wbs_id >", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("wbs_id >=", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdLessThan(Long value) {
            addCriterion("wbs_id <", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdLessThanOrEqualTo(Long value) {
            addCriterion("wbs_id <=", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdIn(List<Long> values) {
            addCriterion("wbs_id in", values, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotIn(List<Long> values) {
            addCriterion("wbs_id not in", values, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdBetween(Long value1, Long value2) {
            addCriterion("wbs_id between", value1, value2, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotBetween(Long value1, Long value2) {
            addCriterion("wbs_id not between", value1, value2, "wbsId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andEntityLikeInsensitive(String value) {
            addCriterion("lower(entity) like", (value != null) ? value.toLowerCase() : value , "entity");
            return (Criteria) this;
        }

        public Criteria andFilenameLikeInsensitive(String value) {
            addCriterion("lower(filename) like", (value != null) ? value.toLowerCase() : value , "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeLikeInsensitive(String value) {
            addCriterion("lower(mime_type) like", (value != null) ? value.toLowerCase() : value , "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameLikeInsensitive(String value) {
            addCriterion("lower(bucket_name) like", (value != null) ? value.toLowerCase() : value , "bucketName");
            return (Criteria) this;
        }

        public Criteria andStoragePathLikeInsensitive(String value) {
            addCriterion("lower(storage_path) like", (value != null) ? value.toLowerCase() : value , "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileLikeInsensitive(String value) {
            addCriterion("lower(storage_file) like", (value != null) ? value.toLowerCase() : value , "storageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileLikeInsensitive(String value) {
            addCriterion("lower(thumbnail_storage_file) like", (value != null) ? value.toLowerCase() : value , "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathLikeInsensitive(String value) {
            addCriterion("lower(thumbnail_storage_path) like", (value != null) ? value.toLowerCase() : value , "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileLikeInsensitive(String value) {
            addCriterion("lower(web_storage_file) like", (value != null) ? value.toLowerCase() : value , "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathLikeInsensitive(String value) {
            addCriterion("lower(web_storage_path) like", (value != null) ? value.toLowerCase() : value , "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andSha1LikeInsensitive(String value) {
            addCriterion("lower(sha1) like", (value != null) ? value.toLowerCase() : value , "sha1");
            return (Criteria) this;
        }

        public Criteria andNoteLikeInsensitive(String value) {
            addCriterion("lower(note) like", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andEntityEqualToInsensitive(String value) {
            addCriterion("lower(entity) =", (value != null) ? value.toLowerCase() : value , "entity");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualToInsensitive(String value) {
            addCriterion("lower(filename) =", (value != null) ? value.toLowerCase() : value , "filename");
            return (Criteria) this;
        }

        public Criteria andMimeTypeEqualToInsensitive(String value) {
            addCriterion("lower(mime_type) =", (value != null) ? value.toLowerCase() : value , "mimeType");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualToInsensitive(String value) {
            addCriterion("lower(bucket_name) =", (value != null) ? value.toLowerCase() : value , "bucketName");
            return (Criteria) this;
        }

        public Criteria andStoragePathEqualToInsensitive(String value) {
            addCriterion("lower(storage_path) =", (value != null) ? value.toLowerCase() : value , "storagePath");
            return (Criteria) this;
        }

        public Criteria andStorageFileEqualToInsensitive(String value) {
            addCriterion("lower(storage_file) =", (value != null) ? value.toLowerCase() : value , "storageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStorageFileEqualToInsensitive(String value) {
            addCriterion("lower(thumbnail_storage_file) =", (value != null) ? value.toLowerCase() : value , "thumbnailStorageFile");
            return (Criteria) this;
        }

        public Criteria andThumbnailStoragePathEqualToInsensitive(String value) {
            addCriterion("lower(thumbnail_storage_path) =", (value != null) ? value.toLowerCase() : value , "thumbnailStoragePath");
            return (Criteria) this;
        }

        public Criteria andWebStorageFileEqualToInsensitive(String value) {
            addCriterion("lower(web_storage_file) =", (value != null) ? value.toLowerCase() : value , "webStorageFile");
            return (Criteria) this;
        }

        public Criteria andWebStoragePathEqualToInsensitive(String value) {
            addCriterion("lower(web_storage_path) =", (value != null) ? value.toLowerCase() : value , "webStoragePath");
            return (Criteria) this;
        }

        public Criteria andSha1EqualToInsensitive(String value) {
            addCriterion("lower(sha1) =", (value != null) ? value.toLowerCase() : value , "sha1");
            return (Criteria) this;
        }

        public Criteria andNoteEqualToInsensitive(String value) {
            addCriterion("lower(note) =", (value != null) ? value.toLowerCase() : value , "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gallery_image
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 07 11:48:52 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gallery_image
     *
     * @mbggenerated Mon Nov 07 11:48:52 CET 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}