package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.ArrayList;
import java.util.List;

public class GeoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public GeoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGeoIdIsNull() {
            addCriterion("geo_id is null");
            return (Criteria) this;
        }

        public Criteria andGeoIdIsNotNull() {
            addCriterion("geo_id is not null");
            return (Criteria) this;
        }

        public Criteria andGeoIdEqualTo(String value) {
            addCriterion("geo_id =", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdNotEqualTo(String value) {
            addCriterion("geo_id <>", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdGreaterThan(String value) {
            addCriterion("geo_id >", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdGreaterThanOrEqualTo(String value) {
            addCriterion("geo_id >=", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdLessThan(String value) {
            addCriterion("geo_id <", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdLessThanOrEqualTo(String value) {
            addCriterion("geo_id <=", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdLike(String value) {
            addCriterion("geo_id like", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdNotLike(String value) {
            addCriterion("geo_id not like", value, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdIn(List<String> values) {
            addCriterion("geo_id in", values, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdNotIn(List<String> values) {
            addCriterion("geo_id not in", values, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdBetween(String value1, String value2) {
            addCriterion("geo_id between", value1, value2, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoIdNotBetween(String value1, String value2) {
            addCriterion("geo_id not between", value1, value2, "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdIsNull() {
            addCriterion("geo_type_id is null");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdIsNotNull() {
            addCriterion("geo_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdEqualTo(String value) {
            addCriterion("geo_type_id =", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdNotEqualTo(String value) {
            addCriterion("geo_type_id <>", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdGreaterThan(String value) {
            addCriterion("geo_type_id >", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("geo_type_id >=", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdLessThan(String value) {
            addCriterion("geo_type_id <", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdLessThanOrEqualTo(String value) {
            addCriterion("geo_type_id <=", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdLike(String value) {
            addCriterion("geo_type_id like", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdNotLike(String value) {
            addCriterion("geo_type_id not like", value, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdIn(List<String> values) {
            addCriterion("geo_type_id in", values, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdNotIn(List<String> values) {
            addCriterion("geo_type_id not in", values, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdBetween(String value1, String value2) {
            addCriterion("geo_type_id between", value1, value2, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdNotBetween(String value1, String value2) {
            addCriterion("geo_type_id not between", value1, value2, "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoNameIsNull() {
            addCriterion("geo_name is null");
            return (Criteria) this;
        }

        public Criteria andGeoNameIsNotNull() {
            addCriterion("geo_name is not null");
            return (Criteria) this;
        }

        public Criteria andGeoNameEqualTo(String value) {
            addCriterion("geo_name =", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameNotEqualTo(String value) {
            addCriterion("geo_name <>", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameGreaterThan(String value) {
            addCriterion("geo_name >", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameGreaterThanOrEqualTo(String value) {
            addCriterion("geo_name >=", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameLessThan(String value) {
            addCriterion("geo_name <", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameLessThanOrEqualTo(String value) {
            addCriterion("geo_name <=", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameLike(String value) {
            addCriterion("geo_name like", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameNotLike(String value) {
            addCriterion("geo_name not like", value, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameIn(List<String> values) {
            addCriterion("geo_name in", values, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameNotIn(List<String> values) {
            addCriterion("geo_name not in", values, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameBetween(String value1, String value2) {
            addCriterion("geo_name between", value1, value2, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoNameNotBetween(String value1, String value2) {
            addCriterion("geo_name not between", value1, value2, "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIsNull() {
            addCriterion("geo_code is null");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIsNotNull() {
            addCriterion("geo_code is not null");
            return (Criteria) this;
        }

        public Criteria andGeoCodeEqualTo(String value) {
            addCriterion("geo_code =", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotEqualTo(String value) {
            addCriterion("geo_code <>", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeGreaterThan(String value) {
            addCriterion("geo_code >", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("geo_code >=", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLessThan(String value) {
            addCriterion("geo_code <", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLessThanOrEqualTo(String value) {
            addCriterion("geo_code <=", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLike(String value) {
            addCriterion("geo_code like", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotLike(String value) {
            addCriterion("geo_code not like", value, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeIn(List<String> values) {
            addCriterion("geo_code in", values, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotIn(List<String> values) {
            addCriterion("geo_code not in", values, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeBetween(String value1, String value2) {
            addCriterion("geo_code between", value1, value2, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoCodeNotBetween(String value1, String value2) {
            addCriterion("geo_code not between", value1, value2, "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeIsNull() {
            addCriterion("geo_sec_code is null");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeIsNotNull() {
            addCriterion("geo_sec_code is not null");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeEqualTo(String value) {
            addCriterion("geo_sec_code =", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeNotEqualTo(String value) {
            addCriterion("geo_sec_code <>", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeGreaterThan(String value) {
            addCriterion("geo_sec_code >", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeGreaterThanOrEqualTo(String value) {
            addCriterion("geo_sec_code >=", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeLessThan(String value) {
            addCriterion("geo_sec_code <", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeLessThanOrEqualTo(String value) {
            addCriterion("geo_sec_code <=", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeLike(String value) {
            addCriterion("geo_sec_code like", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeNotLike(String value) {
            addCriterion("geo_sec_code not like", value, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeIn(List<String> values) {
            addCriterion("geo_sec_code in", values, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeNotIn(List<String> values) {
            addCriterion("geo_sec_code not in", values, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeBetween(String value1, String value2) {
            addCriterion("geo_sec_code between", value1, value2, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeNotBetween(String value1, String value2) {
            addCriterion("geo_sec_code not between", value1, value2, "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNull() {
            addCriterion("abbreviation is null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIsNotNull() {
            addCriterion("abbreviation is not null");
            return (Criteria) this;
        }

        public Criteria andAbbreviationEqualTo(String value) {
            addCriterion("abbreviation =", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotEqualTo(String value) {
            addCriterion("abbreviation <>", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThan(String value) {
            addCriterion("abbreviation >", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationGreaterThanOrEqualTo(String value) {
            addCriterion("abbreviation >=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThan(String value) {
            addCriterion("abbreviation <", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLessThanOrEqualTo(String value) {
            addCriterion("abbreviation <=", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLike(String value) {
            addCriterion("abbreviation like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotLike(String value) {
            addCriterion("abbreviation not like", value, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationIn(List<String> values) {
            addCriterion("abbreviation in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotIn(List<String> values) {
            addCriterion("abbreviation not in", values, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationBetween(String value1, String value2) {
            addCriterion("abbreviation between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andAbbreviationNotBetween(String value1, String value2) {
            addCriterion("abbreviation not between", value1, value2, "abbreviation");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextIsNull() {
            addCriterion("well_known_text is null");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextIsNotNull() {
            addCriterion("well_known_text is not null");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextEqualTo(String value) {
            addCriterion("well_known_text =", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextNotEqualTo(String value) {
            addCriterion("well_known_text <>", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextGreaterThan(String value) {
            addCriterion("well_known_text >", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextGreaterThanOrEqualTo(String value) {
            addCriterion("well_known_text >=", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextLessThan(String value) {
            addCriterion("well_known_text <", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextLessThanOrEqualTo(String value) {
            addCriterion("well_known_text <=", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextLike(String value) {
            addCriterion("well_known_text like", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextNotLike(String value) {
            addCriterion("well_known_text not like", value, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextIn(List<String> values) {
            addCriterion("well_known_text in", values, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextNotIn(List<String> values) {
            addCriterion("well_known_text not in", values, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextBetween(String value1, String value2) {
            addCriterion("well_known_text between", value1, value2, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextNotBetween(String value1, String value2) {
            addCriterion("well_known_text not between", value1, value2, "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andGeoIdLikeInsensitive(String value) {
            addCriterion("lower(geo_id) like", (value != null) ? value.toLowerCase() : value , "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdLikeInsensitive(String value) {
            addCriterion("lower(geo_type_id) like", (value != null) ? value.toLowerCase() : value , "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoNameLikeInsensitive(String value) {
            addCriterion("lower(geo_name) like", (value != null) ? value.toLowerCase() : value , "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoCodeLikeInsensitive(String value) {
            addCriterion("lower(geo_code) like", (value != null) ? value.toLowerCase() : value , "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeLikeInsensitive(String value) {
            addCriterion("lower(geo_sec_code) like", (value != null) ? value.toLowerCase() : value , "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andAbbreviationLikeInsensitive(String value) {
            addCriterion("lower(abbreviation) like", (value != null) ? value.toLowerCase() : value , "abbreviation");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextLikeInsensitive(String value) {
            addCriterion("lower(well_known_text) like", (value != null) ? value.toLowerCase() : value , "wellKnownText");
            return (Criteria) this;
        }

        public Criteria andGeoIdEqualToInsensitive(String value) {
            addCriterion("lower(geo_id) =", (value != null) ? value.toLowerCase() : value , "geoId");
            return (Criteria) this;
        }

        public Criteria andGeoTypeIdEqualToInsensitive(String value) {
            addCriterion("lower(geo_type_id) =", (value != null) ? value.toLowerCase() : value , "geoTypeId");
            return (Criteria) this;
        }

        public Criteria andGeoNameEqualToInsensitive(String value) {
            addCriterion("lower(geo_name) =", (value != null) ? value.toLowerCase() : value , "geoName");
            return (Criteria) this;
        }

        public Criteria andGeoCodeEqualToInsensitive(String value) {
            addCriterion("lower(geo_code) =", (value != null) ? value.toLowerCase() : value , "geoCode");
            return (Criteria) this;
        }

        public Criteria andGeoSecCodeEqualToInsensitive(String value) {
            addCriterion("lower(geo_sec_code) =", (value != null) ? value.toLowerCase() : value , "geoSecCode");
            return (Criteria) this;
        }

        public Criteria andAbbreviationEqualToInsensitive(String value) {
            addCriterion("lower(abbreviation) =", (value != null) ? value.toLowerCase() : value , "abbreviation");
            return (Criteria) this;
        }

        public Criteria andWellKnownTextEqualToInsensitive(String value) {
            addCriterion("lower(well_known_text) =", (value != null) ? value.toLowerCase() : value , "wellKnownText");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geo
     *
     * @mbggenerated do_not_delete_during_merge Fri May 06 17:57:24 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}