package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class Lot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.code
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.description
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.created_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.modified_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.created_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.modified_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.job_order_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long jobOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.works_manager_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long worksManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.dtl_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long dtlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.assigned_company_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long assignedCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.note
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lot.owner_node_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.id
     *
     * @return the value of lot.id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.id
     *
     * @param id the value for lot.id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.code
     *
     * @return the value of lot.code
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.code
     *
     * @param code the value for lot.code
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.description
     *
     * @return the value of lot.description
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.description
     *
     * @param description the value for lot.description
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.created_stamp
     *
     * @return the value of lot.created_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.created_stamp
     *
     * @param createdStamp the value for lot.created_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.modified_stamp
     *
     * @return the value of lot.modified_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.modified_stamp
     *
     * @param modifiedStamp the value for lot.modified_stamp
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.created_by_user_id
     *
     * @return the value of lot.created_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.created_by_user_id
     *
     * @param createdByUserId the value for lot.created_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.modified_by_user_id
     *
     * @return the value of lot.modified_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.modified_by_user_id
     *
     * @param modifiedByUserId the value for lot.modified_by_user_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.job_order_id
     *
     * @return the value of lot.job_order_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getJobOrderId() {
        return jobOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.job_order_id
     *
     * @param jobOrderId the value for lot.job_order_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setJobOrderId(Long jobOrderId) {
        this.jobOrderId = jobOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.works_manager_id
     *
     * @return the value of lot.works_manager_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getWorksManagerId() {
        return worksManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.works_manager_id
     *
     * @param worksManagerId the value for lot.works_manager_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setWorksManagerId(Long worksManagerId) {
        this.worksManagerId = worksManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.dtl_id
     *
     * @return the value of lot.dtl_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getDtlId() {
        return dtlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.dtl_id
     *
     * @param dtlId the value for lot.dtl_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setDtlId(Long dtlId) {
        this.dtlId = dtlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.assigned_company_id
     *
     * @return the value of lot.assigned_company_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getAssignedCompanyId() {
        return assignedCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.assigned_company_id
     *
     * @param assignedCompanyId the value for lot.assigned_company_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setAssignedCompanyId(Long assignedCompanyId) {
        this.assignedCompanyId = assignedCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.note
     *
     * @return the value of lot.note
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.note
     *
     * @param note the value for lot.note
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lot.owner_node_id
     *
     * @return the value of lot.owner_node_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lot.owner_node_id
     *
     * @param ownerNodeId the value for lot.owner_node_id
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }
}