package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class NodeTimesheetConfiguration implements AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.modified_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.created_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.created_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.modified_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.disabled
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.weekly_work_log_check
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private Boolean weeklyWorkLogCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.username
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.password
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.ssl_pem_path
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String sslPemPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.registry_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String registryEndpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.timesheet_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String timesheetEndpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.timesheet_processed_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String timesheetProcessedEndpoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_timesheet_configuration.construction_site_field
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    private String constructionSiteField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.id
     *
     * @return the value of node_timesheet_configuration.id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.id
     *
     * @param id the value for node_timesheet_configuration.id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.modified_stamp
     *
     * @return the value of node_timesheet_configuration.modified_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.modified_stamp
     *
     * @param modifiedStamp the value for node_timesheet_configuration.modified_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.created_stamp
     *
     * @return the value of node_timesheet_configuration.created_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.created_stamp
     *
     * @param createdStamp the value for node_timesheet_configuration.created_stamp
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.created_by_user_id
     *
     * @return the value of node_timesheet_configuration.created_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.created_by_user_id
     *
     * @param createdByUserId the value for node_timesheet_configuration.created_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.modified_by_user_id
     *
     * @return the value of node_timesheet_configuration.modified_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.modified_by_user_id
     *
     * @param modifiedByUserId the value for node_timesheet_configuration.modified_by_user_id
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.disabled
     *
     * @return the value of node_timesheet_configuration.disabled
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.disabled
     *
     * @param disabled the value for node_timesheet_configuration.disabled
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.weekly_work_log_check
     *
     * @return the value of node_timesheet_configuration.weekly_work_log_check
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public Boolean getWeeklyWorkLogCheck() {
        return weeklyWorkLogCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.weekly_work_log_check
     *
     * @param weeklyWorkLogCheck the value for node_timesheet_configuration.weekly_work_log_check
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setWeeklyWorkLogCheck(Boolean weeklyWorkLogCheck) {
        this.weeklyWorkLogCheck = weeklyWorkLogCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.username
     *
     * @return the value of node_timesheet_configuration.username
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.username
     *
     * @param username the value for node_timesheet_configuration.username
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.password
     *
     * @return the value of node_timesheet_configuration.password
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.password
     *
     * @param password the value for node_timesheet_configuration.password
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.ssl_pem_path
     *
     * @return the value of node_timesheet_configuration.ssl_pem_path
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getSslPemPath() {
        return sslPemPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.ssl_pem_path
     *
     * @param sslPemPath the value for node_timesheet_configuration.ssl_pem_path
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setSslPemPath(String sslPemPath) {
        this.sslPemPath = sslPemPath == null ? null : sslPemPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.registry_endpoint
     *
     * @return the value of node_timesheet_configuration.registry_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getRegistryEndpoint() {
        return registryEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.registry_endpoint
     *
     * @param registryEndpoint the value for node_timesheet_configuration.registry_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setRegistryEndpoint(String registryEndpoint) {
        this.registryEndpoint = registryEndpoint == null ? null : registryEndpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.timesheet_endpoint
     *
     * @return the value of node_timesheet_configuration.timesheet_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getTimesheetEndpoint() {
        return timesheetEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.timesheet_endpoint
     *
     * @param timesheetEndpoint the value for node_timesheet_configuration.timesheet_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setTimesheetEndpoint(String timesheetEndpoint) {
        this.timesheetEndpoint = timesheetEndpoint == null ? null : timesheetEndpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.timesheet_processed_endpoint
     *
     * @return the value of node_timesheet_configuration.timesheet_processed_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getTimesheetProcessedEndpoint() {
        return timesheetProcessedEndpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.timesheet_processed_endpoint
     *
     * @param timesheetProcessedEndpoint the value for node_timesheet_configuration.timesheet_processed_endpoint
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setTimesheetProcessedEndpoint(String timesheetProcessedEndpoint) {
        this.timesheetProcessedEndpoint = timesheetProcessedEndpoint == null ? null : timesheetProcessedEndpoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_timesheet_configuration.construction_site_field
     *
     * @return the value of node_timesheet_configuration.construction_site_field
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public String getConstructionSiteField() {
        return constructionSiteField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_timesheet_configuration.construction_site_field
     *
     * @param constructionSiteField the value for node_timesheet_configuration.construction_site_field
     *
     * @mbggenerated Wed Jan 18 16:48:43 CET 2017
     */
    public void setConstructionSiteField(String constructionSiteField) {
        this.constructionSiteField = constructionSiteField == null ? null : constructionSiteField.trim();
    }
}