package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class NotificationGroup implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.modified_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.created_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.created_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.modified_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.owner_node_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private Long ownerNodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification_group.description
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.id
     *
     * @return the value of notification_group.id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.id
     *
     * @param id the value for notification_group.id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.modified_stamp
     *
     * @return the value of notification_group.modified_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.modified_stamp
     *
     * @param modifiedStamp the value for notification_group.modified_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.created_stamp
     *
     * @return the value of notification_group.created_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.created_stamp
     *
     * @param createdStamp the value for notification_group.created_stamp
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.created_by_user_id
     *
     * @return the value of notification_group.created_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.created_by_user_id
     *
     * @param createdByUserId the value for notification_group.created_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.modified_by_user_id
     *
     * @return the value of notification_group.modified_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.modified_by_user_id
     *
     * @param modifiedByUserId the value for notification_group.modified_by_user_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.owner_node_id
     *
     * @return the value of notification_group.owner_node_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.owner_node_id
     *
     * @param ownerNodeId the value for notification_group.owner_node_id
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification_group.description
     *
     * @return the value of notification_group.description
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification_group.description
     *
     * @param description the value for notification_group.description
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}