package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonEmploymentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public PersonEmploymentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> stateTagCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            stateTagCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStateTagCriteria() {
            return stateTagCriteria;
        }

        protected void addStateTagCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStateTagCriterion(String condition, EntityStateTag value1, EntityStateTag value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || stateTagCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(stateTagCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNull() {
            addCriterion("card_number is null");
            return (Criteria) this;
        }

        public Criteria andCardNumberIsNotNull() {
            addCriterion("card_number is not null");
            return (Criteria) this;
        }

        public Criteria andCardNumberEqualTo(Long value) {
            addCriterion("card_number =", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotEqualTo(Long value) {
            addCriterion("card_number <>", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThan(Long value) {
            addCriterion("card_number >", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("card_number >=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThan(Long value) {
            addCriterion("card_number <", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberLessThanOrEqualTo(Long value) {
            addCriterion("card_number <=", value, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberIn(List<Long> values) {
            addCriterion("card_number in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotIn(List<Long> values) {
            addCriterion("card_number not in", values, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberBetween(Long value1, Long value2) {
            addCriterion("card_number between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andCardNumberNotBetween(Long value1, Long value2) {
            addCriterion("card_number not between", value1, value2, "cardNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberIsNull() {
            addCriterion("badge_number is null");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberIsNotNull() {
            addCriterion("badge_number is not null");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberEqualTo(String value) {
            addCriterion("badge_number =", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberNotEqualTo(String value) {
            addCriterion("badge_number <>", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberGreaterThan(String value) {
            addCriterion("badge_number >", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberGreaterThanOrEqualTo(String value) {
            addCriterion("badge_number >=", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberLessThan(String value) {
            addCriterion("badge_number <", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberLessThanOrEqualTo(String value) {
            addCriterion("badge_number <=", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberLike(String value) {
            addCriterion("badge_number like", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberNotLike(String value) {
            addCriterion("badge_number not like", value, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberIn(List<String> values) {
            addCriterion("badge_number in", values, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberNotIn(List<String> values) {
            addCriterion("badge_number not in", values, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberBetween(String value1, String value2) {
            addCriterion("badge_number between", value1, value2, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberNotBetween(String value1, String value2) {
            addCriterion("badge_number not between", value1, value2, "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterionForJDBCDate("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterionForJDBCDate("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("state_id is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("state_id is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(Long value) {
            addCriterion("state_id =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(Long value) {
            addCriterion("state_id <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(Long value) {
            addCriterion("state_id >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("state_id >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(Long value) {
            addCriterion("state_id <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(Long value) {
            addCriterion("state_id <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<Long> values) {
            addCriterion("state_id in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<Long> values) {
            addCriterion("state_id not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(Long value1, Long value2) {
            addCriterion("state_id between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(Long value1, Long value2) {
            addCriterion("state_id not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNull() {
            addCriterion("person_id is null");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNotNull() {
            addCriterion("person_id is not null");
            return (Criteria) this;
        }

        public Criteria andPersonIdEqualTo(Long value) {
            addCriterion("person_id =", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotEqualTo(Long value) {
            addCriterion("person_id <>", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThan(Long value) {
            addCriterion("person_id >", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThanOrEqualTo(Long value) {
            addCriterion("person_id >=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThan(Long value) {
            addCriterion("person_id <", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThanOrEqualTo(Long value) {
            addCriterion("person_id <=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIn(List<Long> values) {
            addCriterion("person_id in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotIn(List<Long> values) {
            addCriterion("person_id not in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdBetween(Long value1, Long value2) {
            addCriterion("person_id between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotBetween(Long value1, Long value2) {
            addCriterion("person_id not between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Long value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Long value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Long value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Long value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Long> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Long> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Long value1, Long value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Long value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Long value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Long value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Long value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Long value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Long> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Long> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Long value1, Long value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Long value1, Long value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNull() {
            addCriterion("job_description is null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIsNotNull() {
            addCriterion("job_description is not null");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionEqualTo(String value) {
            addCriterion("job_description =", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotEqualTo(String value) {
            addCriterion("job_description <>", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThan(String value) {
            addCriterion("job_description >", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("job_description >=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThan(String value) {
            addCriterion("job_description <", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLessThanOrEqualTo(String value) {
            addCriterion("job_description <=", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLike(String value) {
            addCriterion("job_description like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotLike(String value) {
            addCriterion("job_description not like", value, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionIn(List<String> values) {
            addCriterion("job_description in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotIn(List<String> values) {
            addCriterion("job_description not in", values, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionBetween(String value1, String value2) {
            addCriterion("job_description between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionNotBetween(String value1, String value2) {
            addCriterion("job_description not between", value1, value2, "jobDescription");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateIsNull() {
            addCriterion("assumption_date is null");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateIsNotNull() {
            addCriterion("assumption_date is not null");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateEqualTo(Date value) {
            addCriterionForJDBCDate("assumption_date =", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("assumption_date <>", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("assumption_date >", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("assumption_date >=", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateLessThan(Date value) {
            addCriterionForJDBCDate("assumption_date <", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("assumption_date <=", value, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateIn(List<Date> values) {
            addCriterionForJDBCDate("assumption_date in", values, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("assumption_date not in", values, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("assumption_date between", value1, value2, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andAssumptionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("assumption_date not between", value1, value2, "assumptionDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateIsNull() {
            addCriterion("dismissal_date is null");
            return (Criteria) this;
        }

        public Criteria andDismissalDateIsNotNull() {
            addCriterion("dismissal_date is not null");
            return (Criteria) this;
        }

        public Criteria andDismissalDateEqualTo(Date value) {
            addCriterionForJDBCDate("dismissal_date =", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("dismissal_date <>", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateGreaterThan(Date value) {
            addCriterionForJDBCDate("dismissal_date >", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dismissal_date >=", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateLessThan(Date value) {
            addCriterionForJDBCDate("dismissal_date <", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("dismissal_date <=", value, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateIn(List<Date> values) {
            addCriterionForJDBCDate("dismissal_date in", values, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("dismissal_date not in", values, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dismissal_date between", value1, value2, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDismissalDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("dismissal_date not between", value1, value2, "dismissalDate");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdIsNull() {
            addCriterion("destination_company_id is null");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdIsNotNull() {
            addCriterion("destination_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdEqualTo(Long value) {
            addCriterion("destination_company_id =", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdNotEqualTo(Long value) {
            addCriterion("destination_company_id <>", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdGreaterThan(Long value) {
            addCriterion("destination_company_id >", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("destination_company_id >=", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdLessThan(Long value) {
            addCriterion("destination_company_id <", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("destination_company_id <=", value, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdIn(List<Long> values) {
            addCriterion("destination_company_id in", values, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdNotIn(List<Long> values) {
            addCriterion("destination_company_id not in", values, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdBetween(Long value1, Long value2) {
            addCriterion("destination_company_id between", value1, value2, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andDestinationCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("destination_company_id not between", value1, value2, "destinationCompanyId");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNull() {
            addCriterion("state_tag is null");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNotNull() {
            addCriterion("state_tag is not null");
            return (Criteria) this;
        }

        public Criteria andStateTagEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag =", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <>", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThan(EntityStateTag value) {
            addStateTagCriterion("state_tag >", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag >=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThan(EntityStateTag value) {
            addStateTagCriterion("state_tag <", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLike(EntityStateTag value) {
            addStateTagCriterion("state_tag like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotLike(EntityStateTag value) {
            addStateTagCriterion("state_tag not like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag not in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag not between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andExportedStampIsNull() {
            addCriterion("exported_stamp is null");
            return (Criteria) this;
        }

        public Criteria andExportedStampIsNotNull() {
            addCriterion("exported_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andExportedStampEqualTo(Date value) {
            addCriterion("exported_stamp =", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampNotEqualTo(Date value) {
            addCriterion("exported_stamp <>", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampGreaterThan(Date value) {
            addCriterion("exported_stamp >", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("exported_stamp >=", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampLessThan(Date value) {
            addCriterion("exported_stamp <", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampLessThanOrEqualTo(Date value) {
            addCriterion("exported_stamp <=", value, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampIn(List<Date> values) {
            addCriterion("exported_stamp in", values, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampNotIn(List<Date> values) {
            addCriterion("exported_stamp not in", values, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampBetween(Date value1, Date value2) {
            addCriterion("exported_stamp between", value1, value2, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExportedStampNotBetween(Date value1, Date value2) {
            addCriterion("exported_stamp not between", value1, value2, "exportedStamp");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNull() {
            addCriterion("external_id is null");
            return (Criteria) this;
        }

        public Criteria andExternalIdIsNotNull() {
            addCriterion("external_id is not null");
            return (Criteria) this;
        }

        public Criteria andExternalIdEqualTo(String value) {
            addCriterion("external_id =", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotEqualTo(String value) {
            addCriterion("external_id <>", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThan(String value) {
            addCriterion("external_id >", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdGreaterThanOrEqualTo(String value) {
            addCriterion("external_id >=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThan(String value) {
            addCriterion("external_id <", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLessThanOrEqualTo(String value) {
            addCriterion("external_id <=", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdLike(String value) {
            addCriterion("external_id like", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotLike(String value) {
            addCriterion("external_id not like", value, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdIn(List<String> values) {
            addCriterion("external_id in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotIn(List<String> values) {
            addCriterion("external_id not in", values, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdBetween(String value1, String value2) {
            addCriterion("external_id between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andExternalIdNotBetween(String value1, String value2) {
            addCriterion("external_id not between", value1, value2, "externalId");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberLikeInsensitive(String value) {
            addCriterion("lower(badge_number) like", (value != null) ? value.toLowerCase() : value , "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionLikeInsensitive(String value) {
            addCriterion("lower(job_description) like", (value != null) ? value.toLowerCase() : value , "jobDescription");
            return (Criteria) this;
        }

        public Criteria andLevelLikeInsensitive(String value) {
            addCriterion("lower(level) like", (value != null) ? value.toLowerCase() : value , "level");
            return (Criteria) this;
        }

        public Criteria andExternalIdLikeInsensitive(String value) {
            addCriterion("lower(external_id) like", (value != null) ? value.toLowerCase() : value , "externalId");
            return (Criteria) this;
        }

        public Criteria andBadgeNumberEqualToInsensitive(String value) {
            addCriterion("lower(badge_number) =", (value != null) ? value.toLowerCase() : value , "badgeNumber");
            return (Criteria) this;
        }

        public Criteria andJobDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(job_description) =", (value != null) ? value.toLowerCase() : value , "jobDescription");
            return (Criteria) this;
        }

        public Criteria andLevelEqualToInsensitive(String value) {
            addCriterion("lower(level) =", (value != null) ? value.toLowerCase() : value , "level");
            return (Criteria) this;
        }

        public Criteria andExternalIdEqualToInsensitive(String value) {
            addCriterion("lower(external_id) =", (value != null) ? value.toLowerCase() : value , "externalId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_employment
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 15 17:58:12 CET 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}