package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class SecurityRole implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.description
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.modified_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.created_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.created_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column security_role.modified_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.id
     *
     * @return the value of security_role.id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.id
     *
     * @param id the value for security_role.id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.description
     *
     * @return the value of security_role.description
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.description
     *
     * @param description the value for security_role.description
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.modified_stamp
     *
     * @return the value of security_role.modified_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.modified_stamp
     *
     * @param modifiedStamp the value for security_role.modified_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.created_stamp
     *
     * @return the value of security_role.created_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.created_stamp
     *
     * @param createdStamp the value for security_role.created_stamp
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.created_by_user_id
     *
     * @return the value of security_role.created_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.created_by_user_id
     *
     * @param createdByUserId the value for security_role.created_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column security_role.modified_by_user_id
     *
     * @return the value of security_role.modified_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column security_role.modified_by_user_id
     *
     * @param modifiedByUserId the value for security_role.modified_by_user_id
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }
}