package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.Date;

public class Wbs implements AbstractIdentifiable, AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.code
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.description
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.created_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.modified_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.created_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.modified_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.job_order_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long jobOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.construction_site_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long constructionSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.note
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wbs.owner_node_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    private Long ownerNodeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.id
     *
     * @return the value of wbs.id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.id
     *
     * @param id the value for wbs.id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.code
     *
     * @return the value of wbs.code
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.code
     *
     * @param code the value for wbs.code
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.description
     *
     * @return the value of wbs.description
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.description
     *
     * @param description the value for wbs.description
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.created_stamp
     *
     * @return the value of wbs.created_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.created_stamp
     *
     * @param createdStamp the value for wbs.created_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.modified_stamp
     *
     * @return the value of wbs.modified_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.modified_stamp
     *
     * @param modifiedStamp the value for wbs.modified_stamp
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.created_by_user_id
     *
     * @return the value of wbs.created_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.created_by_user_id
     *
     * @param createdByUserId the value for wbs.created_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.modified_by_user_id
     *
     * @return the value of wbs.modified_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.modified_by_user_id
     *
     * @param modifiedByUserId the value for wbs.modified_by_user_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.job_order_id
     *
     * @return the value of wbs.job_order_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getJobOrderId() {
        return jobOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.job_order_id
     *
     * @param jobOrderId the value for wbs.job_order_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setJobOrderId(Long jobOrderId) {
        this.jobOrderId = jobOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.construction_site_id
     *
     * @return the value of wbs.construction_site_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getConstructionSiteId() {
        return constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.construction_site_id
     *
     * @param constructionSiteId the value for wbs.construction_site_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setConstructionSiteId(Long constructionSiteId) {
        this.constructionSiteId = constructionSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.note
     *
     * @return the value of wbs.note
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.note
     *
     * @param note the value for wbs.note
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wbs.owner_node_id
     *
     * @return the value of wbs.owner_node_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wbs.owner_node_id
     *
     * @param ownerNodeId the value for wbs.owner_node_id
     *
     * @mbggenerated Thu Oct 20 17:49:33 CEST 2016
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
    }
}