package it.memelabs.smartnebula.lmm.persistence.main.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WbsPartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public WbsPartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIsNull() {
            addCriterion("job_order_id is null");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIsNotNull() {
            addCriterion("job_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdEqualTo(Long value) {
            addCriterion("job_order_id =", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotEqualTo(Long value) {
            addCriterion("job_order_id <>", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdGreaterThan(Long value) {
            addCriterion("job_order_id >", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_order_id >=", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdLessThan(Long value) {
            addCriterion("job_order_id <", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("job_order_id <=", value, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdIn(List<Long> values) {
            addCriterion("job_order_id in", values, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotIn(List<Long> values) {
            addCriterion("job_order_id not in", values, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdBetween(Long value1, Long value2) {
            addCriterion("job_order_id between", value1, value2, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andJobOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("job_order_id not between", value1, value2, "jobOrderId");
            return (Criteria) this;
        }

        public Criteria andWbsIdIsNull() {
            addCriterion("wbs_id is null");
            return (Criteria) this;
        }

        public Criteria andWbsIdIsNotNull() {
            addCriterion("wbs_id is not null");
            return (Criteria) this;
        }

        public Criteria andWbsIdEqualTo(Long value) {
            addCriterion("wbs_id =", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotEqualTo(Long value) {
            addCriterion("wbs_id <>", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdGreaterThan(Long value) {
            addCriterion("wbs_id >", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("wbs_id >=", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdLessThan(Long value) {
            addCriterion("wbs_id <", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdLessThanOrEqualTo(Long value) {
            addCriterion("wbs_id <=", value, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdIn(List<Long> values) {
            addCriterion("wbs_id in", values, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotIn(List<Long> values) {
            addCriterion("wbs_id not in", values, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdBetween(Long value1, Long value2) {
            addCriterion("wbs_id between", value1, value2, "wbsId");
            return (Criteria) this;
        }

        public Criteria andWbsIdNotBetween(Long value1, Long value2) {
            addCriterion("wbs_id not between", value1, value2, "wbsId");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("lower(code) like", (value != null) ? value.toLowerCase() : value , "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("lower(description) like", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }

        public Criteria andCodeEqualToInsensitive(String value) {
            addCriterion("lower(code) =", (value != null) ? value.toLowerCase() : value , "code");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualToInsensitive(String value) {
            addCriterion("lower(description) =", (value != null) ? value.toLowerCase() : value , "description");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wbs_part
     *
     * @mbggenerated do_not_delete_during_merge Thu May 05 10:57:10 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wbs_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}