package it.memelabs.smartnebula.lmm.persistence.main.dto;

public class WorkLogPersonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person.work_log_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    private Long workLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person.person_empl_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    private Long personEmplId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person.work_log_id
     *
     * @return the value of work_log_person.work_log_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    public Long getWorkLogId() {
        return workLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person.work_log_id
     *
     * @param workLogId the value for work_log_person.work_log_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    public void setWorkLogId(Long workLogId) {
        this.workLogId = workLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person.person_empl_id
     *
     * @return the value of work_log_person.person_empl_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    public Long getPersonEmplId() {
        return personEmplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person.person_empl_id
     *
     * @param personEmplId the value for work_log_person.person_empl_id
     *
     * @mbggenerated Thu Jun 16 16:12:02 CEST 2016
     */
    public void setPersonEmplId(Long personEmplId) {
        this.personEmplId = personEmplId;
    }
}