package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.WorkLogEventDirection;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkLogRejectedEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public WorkLogRejectedEventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> directionCriteria;

        protected List<Criterion> stateTagCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            directionCriteria = new ArrayList<Criterion>();
            stateTagCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getDirectionCriteria() {
            return directionCriteria;
        }

        protected void addDirectionCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            directionCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addDirectionCriterion(String condition, WorkLogEventDirection value1, WorkLogEventDirection value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            directionCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getStateTagCriteria() {
            return stateTagCriteria;
        }

        protected void addStateTagCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        protected void addStateTagCriterion(String condition, EntityStateTag value1, EntityStateTag value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            stateTagCriteria.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || directionCriteria.size() > 0
                || stateTagCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(directionCriteria);
                allCriteria.addAll(stateTagCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNull() {
            addCriterion("modified_stamp is null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIsNotNull() {
            addCriterion("modified_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedStampEqualTo(Date value) {
            addCriterion("modified_stamp =", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotEqualTo(Date value) {
            addCriterion("modified_stamp <>", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThan(Date value) {
            addCriterion("modified_stamp >", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_stamp >=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThan(Date value) {
            addCriterion("modified_stamp <", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampLessThanOrEqualTo(Date value) {
            addCriterion("modified_stamp <=", value, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampIn(List<Date> values) {
            addCriterion("modified_stamp in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotIn(List<Date> values) {
            addCriterion("modified_stamp not in", values, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampBetween(Date value1, Date value2) {
            addCriterion("modified_stamp between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andModifiedStampNotBetween(Date value1, Date value2) {
            addCriterion("modified_stamp not between", value1, value2, "modifiedStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNull() {
            addCriterion("created_stamp is null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIsNotNull() {
            addCriterion("created_stamp is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedStampEqualTo(Date value) {
            addCriterion("created_stamp =", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotEqualTo(Date value) {
            addCriterion("created_stamp <>", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThan(Date value) {
            addCriterion("created_stamp >", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampGreaterThanOrEqualTo(Date value) {
            addCriterion("created_stamp >=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThan(Date value) {
            addCriterion("created_stamp <", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampLessThanOrEqualTo(Date value) {
            addCriterion("created_stamp <=", value, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampIn(List<Date> values) {
            addCriterion("created_stamp in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotIn(List<Date> values) {
            addCriterion("created_stamp not in", values, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampBetween(Date value1, Date value2) {
            addCriterion("created_stamp between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedStampNotBetween(Date value1, Date value2) {
            addCriterion("created_stamp not between", value1, value2, "createdStamp");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNull() {
            addCriterion("created_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIsNotNull() {
            addCriterion("created_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdEqualTo(Long value) {
            addCriterion("created_by_user_id =", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotEqualTo(Long value) {
            addCriterion("created_by_user_id <>", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThan(Long value) {
            addCriterion("created_by_user_id >", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id >=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThan(Long value) {
            addCriterion("created_by_user_id <", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("created_by_user_id <=", value, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdIn(List<Long> values) {
            addCriterion("created_by_user_id in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotIn(List<Long> values) {
            addCriterion("created_by_user_id not in", values, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andCreatedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("created_by_user_id not between", value1, value2, "createdByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNull() {
            addCriterion("modified_by_user_id is null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIsNotNull() {
            addCriterion("modified_by_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdEqualTo(Long value) {
            addCriterion("modified_by_user_id =", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotEqualTo(Long value) {
            addCriterion("modified_by_user_id <>", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThan(Long value) {
            addCriterion("modified_by_user_id >", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id >=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThan(Long value) {
            addCriterion("modified_by_user_id <", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdLessThanOrEqualTo(Long value) {
            addCriterion("modified_by_user_id <=", value, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdIn(List<Long> values) {
            addCriterion("modified_by_user_id in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotIn(List<Long> values) {
            addCriterion("modified_by_user_id not in", values, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andModifiedByUserIdNotBetween(Long value1, Long value2) {
            addCriterion("modified_by_user_id not between", value1, value2, "modifiedByUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNull() {
            addCriterion("owner_node_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIsNotNull() {
            addCriterion("owner_node_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdEqualTo(Long value) {
            addCriterion("owner_node_id =", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotEqualTo(Long value) {
            addCriterion("owner_node_id <>", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThan(Long value) {
            addCriterion("owner_node_id >", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_node_id >=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThan(Long value) {
            addCriterion("owner_node_id <", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_node_id <=", value, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdIn(List<Long> values) {
            addCriterion("owner_node_id in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotIn(List<Long> values) {
            addCriterion("owner_node_id not in", values, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdBetween(Long value1, Long value2) {
            addCriterion("owner_node_id between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andOwnerNodeIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_node_id not between", value1, value2, "ownerNodeId");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeIsNull() {
            addCriterion("identification_code is null");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeIsNotNull() {
            addCriterion("identification_code is not null");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeEqualTo(String value) {
            addCriterion("identification_code =", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeNotEqualTo(String value) {
            addCriterion("identification_code <>", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeGreaterThan(String value) {
            addCriterion("identification_code >", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("identification_code >=", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeLessThan(String value) {
            addCriterion("identification_code <", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeLessThanOrEqualTo(String value) {
            addCriterion("identification_code <=", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeLike(String value) {
            addCriterion("identification_code like", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeNotLike(String value) {
            addCriterion("identification_code not like", value, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeIn(List<String> values) {
            addCriterion("identification_code in", values, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeNotIn(List<String> values) {
            addCriterion("identification_code not in", values, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeBetween(String value1, String value2) {
            addCriterion("identification_code between", value1, value2, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeNotBetween(String value1, String value2) {
            addCriterion("identification_code not between", value1, value2, "identificationCode");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNull() {
            addCriterion("direction is null");
            return (Criteria) this;
        }

        public Criteria andDirectionIsNotNull() {
            addCriterion("direction is not null");
            return (Criteria) this;
        }

        public Criteria andDirectionEqualTo(WorkLogEventDirection value) {
            addDirectionCriterion("direction =", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotEqualTo(WorkLogEventDirection value) {
            addDirectionCriterion("direction <>", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThan(WorkLogEventDirection value) {
            addDirectionCriterion("direction >", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionGreaterThanOrEqualTo(WorkLogEventDirection value) {
            addDirectionCriterion("direction >=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThan(WorkLogEventDirection value) {
            addDirectionCriterion("direction <", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLessThanOrEqualTo(WorkLogEventDirection value) {
            addDirectionCriterion("direction <=", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionLike(WorkLogEventDirection value) {
            addDirectionCriterion("direction like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotLike(WorkLogEventDirection value) {
            addDirectionCriterion("direction not like", value, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionIn(List<WorkLogEventDirection> values) {
            addDirectionCriterion("direction in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotIn(List<WorkLogEventDirection> values) {
            addDirectionCriterion("direction not in", values, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionBetween(WorkLogEventDirection value1, WorkLogEventDirection value2) {
            addDirectionCriterion("direction between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andDirectionNotBetween(WorkLogEventDirection value1, WorkLogEventDirection value2) {
            addDirectionCriterion("direction not between", value1, value2, "direction");
            return (Criteria) this;
        }

        public Criteria andCausaleIsNull() {
            addCriterion("causale is null");
            return (Criteria) this;
        }

        public Criteria andCausaleIsNotNull() {
            addCriterion("causale is not null");
            return (Criteria) this;
        }

        public Criteria andCausaleEqualTo(String value) {
            addCriterion("causale =", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleNotEqualTo(String value) {
            addCriterion("causale <>", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleGreaterThan(String value) {
            addCriterion("causale >", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleGreaterThanOrEqualTo(String value) {
            addCriterion("causale >=", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleLessThan(String value) {
            addCriterion("causale <", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleLessThanOrEqualTo(String value) {
            addCriterion("causale <=", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleLike(String value) {
            addCriterion("causale like", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleNotLike(String value) {
            addCriterion("causale not like", value, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleIn(List<String> values) {
            addCriterion("causale in", values, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleNotIn(List<String> values) {
            addCriterion("causale not in", values, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleBetween(String value1, String value2) {
            addCriterion("causale between", value1, value2, "causale");
            return (Criteria) this;
        }

        public Criteria andCausaleNotBetween(String value1, String value2) {
            addCriterion("causale not between", value1, value2, "causale");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andLettoreIsNull() {
            addCriterion("lettore is null");
            return (Criteria) this;
        }

        public Criteria andLettoreIsNotNull() {
            addCriterion("lettore is not null");
            return (Criteria) this;
        }

        public Criteria andLettoreEqualTo(String value) {
            addCriterion("lettore =", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreNotEqualTo(String value) {
            addCriterion("lettore <>", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreGreaterThan(String value) {
            addCriterion("lettore >", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreGreaterThanOrEqualTo(String value) {
            addCriterion("lettore >=", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreLessThan(String value) {
            addCriterion("lettore <", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreLessThanOrEqualTo(String value) {
            addCriterion("lettore <=", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreLike(String value) {
            addCriterion("lettore like", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreNotLike(String value) {
            addCriterion("lettore not like", value, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreIn(List<String> values) {
            addCriterion("lettore in", values, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreNotIn(List<String> values) {
            addCriterion("lettore not in", values, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreBetween(String value1, String value2) {
            addCriterion("lettore between", value1, value2, "lettore");
            return (Criteria) this;
        }

        public Criteria andLettoreNotBetween(String value1, String value2) {
            addCriterion("lettore not between", value1, value2, "lettore");
            return (Criteria) this;
        }

        public Criteria andWbsIsNull() {
            addCriterion("wbs is null");
            return (Criteria) this;
        }

        public Criteria andWbsIsNotNull() {
            addCriterion("wbs is not null");
            return (Criteria) this;
        }

        public Criteria andWbsEqualTo(String value) {
            addCriterion("wbs =", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotEqualTo(String value) {
            addCriterion("wbs <>", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsGreaterThan(String value) {
            addCriterion("wbs >", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsGreaterThanOrEqualTo(String value) {
            addCriterion("wbs >=", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsLessThan(String value) {
            addCriterion("wbs <", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsLessThanOrEqualTo(String value) {
            addCriterion("wbs <=", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsLike(String value) {
            addCriterion("wbs like", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotLike(String value) {
            addCriterion("wbs not like", value, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsIn(List<String> values) {
            addCriterion("wbs in", values, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotIn(List<String> values) {
            addCriterion("wbs not in", values, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsBetween(String value1, String value2) {
            addCriterion("wbs between", value1, value2, "wbs");
            return (Criteria) this;
        }

        public Criteria andWbsNotBetween(String value1, String value2) {
            addCriterion("wbs not between", value1, value2, "wbs");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("state_id is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("state_id is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(Long value) {
            addCriterion("state_id =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(Long value) {
            addCriterion("state_id <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(Long value) {
            addCriterion("state_id >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("state_id >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(Long value) {
            addCriterion("state_id <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(Long value) {
            addCriterion("state_id <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<Long> values) {
            addCriterion("state_id in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<Long> values) {
            addCriterion("state_id not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(Long value1, Long value2) {
            addCriterion("state_id between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(Long value1, Long value2) {
            addCriterion("state_id not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNull() {
            addCriterion("state_tag is null");
            return (Criteria) this;
        }

        public Criteria andStateTagIsNotNull() {
            addCriterion("state_tag is not null");
            return (Criteria) this;
        }

        public Criteria andStateTagEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag =", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <>", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThan(EntityStateTag value) {
            addStateTagCriterion("state_tag >", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagGreaterThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag >=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThan(EntityStateTag value) {
            addStateTagCriterion("state_tag <", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLessThanOrEqualTo(EntityStateTag value) {
            addStateTagCriterion("state_tag <=", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagLike(EntityStateTag value) {
            addStateTagCriterion("state_tag like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotLike(EntityStateTag value) {
            addStateTagCriterion("state_tag not like", value, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotIn(List<EntityStateTag> values) {
            addStateTagCriterion("state_tag not in", values, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andStateTagNotBetween(EntityStateTag value1, EntityStateTag value2) {
            addStateTagCriterion("state_tag not between", value1, value2, "stateTag");
            return (Criteria) this;
        }

        public Criteria andErrorIsNull() {
            addCriterion("error is null");
            return (Criteria) this;
        }

        public Criteria andErrorIsNotNull() {
            addCriterion("error is not null");
            return (Criteria) this;
        }

        public Criteria andErrorEqualTo(String value) {
            addCriterion("error =", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotEqualTo(String value) {
            addCriterion("error <>", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThan(String value) {
            addCriterion("error >", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThanOrEqualTo(String value) {
            addCriterion("error >=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThan(String value) {
            addCriterion("error <", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThanOrEqualTo(String value) {
            addCriterion("error <=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLike(String value) {
            addCriterion("error like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotLike(String value) {
            addCriterion("error not like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorIn(List<String> values) {
            addCriterion("error in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotIn(List<String> values) {
            addCriterion("error not in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorBetween(String value1, String value2) {
            addCriterion("error between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotBetween(String value1, String value2) {
            addCriterion("error not between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andReceivedDataIsNull() {
            addCriterion("received_data is null");
            return (Criteria) this;
        }

        public Criteria andReceivedDataIsNotNull() {
            addCriterion("received_data is not null");
            return (Criteria) this;
        }

        public Criteria andReceivedDataEqualTo(String value) {
            addCriterion("received_data =", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataNotEqualTo(String value) {
            addCriterion("received_data <>", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataGreaterThan(String value) {
            addCriterion("received_data >", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataGreaterThanOrEqualTo(String value) {
            addCriterion("received_data >=", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataLessThan(String value) {
            addCriterion("received_data <", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataLessThanOrEqualTo(String value) {
            addCriterion("received_data <=", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataLike(String value) {
            addCriterion("received_data like", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataNotLike(String value) {
            addCriterion("received_data not like", value, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataIn(List<String> values) {
            addCriterion("received_data in", values, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataNotIn(List<String> values) {
            addCriterion("received_data not in", values, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataBetween(String value1, String value2) {
            addCriterion("received_data between", value1, value2, "receivedData");
            return (Criteria) this;
        }

        public Criteria andReceivedDataNotBetween(String value1, String value2) {
            addCriterion("received_data not between", value1, value2, "receivedData");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeLikeInsensitive(String value) {
            addCriterion("lower(identification_code) like", (value != null) ? value.toLowerCase() : value , "identificationCode");
            return (Criteria) this;
        }

        public Criteria andCausaleLikeInsensitive(String value) {
            addCriterion("lower(causale) like", (value != null) ? value.toLowerCase() : value , "causale");
            return (Criteria) this;
        }

        public Criteria andLettoreLikeInsensitive(String value) {
            addCriterion("lower(lettore) like", (value != null) ? value.toLowerCase() : value , "lettore");
            return (Criteria) this;
        }

        public Criteria andWbsLikeInsensitive(String value) {
            addCriterion("lower(wbs) like", (value != null) ? value.toLowerCase() : value , "wbs");
            return (Criteria) this;
        }

        public Criteria andErrorLikeInsensitive(String value) {
            addCriterion("lower(error) like", (value != null) ? value.toLowerCase() : value , "error");
            return (Criteria) this;
        }

        public Criteria andReceivedDataLikeInsensitive(String value) {
            addCriterion("lower(received_data) like", (value != null) ? value.toLowerCase() : value , "receivedData");
            return (Criteria) this;
        }

        public Criteria andGroupIdLikeInsensitive(String value) {
            addCriterion("lower(group_id) like", (value != null) ? value.toLowerCase() : value , "groupId");
            return (Criteria) this;
        }

        public Criteria andIdentificationCodeEqualToInsensitive(String value) {
            addCriterion("lower(identification_code) =", (value != null) ? value.toLowerCase() : value , "identificationCode");
            return (Criteria) this;
        }

        public Criteria andCausaleEqualToInsensitive(String value) {
            addCriterion("lower(causale) =", (value != null) ? value.toLowerCase() : value , "causale");
            return (Criteria) this;
        }

        public Criteria andLettoreEqualToInsensitive(String value) {
            addCriterion("lower(lettore) =", (value != null) ? value.toLowerCase() : value , "lettore");
            return (Criteria) this;
        }

        public Criteria andWbsEqualToInsensitive(String value) {
            addCriterion("lower(wbs) =", (value != null) ? value.toLowerCase() : value , "wbs");
            return (Criteria) this;
        }

        public Criteria andErrorEqualToInsensitive(String value) {
            addCriterion("lower(error) =", (value != null) ? value.toLowerCase() : value , "error");
            return (Criteria) this;
        }

        public Criteria andReceivedDataEqualToInsensitive(String value) {
            addCriterion("lower(received_data) =", (value != null) ? value.toLowerCase() : value , "receivedData");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualToInsensitive(String value) {
            addCriterion("lower(group_id) =", (value != null) ? value.toLowerCase() : value , "groupId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 02 13:08:24 CET 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table work_log_rejected_event
     *
     * @mbggenerated Mon Jan 02 13:08:24 CET 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}