package it.memelabs.smartnebula.lmm.persistence.main.dto;

import it.memelabs.smartnebula.lmm.persistence.main.enumeration.EntityStateTag;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.WorkLogEventDirection;
import it.memelabs.smartnebula.lmm.persistence.main.enumeration.WorkLogEventOrigin;
import java.util.Date;

public class WorkLogPersonEvent implements AbstractIdentity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.work_log_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long workLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.person_empl_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long personEmplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.event_timestamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Date eventTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.modified_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Date modifiedStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.created_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Date createdStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.created_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long createdByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.modified_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long modifiedByUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.wbs_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long wbsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.direction
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private WorkLogEventDirection direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.state_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private Long stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.state_tag
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private EntityStateTag stateTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.error
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private String error;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.received_data
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private String receivedData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.group_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_log_person_event.origin
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    private WorkLogEventOrigin origin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.id
     *
     * @return the value of work_log_person_event.id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.id
     *
     * @param id the value for work_log_person_event.id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.work_log_id
     *
     * @return the value of work_log_person_event.work_log_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getWorkLogId() {
        return workLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.work_log_id
     *
     * @param workLogId the value for work_log_person_event.work_log_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setWorkLogId(Long workLogId) {
        this.workLogId = workLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.person_empl_id
     *
     * @return the value of work_log_person_event.person_empl_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getPersonEmplId() {
        return personEmplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.person_empl_id
     *
     * @param personEmplId the value for work_log_person_event.person_empl_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setPersonEmplId(Long personEmplId) {
        this.personEmplId = personEmplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.event_timestamp
     *
     * @return the value of work_log_person_event.event_timestamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Date getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.event_timestamp
     *
     * @param eventTimestamp the value for work_log_person_event.event_timestamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setEventTimestamp(Date eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.modified_stamp
     *
     * @return the value of work_log_person_event.modified_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Date getModifiedStamp() {
        return modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.modified_stamp
     *
     * @param modifiedStamp the value for work_log_person_event.modified_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setModifiedStamp(Date modifiedStamp) {
        this.modifiedStamp = modifiedStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.created_stamp
     *
     * @return the value of work_log_person_event.created_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Date getCreatedStamp() {
        return createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.created_stamp
     *
     * @param createdStamp the value for work_log_person_event.created_stamp
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setCreatedStamp(Date createdStamp) {
        this.createdStamp = createdStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.created_by_user_id
     *
     * @return the value of work_log_person_event.created_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getCreatedByUserId() {
        return createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.created_by_user_id
     *
     * @param createdByUserId the value for work_log_person_event.created_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setCreatedByUserId(Long createdByUserId) {
        this.createdByUserId = createdByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.modified_by_user_id
     *
     * @return the value of work_log_person_event.modified_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getModifiedByUserId() {
        return modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.modified_by_user_id
     *
     * @param modifiedByUserId the value for work_log_person_event.modified_by_user_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setModifiedByUserId(Long modifiedByUserId) {
        this.modifiedByUserId = modifiedByUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.wbs_id
     *
     * @return the value of work_log_person_event.wbs_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getWbsId() {
        return wbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.wbs_id
     *
     * @param wbsId the value for work_log_person_event.wbs_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setWbsId(Long wbsId) {
        this.wbsId = wbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.direction
     *
     * @return the value of work_log_person_event.direction
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public WorkLogEventDirection getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.direction
     *
     * @param direction the value for work_log_person_event.direction
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setDirection(WorkLogEventDirection direction) {
        this.direction = direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.state_id
     *
     * @return the value of work_log_person_event.state_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public Long getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.state_id
     *
     * @param stateId the value for work_log_person_event.state_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setStateId(Long stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.state_tag
     *
     * @return the value of work_log_person_event.state_tag
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public EntityStateTag getStateTag() {
        return stateTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.state_tag
     *
     * @param stateTag the value for work_log_person_event.state_tag
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setStateTag(EntityStateTag stateTag) {
        this.stateTag = stateTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.error
     *
     * @return the value of work_log_person_event.error
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.error
     *
     * @param error the value for work_log_person_event.error
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.received_data
     *
     * @return the value of work_log_person_event.received_data
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public String getReceivedData() {
        return receivedData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.received_data
     *
     * @param receivedData the value for work_log_person_event.received_data
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setReceivedData(String receivedData) {
        this.receivedData = receivedData == null ? null : receivedData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.group_id
     *
     * @return the value of work_log_person_event.group_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.group_id
     *
     * @param groupId the value for work_log_person_event.group_id
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_log_person_event.origin
     *
     * @return the value of work_log_person_event.origin
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public WorkLogEventOrigin getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_log_person_event.origin
     *
     * @param origin the value for work_log_person_event.origin
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    public void setOrigin(WorkLogEventOrigin origin) {
        this.origin = origin;
    }
}