package it.memelabs.gn.services.job;

/**
 * 05/05/2014
 *
 * @author Andrea Fossi
 */
public enum JobTypeOfbiz {
    GN_JOB_NOP,
    GN_ACT_JOB_AUTHORIZATION_EXPIRING,//    GN_ACT_JOB_AUTH_EXPIRING
    GN_ACT_JOB_AUTHORIZATION_EXPIRING_MANAGE_OLD,//    GN_ACT_JOB_AUTH_EXPIRING_MANAGE_OLD
    GN_ACT_JOB_PARTY_INVITATION_NOTIFICATION_PENDING,//    GN_ACT_JOB_PARTY_INVITATION_PENDING
    GN_ACT_JOB_PARTY_INVITATION_MARK_EXPIRED,//    GN_ACT_JOB_PARTY_INVITATION_MARK_EXPIRED
    GN_ACT_JOB_PARTY_INVITATION_JOB_MANAGE_OLD,//    GN_ACT_JOB_PARTY_INVITATION_EXPIRING_MANAGE_OLD
    GN_ACT_JOB_AUTHORIZATION_PUBLICATION_REMINDER,//    GN_ACT_JOB_AUTHORIZATION_PUBLICATION_REMINDER
    GN_ACT_JOB_AUTHORIZATION_PUBLICATION_REMINDER_MANAGE_OLD,//    GN_ACT_JOB_AUTHORIZATION_PUBLICATION_REMINDER_OLD
    GN_ACT_JOB_AUTHORIZATION_TO_BE_VALIDATED_REMINDER,//    GN_ACT_JOB_AUTHORIZATION_TO_BE_VALIDATED_REMINDER
    GN_ACT_JOB_AUTHORIZATION_TO_BE_VALIDATED_REMINDER_MANAGE_OLD,//    GN_ACT_JOB_AUTHORIZATION_TO_BE_VALIDATED_REMINDER_OLD
}
