package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.Accident;
import it.memelabs.smartnebula.lmm.persistence.main.dto.AccidentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AccidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int countByExample(AccidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int deleteByExample(AccidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int insert(Accident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int insertSelective(Accident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    List<Accident> selectByExampleWithRowbounds(AccidentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    List<Accident> selectByExample(AccidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    Accident selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int updateByExampleSelective(@Param("record") Accident record, @Param("example") AccidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int updateByExample(@Param("record") Accident record, @Param("example") AccidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int updateByPrimaryKeySelective(Accident record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accident
     *
     * @mbggenerated Mon Oct 31 14:51:57 CET 2016
     */
    int updateByPrimaryKey(Accident record);
}