package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ActivityJob;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ActivityJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ActivityJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int countByExample(ActivityJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int deleteByExample(ActivityJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int insert(ActivityJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int insertSelective(ActivityJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    List<ActivityJob> selectByExampleWithRowbounds(ActivityJobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    List<ActivityJob> selectByExample(ActivityJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    ActivityJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ActivityJob record, @Param("example") ActivityJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int updateByExample(@Param("record") ActivityJob record, @Param("example") ActivityJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int updateByPrimaryKeySelective(ActivityJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_job
     *
     * @mbggenerated Mon Aug 08 11:32:05 CEST 2016
     */
    int updateByPrimaryKey(ActivityJob record);
}