package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.AntimafiaProcess;
import it.memelabs.smartnebula.lmm.persistence.main.dto.AntimafiaProcessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AntimafiaProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int countByExample(AntimafiaProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int deleteByExample(AntimafiaProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int insert(AntimafiaProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int insertSelective(AntimafiaProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    List<AntimafiaProcess> selectByExampleWithRowbounds(AntimafiaProcessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    List<AntimafiaProcess> selectByExample(AntimafiaProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    AntimafiaProcess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int updateByExampleSelective(@Param("record") AntimafiaProcess record, @Param("example") AntimafiaProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int updateByExample(@Param("record") AntimafiaProcess record, @Param("example") AntimafiaProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int updateByPrimaryKeySelective(AntimafiaProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process
     *
     * @mbggenerated Wed Nov 23 11:44:05 CET 2016
     */
    int updateByPrimaryKey(AntimafiaProcess record);
}