package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.AntimafiaProcessPhase;
import it.memelabs.smartnebula.lmm.persistence.main.dto.AntimafiaProcessPhaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AntimafiaProcessPhaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int countByExample(AntimafiaProcessPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int deleteByExample(AntimafiaProcessPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int insert(AntimafiaProcessPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int insertSelective(AntimafiaProcessPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    List<AntimafiaProcessPhase> selectByExampleWithRowbounds(AntimafiaProcessPhaseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    List<AntimafiaProcessPhase> selectByExample(AntimafiaProcessPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    AntimafiaProcessPhase selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int updateByExampleSelective(@Param("record") AntimafiaProcessPhase record, @Param("example") AntimafiaProcessPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int updateByExample(@Param("record") AntimafiaProcessPhase record, @Param("example") AntimafiaProcessPhaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int updateByPrimaryKeySelective(AntimafiaProcessPhase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antimafia_process_phase
     *
     * @mbggenerated Tue Jul 05 16:08:36 CEST 2016
     */
    int updateByPrimaryKey(AntimafiaProcessPhase record);
}