package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.AttachmentType;
import it.memelabs.smartnebula.lmm.persistence.main.dto.AttachmentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AttachmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int countByExample(AttachmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int deleteByExample(AttachmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int insert(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int insertSelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    List<AttachmentType> selectByExampleWithRowbounds(AttachmentTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    List<AttachmentType> selectByExample(AttachmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    AttachmentType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int updateByExampleSelective(@Param("record") AttachmentType record, @Param("example") AttachmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int updateByExample(@Param("record") AttachmentType record, @Param("example") AttachmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int updateByPrimaryKeySelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Thu May 05 16:19:08 CEST 2016
     */
    int updateByPrimaryKey(AttachmentType record);
}