package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.CommentType;
import it.memelabs.smartnebula.lmm.persistence.main.dto.CommentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int countByExample(CommentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int deleteByExample(CommentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int insert(CommentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int insertSelective(CommentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    List<CommentType> selectByExampleWithRowbounds(CommentTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    List<CommentType> selectByExample(CommentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    CommentType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int updateByExampleSelective(@Param("record") CommentType record, @Param("example") CommentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int updateByExample(@Param("record") CommentType record, @Param("example") CommentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int updateByPrimaryKeySelective(CommentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_type
     *
     * @mbggenerated Thu Oct 20 18:09:17 CEST 2016
     */
    int updateByPrimaryKey(CommentType record);
}