package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyClassification;
import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompanyClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(CompanyClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(CompanyClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(CompanyClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(CompanyClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyClassification> selectByExampleWithRowbounds(CompanyClassificationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyClassification> selectByExample(CompanyClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    CompanyClassification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") CompanyClassification record, @Param("example") CompanyClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") CompanyClassification record, @Param("example") CompanyClassificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(CompanyClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_classification
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(CompanyClassification record);
}