package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyCategory;
import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompanyCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(CompanyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(CompanyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(CompanyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(CompanyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyCategory> selectByExampleWithRowbounds(CompanyCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyCategory> selectByExample(CompanyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    CompanyCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") CompanyCategory record, @Param("example") CompanyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") CompanyCategory record, @Param("example") CompanyCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(CompanyCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(CompanyCategory record);
}