package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyComposition;
import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyCompositionExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.CompanyCompositionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompanyCompositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(CompanyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(CompanyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(CompanyCompositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(CompanyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(CompanyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyComposition> selectByExampleWithRowbounds(CompanyCompositionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<CompanyComposition> selectByExample(CompanyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    CompanyComposition selectByPrimaryKey(CompanyCompositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") CompanyComposition record, @Param("example") CompanyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") CompanyComposition record, @Param("example") CompanyCompositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(CompanyComposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_composition
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(CompanyComposition record);
}