package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLocation;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLocationExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLocationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConstructionSiteLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int countByExample(ConstructionSiteLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int deleteByExample(ConstructionSiteLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int deleteByPrimaryKey(ConstructionSiteLocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int insert(ConstructionSiteLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int insertSelective(ConstructionSiteLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    List<ConstructionSiteLocation> selectByExampleWithRowbounds(ConstructionSiteLocationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    List<ConstructionSiteLocation> selectByExample(ConstructionSiteLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    ConstructionSiteLocation selectByPrimaryKey(ConstructionSiteLocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ConstructionSiteLocation record, @Param("example") ConstructionSiteLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int updateByExample(@Param("record") ConstructionSiteLocation record, @Param("example") ConstructionSiteLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int updateByPrimaryKeySelective(ConstructionSiteLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_location
     *
     * @mbggenerated Mon May 16 15:17:33 CEST 2016
     */
    int updateByPrimaryKey(ConstructionSiteLocation record);
}