package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogWeatherCatalog;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogWeatherCatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConstructionSiteLogWeatherCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int countByExample(ConstructionSiteLogWeatherCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int deleteByExample(ConstructionSiteLogWeatherCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int insert(ConstructionSiteLogWeatherCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int insertSelective(ConstructionSiteLogWeatherCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    List<ConstructionSiteLogWeatherCatalog> selectByExampleWithRowbounds(ConstructionSiteLogWeatherCatalogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    List<ConstructionSiteLogWeatherCatalog> selectByExample(ConstructionSiteLogWeatherCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    ConstructionSiteLogWeatherCatalog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ConstructionSiteLogWeatherCatalog record, @Param("example") ConstructionSiteLogWeatherCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByExample(@Param("record") ConstructionSiteLogWeatherCatalog record, @Param("example") ConstructionSiteLogWeatherCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByPrimaryKeySelective(ConstructionSiteLogWeatherCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_catalog
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByPrimaryKey(ConstructionSiteLogWeatherCatalog record);
}