package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogActivity;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConstructionSiteLogActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int countByExample(ConstructionSiteLogActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int deleteByExample(ConstructionSiteLogActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int insert(ConstructionSiteLogActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int insertSelective(ConstructionSiteLogActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    List<ConstructionSiteLogActivity> selectByExampleWithRowbounds(ConstructionSiteLogActivityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    List<ConstructionSiteLogActivity> selectByExample(ConstructionSiteLogActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    ConstructionSiteLogActivity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ConstructionSiteLogActivity record, @Param("example") ConstructionSiteLogActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int updateByExample(@Param("record") ConstructionSiteLogActivity record, @Param("example") ConstructionSiteLogActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int updateByPrimaryKeySelective(ConstructionSiteLogActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_activity
     *
     * @mbggenerated Fri Oct 21 16:42:40 CEST 2016
     */
    int updateByPrimaryKey(ConstructionSiteLogActivity record);
}