package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSite;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConstructionSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int countByExample(ConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int deleteByExample(ConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int insert(ConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int insertSelective(ConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    List<ConstructionSite> selectByExampleWithRowbounds(ConstructionSiteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    List<ConstructionSite> selectByExample(ConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    ConstructionSite selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ConstructionSite record, @Param("example") ConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int updateByExample(@Param("record") ConstructionSite record, @Param("example") ConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int updateByPrimaryKeySelective(ConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site
     *
     * @mbggenerated Fri Jul 01 14:44:44 CEST 2016
     */
    int updateByPrimaryKey(ConstructionSite record);
}