package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogWeatherData;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ConstructionSiteLogWeatherDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ConstructionSiteLogWeatherDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int countByExample(ConstructionSiteLogWeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int deleteByExample(ConstructionSiteLogWeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int insert(ConstructionSiteLogWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int insertSelective(ConstructionSiteLogWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    List<ConstructionSiteLogWeatherData> selectByExampleWithRowbounds(ConstructionSiteLogWeatherDataExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    List<ConstructionSiteLogWeatherData> selectByExample(ConstructionSiteLogWeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    ConstructionSiteLogWeatherData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ConstructionSiteLogWeatherData record, @Param("example") ConstructionSiteLogWeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByExample(@Param("record") ConstructionSiteLogWeatherData record, @Param("example") ConstructionSiteLogWeatherDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByPrimaryKeySelective(ConstructionSiteLogWeatherData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_site_log_weather_data
     *
     * @mbggenerated Thu Oct 27 11:22:29 CEST 2016
     */
    int updateByPrimaryKey(ConstructionSiteLogWeatherData record);
}