package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ContractConstructionSite;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ContractConstructionSiteExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ContractConstructionSiteKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContractConstructionSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int countByExample(ContractConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int deleteByExample(ContractConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int deleteByPrimaryKey(ContractConstructionSiteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int insert(ContractConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int insertSelective(ContractConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    List<ContractConstructionSite> selectByExampleWithRowbounds(ContractConstructionSiteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    List<ContractConstructionSite> selectByExample(ContractConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    ContractConstructionSite selectByPrimaryKey(ContractConstructionSiteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int updateByExampleSelective(@Param("record") ContractConstructionSite record, @Param("example") ContractConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int updateByExample(@Param("record") ContractConstructionSite record, @Param("example") ContractConstructionSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int updateByPrimaryKeySelective(ContractConstructionSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_construction_site
     *
     * @mbggenerated Tue May 10 18:03:05 CEST 2016
     */
    int updateByPrimaryKey(ContractConstructionSite record);
}