package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.ContractCatalog;
import it.memelabs.smartnebula.lmm.persistence.main.dto.ContractCatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContractCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int countByExample(ContractCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int deleteByExample(ContractCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int insert(ContractCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int insertSelective(ContractCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    List<ContractCatalog> selectByExampleWithRowbounds(ContractCatalogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    List<ContractCatalog> selectByExample(ContractCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    ContractCatalog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int updateByExampleSelective(@Param("record") ContractCatalog record, @Param("example") ContractCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int updateByExample(@Param("record") ContractCatalog record, @Param("example") ContractCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int updateByPrimaryKeySelective(ContractCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_catalog
     *
     * @mbggenerated Mon Dec 05 15:22:54 CET 2016
     */
    int updateByPrimaryKey(ContractCatalog record);
}