package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.EmploymentToExport;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EmploymentToExportExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EmploymentToExportKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmploymentToExportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int countByExample(EmploymentToExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByExample(EmploymentToExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByPrimaryKey(EmploymentToExportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insert(EmploymentToExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insertSelective(EmploymentToExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<EmploymentToExport> selectByExampleWithRowbounds(EmploymentToExportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<EmploymentToExport> selectByExample(EmploymentToExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    EmploymentToExport selectByPrimaryKey(EmploymentToExportKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExampleSelective(@Param("record") EmploymentToExport record, @Param("example") EmploymentToExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExample(@Param("record") EmploymentToExport record, @Param("example") EmploymentToExportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKeySelective(EmploymentToExport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employment_to_export
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKey(EmploymentToExport record);
}