package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.EntityState;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EntityStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EntityStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int countByExample(EntityStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int deleteByExample(EntityStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int insert(EntityState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int insertSelective(EntityState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    List<EntityState> selectByExampleWithRowbounds(EntityStateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    List<EntityState> selectByExample(EntityStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    EntityState selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int updateByExampleSelective(@Param("record") EntityState record, @Param("example") EntityStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int updateByExample(@Param("record") EntityState record, @Param("example") EntityStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int updateByPrimaryKeySelective(EntityState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity_state
     *
     * @mbggenerated Tue Jun 07 15:08:27 CEST 2016
     */
    int updateByPrimaryKey(EntityState record);
}