package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentType;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EquipmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<EquipmentType> selectByExampleWithRowbounds(EquipmentTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<EquipmentType> selectByExample(EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    EquipmentType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") EquipmentType record, @Param("example") EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") EquipmentType record, @Param("example") EquipmentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(EquipmentType record);
}