package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentCategory;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EquipmentCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(EquipmentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(EquipmentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(EquipmentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(EquipmentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<EquipmentCategory> selectByExampleWithRowbounds(EquipmentCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<EquipmentCategory> selectByExample(EquipmentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    EquipmentCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") EquipmentCategory record, @Param("example") EquipmentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") EquipmentCategory record, @Param("example") EquipmentCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(EquipmentCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_category
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(EquipmentCategory record);
}