package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentEmployment;
import it.memelabs.smartnebula.lmm.persistence.main.dto.EquipmentEmploymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EquipmentEmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int countByExample(EquipmentEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByExample(EquipmentEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insert(EquipmentEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insertSelective(EquipmentEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<EquipmentEmployment> selectByExampleWithRowbounds(EquipmentEmploymentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<EquipmentEmployment> selectByExample(EquipmentEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    EquipmentEmployment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExampleSelective(@Param("record") EquipmentEmployment record, @Param("example") EquipmentEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExample(@Param("record") EquipmentEmployment record, @Param("example") EquipmentEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKeySelective(EquipmentEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKey(EquipmentEmployment record);
}