package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.Geo;
import it.memelabs.smartnebula.lmm.persistence.main.dto.GeoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GeoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int countByExample(GeoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByExample(GeoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByPrimaryKey(String geoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insert(Geo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insertSelective(Geo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<Geo> selectByExampleWithRowbounds(GeoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<Geo> selectByExample(GeoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    Geo selectByPrimaryKey(String geoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExampleSelective(@Param("record") Geo record, @Param("example") GeoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExample(@Param("record") Geo record, @Param("example") GeoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKeySelective(Geo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKey(Geo record);
}