package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.GeoType;
import it.memelabs.smartnebula.lmm.persistence.main.dto.GeoTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GeoTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int countByExample(GeoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByExample(GeoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByPrimaryKey(String geoTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insert(GeoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insertSelective(GeoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<GeoType> selectByExampleWithRowbounds(GeoTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<GeoType> selectByExample(GeoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    GeoType selectByPrimaryKey(String geoTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExampleSelective(@Param("record") GeoType record, @Param("example") GeoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExample(@Param("record") GeoType record, @Param("example") GeoTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKeySelective(GeoType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geo_type
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKey(GeoType record);
}