package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.JobOrder;
import it.memelabs.smartnebula.lmm.persistence.main.dto.JobOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface JobOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int countByExample(JobOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int deleteByExample(JobOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int insert(JobOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int insertSelective(JobOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    List<JobOrder> selectByExampleWithRowbounds(JobOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    List<JobOrder> selectByExample(JobOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    JobOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByExampleSelective(@Param("record") JobOrder record, @Param("example") JobOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByExample(@Param("record") JobOrder record, @Param("example") JobOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByPrimaryKeySelective(JobOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_order
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByPrimaryKey(JobOrder record);
}