package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.LotLocation;
import it.memelabs.smartnebula.lmm.persistence.main.dto.LotLocationExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.LotLocationKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LotLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int countByExample(LotLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int deleteByExample(LotLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int deleteByPrimaryKey(LotLocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int insert(LotLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int insertSelective(LotLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    List<LotLocation> selectByExampleWithRowbounds(LotLocationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    List<LotLocation> selectByExample(LotLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    LotLocation selectByPrimaryKey(LotLocationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int updateByExampleSelective(@Param("record") LotLocation record, @Param("example") LotLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int updateByExample(@Param("record") LotLocation record, @Param("example") LotLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int updateByPrimaryKeySelective(LotLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot_location
     *
     * @mbggenerated Fri May 06 10:01:41 CEST 2016
     */
    int updateByPrimaryKey(LotLocation record);
}