package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.Lot;
import it.memelabs.smartnebula.lmm.persistence.main.dto.LotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int countByExample(LotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int deleteByExample(LotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int insert(Lot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int insertSelective(Lot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    List<Lot> selectByExampleWithRowbounds(LotExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    List<Lot> selectByExample(LotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    Lot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int updateByExampleSelective(@Param("record") Lot record, @Param("example") LotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int updateByExample(@Param("record") Lot record, @Param("example") LotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int updateByPrimaryKeySelective(Lot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lot
     *
     * @mbggenerated Mon May 09 18:58:53 CEST 2016
     */
    int updateByPrimaryKey(Lot record);
}