package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.NodeConfiguration;
import it.memelabs.smartnebula.lmm.persistence.main.dto.NodeConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NodeConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int countByExample(NodeConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int deleteByExample(NodeConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int insert(NodeConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int insertSelective(NodeConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    List<NodeConfiguration> selectByExampleWithRowbounds(NodeConfigurationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    List<NodeConfiguration> selectByExample(NodeConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    NodeConfiguration selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NodeConfiguration record, @Param("example") NodeConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NodeConfiguration record, @Param("example") NodeConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NodeConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NodeConfiguration record);
}