package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.NotificationEvent;
import it.memelabs.smartnebula.lmm.persistence.main.dto.NotificationEventExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.NotificationEventKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotificationEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int countByExample(NotificationEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int deleteByExample(NotificationEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int deleteByPrimaryKey(NotificationEventKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int insert(NotificationEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int insertSelective(NotificationEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    List<NotificationEvent> selectByExampleWithRowbounds(NotificationEventExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    List<NotificationEvent> selectByExample(NotificationEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    NotificationEvent selectByPrimaryKey(NotificationEventKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByExampleSelective(@Param("record") NotificationEvent record, @Param("example") NotificationEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByExample(@Param("record") NotificationEvent record, @Param("example") NotificationEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByPrimaryKeySelective(NotificationEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_event
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByPrimaryKey(NotificationEvent record);
}