package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.NotificationGroup;
import it.memelabs.smartnebula.lmm.persistence.main.dto.NotificationGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NotificationGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int countByExample(NotificationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int deleteByExample(NotificationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int insert(NotificationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int insertSelective(NotificationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    List<NotificationGroup> selectByExampleWithRowbounds(NotificationGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    List<NotificationGroup> selectByExample(NotificationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    NotificationGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByExampleSelective(@Param("record") NotificationGroup record, @Param("example") NotificationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByExample(@Param("record") NotificationGroup record, @Param("example") NotificationGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByPrimaryKeySelective(NotificationGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification_group
     *
     * @mbggenerated Tue Nov 15 12:38:17 CET 2016
     */
    int updateByPrimaryKey(NotificationGroup record);
}