package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonRole;
import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(PersonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(PersonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<PersonRole> selectByExampleWithRowbounds(PersonRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<PersonRole> selectByExample(PersonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    PersonRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") PersonRole record, @Param("example") PersonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") PersonRole record, @Param("example") PersonRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(PersonRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_role
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(PersonRole record);
}