package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonEmployment;
import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonEmploymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonEmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int countByExample(PersonEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByExample(PersonEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insert(PersonEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int insertSelective(PersonEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<PersonEmployment> selectByExampleWithRowbounds(PersonEmploymentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    List<PersonEmployment> selectByExample(PersonEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    PersonEmployment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExampleSelective(@Param("record") PersonEmployment record, @Param("example") PersonEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByExample(@Param("record") PersonEmployment record, @Param("example") PersonEmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKeySelective(PersonEmployment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_employment
     *
     * @mbggenerated Thu Dec 15 17:58:12 CET 2016
     */
    int updateByPrimaryKey(PersonEmployment record);
}