package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonJob;
import it.memelabs.smartnebula.lmm.persistence.main.dto.PersonJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PersonJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int countByExample(PersonJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByExample(PersonJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insert(PersonJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int insertSelective(PersonJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<PersonJob> selectByExampleWithRowbounds(PersonJobExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    List<PersonJob> selectByExample(PersonJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    PersonJob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExampleSelective(@Param("record") PersonJob record, @Param("example") PersonJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByExample(@Param("record") PersonJob record, @Param("example") PersonJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKeySelective(PersonJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_job
     *
     * @mbggenerated Wed May 04 12:48:14 CEST 2016
     */
    int updateByPrimaryKey(PersonJob record);
}