package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.PostalAddress;
import it.memelabs.smartnebula.lmm.persistence.main.dto.PostalAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostalAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int countByExample(PostalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByExample(PostalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insert(PostalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int insertSelective(PostalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<PostalAddress> selectByExampleWithRowbounds(PostalAddressExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    List<PostalAddress> selectByExample(PostalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    PostalAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExampleSelective(@Param("record") PostalAddress record, @Param("example") PostalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByExample(@Param("record") PostalAddress record, @Param("example") PostalAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKeySelective(PostalAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table postal_address
     *
     * @mbggenerated Fri May 06 17:57:24 CEST 2016
     */
    int updateByPrimaryKey(PostalAddress record);
}