package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.Prefecture;
import it.memelabs.smartnebula.lmm.persistence.main.dto.PrefectureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PrefectureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int countByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int deleteByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int insert(Prefecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int insertSelective(Prefecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    List<Prefecture> selectByExampleWithRowbounds(PrefectureExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    List<Prefecture> selectByExample(PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    Prefecture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int updateByExampleSelective(@Param("record") Prefecture record, @Param("example") PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int updateByExample(@Param("record") Prefecture record, @Param("example") PrefectureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int updateByPrimaryKeySelective(Prefecture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture
     *
     * @mbggenerated Tue May 17 10:49:53 CEST 2016
     */
    int updateByPrimaryKey(Prefecture record);
}