package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.SecurityRolePermission;
import it.memelabs.smartnebula.lmm.persistence.main.dto.SecurityRolePermissionExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.SecurityRolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SecurityRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int countByExample(SecurityRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int deleteByExample(SecurityRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int deleteByPrimaryKey(SecurityRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int insert(SecurityRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int insertSelective(SecurityRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    List<SecurityRolePermission> selectByExampleWithRowbounds(SecurityRolePermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    List<SecurityRolePermission> selectByExample(SecurityRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    SecurityRolePermission selectByPrimaryKey(SecurityRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByExampleSelective(@Param("record") SecurityRolePermission record, @Param("example") SecurityRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByExample(@Param("record") SecurityRolePermission record, @Param("example") SecurityRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByPrimaryKeySelective(SecurityRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role_permission
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByPrimaryKey(SecurityRolePermission record);
}