package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.SecurityRole;
import it.memelabs.smartnebula.lmm.persistence.main.dto.SecurityRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SecurityRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int countByExample(SecurityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int deleteByExample(SecurityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int insert(SecurityRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int insertSelective(SecurityRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    List<SecurityRole> selectByExampleWithRowbounds(SecurityRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    List<SecurityRole> selectByExample(SecurityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    SecurityRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByExampleSelective(@Param("record") SecurityRole record, @Param("example") SecurityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByExample(@Param("record") SecurityRole record, @Param("example") SecurityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByPrimaryKeySelective(SecurityRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_role
     *
     * @mbggenerated Tue Aug 30 09:49:36 CEST 2016
     */
    int updateByPrimaryKey(SecurityRole record);
}