package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.UserLoginPersistent;
import it.memelabs.smartnebula.lmm.persistence.main.dto.UserLoginPersistentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserLoginPersistentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int countByExample(UserLoginPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int deleteByExample(UserLoginPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int insert(UserLoginPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int insertSelective(UserLoginPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    List<UserLoginPersistent> selectByExampleWithRowbounds(UserLoginPersistentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    List<UserLoginPersistent> selectByExample(UserLoginPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    UserLoginPersistent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int updateByExampleSelective(@Param("record") UserLoginPersistent record, @Param("example") UserLoginPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int updateByExample(@Param("record") UserLoginPersistent record, @Param("example") UserLoginPersistentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int updateByPrimaryKeySelective(UserLoginPersistent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login
     *
     * @mbggenerated Wed Aug 31 15:51:56 CEST 2016
     */
    int updateByPrimaryKey(UserLoginPersistent record);
}