package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WbsSubPart;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WbsSubPartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WbsSubPartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int countByExample(WbsSubPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int deleteByExample(WbsSubPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int insert(WbsSubPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int insertSelective(WbsSubPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    List<WbsSubPart> selectByExampleWithRowbounds(WbsSubPartExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    List<WbsSubPart> selectByExample(WbsSubPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    WbsSubPart selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByExampleSelective(@Param("record") WbsSubPart record, @Param("example") WbsSubPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByExample(@Param("record") WbsSubPart record, @Param("example") WbsSubPartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByPrimaryKeySelective(WbsSubPart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wbs_sub_part
     *
     * @mbggenerated Thu May 05 10:57:10 CEST 2016
     */
    int updateByPrimaryKey(WbsSubPart record);
}