package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogEquipment;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogEquipmentExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogEquipmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeeklyWorkLogEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int countByExample(WeeklyWorkLogEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int deleteByExample(WeeklyWorkLogEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int deleteByPrimaryKey(WeeklyWorkLogEquipmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int insert(WeeklyWorkLogEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int insertSelective(WeeklyWorkLogEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    List<WeeklyWorkLogEquipment> selectByExampleWithRowbounds(WeeklyWorkLogEquipmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    List<WeeklyWorkLogEquipment> selectByExample(WeeklyWorkLogEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    WeeklyWorkLogEquipment selectByPrimaryKey(WeeklyWorkLogEquipmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByExampleSelective(@Param("record") WeeklyWorkLogEquipment record, @Param("example") WeeklyWorkLogEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByExample(@Param("record") WeeklyWorkLogEquipment record, @Param("example") WeeklyWorkLogEquipmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByPrimaryKeySelective(WeeklyWorkLogEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_equipment
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByPrimaryKey(WeeklyWorkLogEquipment record);
}