package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogPerson;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogPersonExample;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogPersonKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeeklyWorkLogPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int countByExample(WeeklyWorkLogPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int deleteByExample(WeeklyWorkLogPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int deleteByPrimaryKey(WeeklyWorkLogPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int insert(WeeklyWorkLogPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int insertSelective(WeeklyWorkLogPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    List<WeeklyWorkLogPerson> selectByExampleWithRowbounds(WeeklyWorkLogPersonExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    List<WeeklyWorkLogPerson> selectByExample(WeeklyWorkLogPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    WeeklyWorkLogPerson selectByPrimaryKey(WeeklyWorkLogPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByExampleSelective(@Param("record") WeeklyWorkLogPerson record, @Param("example") WeeklyWorkLogPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByExample(@Param("record") WeeklyWorkLogPerson record, @Param("example") WeeklyWorkLogPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByPrimaryKeySelective(WeeklyWorkLogPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log_person
     *
     * @mbggenerated Fri Jun 10 17:55:26 CEST 2016
     */
    int updateByPrimaryKey(WeeklyWorkLogPerson record);
}