package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLog;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WeeklyWorkLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeeklyWorkLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int countByExample(WeeklyWorkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int deleteByExample(WeeklyWorkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int insert(WeeklyWorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int insertSelective(WeeklyWorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    List<WeeklyWorkLog> selectByExampleWithRowbounds(WeeklyWorkLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    List<WeeklyWorkLog> selectByExample(WeeklyWorkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    WeeklyWorkLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int updateByExampleSelective(@Param("record") WeeklyWorkLog record, @Param("example") WeeklyWorkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int updateByExample(@Param("record") WeeklyWorkLog record, @Param("example") WeeklyWorkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int updateByPrimaryKeySelective(WeeklyWorkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_work_log
     *
     * @mbggenerated Tue Jun 14 10:47:07 CEST 2016
     */
    int updateByPrimaryKey(WeeklyWorkLog record);
}