package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WorkLogPersonEvent;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WorkLogPersonEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkLogPersonEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int countByExample(WorkLogPersonEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int deleteByExample(WorkLogPersonEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int insert(WorkLogPersonEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int insertSelective(WorkLogPersonEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    List<WorkLogPersonEvent> selectByExampleWithRowbounds(WorkLogPersonEventExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    List<WorkLogPersonEvent> selectByExample(WorkLogPersonEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    WorkLogPersonEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByExampleSelective(@Param("record") WorkLogPersonEvent record, @Param("example") WorkLogPersonEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByExample(@Param("record") WorkLogPersonEvent record, @Param("example") WorkLogPersonEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByPrimaryKeySelective(WorkLogPersonEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_person_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByPrimaryKey(WorkLogPersonEvent record);
}