package it.memelabs.smartnebula.lmm.persistence.main.mapper;

import it.memelabs.smartnebula.lmm.persistence.main.dto.WorkLogEquipmentEvent;
import it.memelabs.smartnebula.lmm.persistence.main.dto.WorkLogEquipmentEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkLogEquipmentEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int countByExample(WorkLogEquipmentEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int deleteByExample(WorkLogEquipmentEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int insert(WorkLogEquipmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int insertSelective(WorkLogEquipmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    List<WorkLogEquipmentEvent> selectByExampleWithRowbounds(WorkLogEquipmentEventExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    List<WorkLogEquipmentEvent> selectByExample(WorkLogEquipmentEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    WorkLogEquipmentEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByExampleSelective(@Param("record") WorkLogEquipmentEvent record, @Param("example") WorkLogEquipmentEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByExample(@Param("record") WorkLogEquipmentEvent record, @Param("example") WorkLogEquipmentEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByPrimaryKeySelective(WorkLogEquipmentEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_log_equipment_event
     *
     * @mbggenerated Wed Jan 04 17:07:15 CET 2017
     */
    int updateByPrimaryKey(WorkLogEquipmentEvent record);
}